Repository OCA/account-financial-tools, pull requests merged in 2019-03, with the labels that each got.

#741 [12.0] [MIG] account_move_fiscal_year
  account_move_fiscal_year/README.rst
  account_move_fiscal_year/__init__.py
  account_move_fiscal_year/__manifest__.py
  account_move_fiscal_year/i18n/account_move_fiscal_year.pot
  account_move_fiscal_year/i18n/am.po
  account_move_fiscal_year/i18n/ar.po
  account_move_fiscal_year/i18n/ca.po
  account_move_fiscal_year/i18n/de.po
  account_move_fiscal_year/i18n/es.po
  account_move_fiscal_year/i18n/es_CO.po
  account_move_fiscal_year/i18n/es_EC.po
  account_move_fiscal_year/i18n/fr.po
  account_move_fiscal_year/i18n/fr_FR.po
  account_move_fiscal_year/i18n/gl.po
  account_move_fiscal_year/i18n/hr.po
  account_move_fiscal_year/i18n/hr_HR.po
  account_move_fiscal_year/i18n/it.po
  account_move_fiscal_year/i18n/nl.po
  account_move_fiscal_year/i18n/pt.po
  account_move_fiscal_year/i18n/pt_BR.po
  account_move_fiscal_year/i18n/pt_PT.po
  account_move_fiscal_year/i18n/sl.po
  account_move_fiscal_year/i18n/tr_TR.po
  account_move_fiscal_year/models/__init__.py
  account_move_fiscal_year/models/account_move.py
  account_move_fiscal_year/models/account_move_line.py
  account_move_fiscal_year/models/res_company.py
  account_move_fiscal_year/readme/CONFIGURE.rst
  account_move_fiscal_year/readme/CONTRIBUTORS.rst
  account_move_fiscal_year/readme/DESCRIPTION.rst
  account_move_fiscal_year/readme/INSTALL.rst
  account_move_fiscal_year/readme/USAGE.rst
  account_move_fiscal_year/static/description/icon.png
  account_move_fiscal_year/static/description/index.html
  account_move_fiscal_year/tests/__init__.py
  account_move_fiscal_year/tests/test_account_move_fiscal_year.py
  account_move_fiscal_year/views/account_move.xml
  account_move_fiscal_year/views/account_move_line.xml
Labels: approved, needs review, ready to merge

#769 [12.0][MIG] account balance line
  account_balance_line/README.rst
  account_balance_line/__init__.py
  account_balance_line/__manifest__.py
  account_balance_line/i18n/account_balance_line.pot
  account_balance_line/i18n/ar.po
  account_balance_line/i18n/bs.po
  account_balance_line/i18n/ca.po
  account_balance_line/i18n/cs.po
  account_balance_line/i18n/de.po
  account_balance_line/i18n/en_GB.po
  account_balance_line/i18n/es.po
  account_balance_line/i18n/es_CR.po
  account_balance_line/i18n/es_EC.po
  account_balance_line/i18n/es_MX.po
  account_balance_line/i18n/fr.po
  account_balance_line/i18n/gl.po
  account_balance_line/i18n/hr.po
  account_balance_line/i18n/hr_HR.po
  account_balance_line/i18n/hu.po
  account_balance_line/i18n/it.po
  account_balance_line/i18n/ja.po
  account_balance_line/i18n/lt.po
  account_balance_line/i18n/mk.po
  account_balance_line/i18n/mn.po
  account_balance_line/i18n/nb.po
  account_balance_line/i18n/nb_NO.po
  account_balance_line/i18n/nl.po
  account_balance_line/i18n/nl_BE.po
  account_balance_line/i18n/pt.po
  account_balance_line/i18n/pt_BR.po
  account_balance_line/i18n/pt_PT.po
  account_balance_line/i18n/ro.po
  account_balance_line/i18n/ru.po
  account_balance_line/i18n/sl.po
  account_balance_line/i18n/sv.po
  account_balance_line/i18n/tr.po
  account_balance_line/i18n/zh_CN.po
  account_balance_line/i18n/zh_TW.po
  account_balance_line/readme/CONTRIBUTORS.rst
  account_balance_line/readme/DESCRIPTION.rst
  account_balance_line/readme/USAGE.rst
  account_balance_line/static/description/icon.png
  account_balance_line/static/description/index.html
  account_balance_line/views/account_move_line_view.xml
Labels: approved, ready to merge

#695 [IMP] account_credit_control: UX improvements
  account_credit_control/__manifest__.py
  account_credit_control/data/data.xml
  account_credit_control/i18n/account_credit_control.pot
  account_credit_control/models/credit_control_line.py
  account_credit_control/models/credit_control_run.py
  account_credit_control/models/res_partner.py
  account_credit_control/security/account_security.xml
  account_credit_control/views/credit_control_line.xml
  account_credit_control/views/credit_control_run.xml
  account_credit_control/views/res_partner.xml
Labels: work in progress

#764 account_chart_update: allows to set the field matching order
  account_chart_update/README.rst
  account_chart_update/__manifest__.py
  account_chart_update/readme/USAGE.rst
  account_chart_update/static/description/index.html
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
  account_chart_update/wizard/wizard_chart_update_view.xml
Labels: approved, needs review, ready to merge

#780 [11.0][FIX] Add Credit Control Policy rule for multicompany
  account_credit_control/__manifest__.py
  account_credit_control/security/account_security.xml
Labels: approved

#735 [10.0][FIX] account_asset_management: fix stack while trying to log an error
  account_asset_management/models/account_asset.py
Labels: approved

#776 Fix asset view "search more" on parent_id field
  account_asset_management/views/account_asset.xml
Labels: approved
