Repository OCA/account-financial-tools, pull requests merged in 2020-11, with the labels that each got.

#986 [12.0][FIX] account_move_fiscal_month: error when creating account.move
  account_move_fiscal_month/models/account_move.py
Labels: approved, bot is merging ⏳, ready to merge

#1080 [13.0][FIX] account_move_line_tax_editable
  account_move_line_tax_editable/views/account_move.xml
Labels: approved, bot is merging ⏳

#1084 [FIX] account_document_reversal: modify to correct development_status
  account_document_reversal/__manifest__.py
Labels: bot is merging ⏳

#1085 [12.0][FIX] modify to correct development_status
  account_document_reversal/__manifest__.py
  account_payment_netting/__manifest__.py
Labels: bot is merging ⏳

#1086 [14.0][MIG] account_menu
  account_menu/README.rst
  account_menu/__init__.py
  account_menu/__manifest__.py
  account_menu/demo/res_groups.xml
  account_menu/i18n/account_menu.pot
  account_menu/models/__init__.py
  account_menu/models/account_group.py
  account_menu/models/account_tag.py
  account_menu/models/account_tax_group.py
  account_menu/readme/CONFIGURE.rst
  account_menu/readme/CONTRIBUTORS.rst
  account_menu/readme/DESCRIPTION.rst
  account_menu/static/description/icon.png
  account_menu/static/description/index.html
  account_menu/views/menu.xml
  account_menu/views/view_account_account_template.xml
  account_menu/views/view_account_bank_statement.xml
  account_menu/views/view_account_chart_template.xml
  account_menu/views/view_account_fiscal_position_template.xml
  account_menu/views/view_account_group.xml
  account_menu/views/view_account_tag.xml
  account_menu/views/view_account_tax_group.xml
  account_menu/views/view_account_tax_template.xml
  account_menu/views/view_account_type.xml
Labels: approved, bot is merging ⏳, ready to merge

#1095 [13.0][ADD] account_move_force_removal: Allow force removal account moves
  account_move_force_removal/__init__.py
  account_move_force_removal/__manifest__.py
  account_move_force_removal/models/__init__.py
  account_move_force_removal/models/account_move.py
  account_move_force_removal/readme/CONTRIBUTORS.rst
  account_move_force_removal/readme/DESCRIPTION.rst
  account_move_force_removal/readme/USAGE.rst
  account_move_force_removal/static/description/icon.png
  account_move_force_removal/tests/__init__.py
  account_move_force_removal/tests/test_move.py
  setup/account_move_force_removal/odoo/addons/account_move_force_removal
  setup/account_move_force_removal/setup.py
Labels: approved, bot is merging ⏳

#1094 [13.0][IMP] account_move_template, add options to overwrite output lines
  account_move_template/models/account_move_template.py
  account_move_template/readme/CONTRIBUTORS.rst
  account_move_template/readme/DESCRIPTION.rst
  account_move_template/readme/USAGE.rst
  account_move_template/tests/__init__.py
  account_move_template/tests/test_account_move_template_options.py
  account_move_template/view/account_move_template.xml
  account_move_template/wizard/account_move_template_run.py
  account_move_template/wizard/account_move_template_run_view.xml
Labels: approved, bot is merging ⏳, ready to merge
