Repository OCA/account-financial-tools, pull requests merged in 2020-09, with the labels that each got.

#1055 [12.0][IMP] account_asset_management: Add BI report
  account_asset_management/__init__.py
  account_asset_management/__manifest__.py
  account_asset_management/report/__init__.py
  account_asset_management/report/account_asset_report.py
  account_asset_management/report/account_asset_report_views.xml
  account_asset_management/security/ir.model.access.csv
Labels: approved, bot is merging ⏳, ready to merge

#1054 [10.0][BACKPORT] account_move_chatter backport from 12.0
  account_move_chatter/README.rst
  account_move_chatter/__init__.py
  account_move_chatter/__manifest__.py
  account_move_chatter/i18n/account_move_chatter.pot
  account_move_chatter/i18n/es.po
  account_move_chatter/i18n/pt.po
  account_move_chatter/models/__init__.py
  account_move_chatter/models/account_move.py
  account_move_chatter/readme/CONFIGURE.rst
  account_move_chatter/readme/CONTRIBUTORS.rst
  account_move_chatter/readme/DESCRIPTION.rst
  account_move_chatter/readme/USAGE.rst
  account_move_chatter/static/description/icon.png
  account_move_chatter/static/description/index.html
  account_move_chatter/views/account_move_views.xml
Labels: approved, enhancement, needs review

#1057 [ADD] account_cash_basis_group_base_line: add module
  account_cash_basis_group_base_line/README.rst
  account_cash_basis_group_base_line/__init__.py
  account_cash_basis_group_base_line/__manifest__.py
  account_cash_basis_group_base_line/models/__init__.py
  account_cash_basis_group_base_line/models/account_move.py
  account_cash_basis_group_base_line/readme/CONTRIBUTORS.rst
  account_cash_basis_group_base_line/readme/DESCRIPTION.rst
  account_cash_basis_group_base_line/readme/USAGE.rst
Labels: approved, bot is merging ⏳

#1060 [FIX] account_asset_management : empty message is posted if there are no no asset
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳
