Repository OCA/account-financial-tools, pull requests merged in 2020-07, with the labels that each got.

#1016 [IMP] account_asset_management: Add scheduled action for the depreciation asset entries creation.
  account_asset_management/__manifest__.py
  account_asset_management/data/cron.xml
  account_asset_management/readme/DESCRIPTION.rst
Labels: approved, bot is merging ⏳

#1022 [13.0][FIX] account_asset_management: fix remaining_value cache miss error.
  account_asset_management/models/account_asset_line.py
Labels: approved, bot is merging ⏳

#1014 [12.0] [ADD] new module account_voucher_print
  account_voucher_print/README.rst
  account_voucher_print/__init__.py
  account_voucher_print/__manifest__.py
  account_voucher_print/i18n/it.po
  account_voucher_print/models/__init__.py
  account_voucher_print/models/account_voucher.py
  account_voucher_print/readme/CONTRIBUTORS.rst
  account_voucher_print/readme/DESCRIPTION.rst
  account_voucher_print/static/description/index.html
  account_voucher_print/views/account_report.xml
  account_voucher_print/views/report_receipt.xml
Labels: approved, bot is merging ⏳

#1025 [12.0][FIX] account_asset_management: domain in multicompany
  account_asset_management/__manifest__.py
  account_asset_management/models/account_asset_profile.py
Labels: approved, bot is merging ⏳

#957 [13.0][add] account_tax_repartition_line_account
  account_tax_repartition_line_tax_group_account/README.rst
  account_tax_repartition_line_tax_group_account/__init__.py
  account_tax_repartition_line_tax_group_account/__manifest__.py
  account_tax_repartition_line_tax_group_account/models/__init__.py
  account_tax_repartition_line_tax_group_account/models/account_tax_group.py
  account_tax_repartition_line_tax_group_account/models/account_tax_repartition_line.py
  account_tax_repartition_line_tax_group_account/readme/CONFIGURE.rst
  account_tax_repartition_line_tax_group_account/readme/CONTRIBUTORS.rst
  account_tax_repartition_line_tax_group_account/readme/DESCRIPTION.rst
  account_tax_repartition_line_tax_group_account/readme/USAGE.rst
  account_tax_repartition_line_tax_group_account/static/description/icon.png
  account_tax_repartition_line_tax_group_account/static/description/index.html
  account_tax_repartition_line_tax_group_account/tests/__init__.py
  account_tax_repartition_line_tax_group_account/tests/test_account_tax_repartition_line_tax_group_account.py
  account_tax_repartition_line_tax_group_account/views/account_tax_group_views.xml
  setup/account_tax_repartition_line_tax_group_account/odoo/addons/account_tax_repartition_line_tax_group_account
  setup/account_tax_repartition_line_tax_group_account/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#983 [13.0][MIG] base_vat_optional_vies
  base_vat_optional_vies/README.rst
  base_vat_optional_vies/__init__.py
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/i18n/.gitkeep
  base_vat_optional_vies/i18n/base_vat_optional_vies.pot
  base_vat_optional_vies/i18n/es.po
  base_vat_optional_vies/i18n/hr.po
  base_vat_optional_vies/i18n/pt.po
  base_vat_optional_vies/models/__init__.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONFIGURE.rst
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/readme/DESCRIPTION.rst
  base_vat_optional_vies/readme/USAGE.rst
  base_vat_optional_vies/static/description/icon.png
  base_vat_optional_vies/static/description/index.html
  base_vat_optional_vies/tests/__init__.py
  base_vat_optional_vies/tests/test_res_partner.py
  base_vat_optional_vies/views/res_partner_view.xml
  setup/base_vat_optional_vies/odoo/addons/base_vat_optional_vies
  setup/base_vat_optional_vies/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#866 [12.0] [MIG] account_move_batch_validate
  account_move_batch_validate/__init__.py
  account_move_batch_validate/__manifest__.py
  account_move_batch_validate/i18n/am.po
  account_move_batch_validate/i18n/ar.po
  account_move_batch_validate/i18n/bg.po
  account_move_batch_validate/i18n/bs.po
  account_move_batch_validate/i18n/ca.po
  account_move_batch_validate/i18n/ca_ES.po
  account_move_batch_validate/i18n/cs.po
  account_move_batch_validate/i18n/de.po
  account_move_batch_validate/i18n/en_GB.po
  account_move_batch_validate/i18n/es.po
  account_move_batch_validate/i18n/es_CR.po
  account_move_batch_validate/i18n/es_EC.po
  account_move_batch_validate/i18n/es_ES.po
  account_move_batch_validate/i18n/es_MX.po
  account_move_batch_validate/i18n/es_VE.po
  account_move_batch_validate/i18n/et.po
  account_move_batch_validate/i18n/fr.po
  account_move_batch_validate/i18n/gl.po
  account_move_batch_validate/i18n/gl_ES.po
  account_move_batch_validate/i18n/gu.po
  account_move_batch_validate/i18n/hr.po
  account_move_batch_validate/i18n/hr_HR.po
  account_move_batch_validate/i18n/hu.po
  account_move_batch_validate/i18n/id.po
  account_move_batch_validate/i18n/it.po
  account_move_batch_validate/i18n/ja.po
  account_move_batch_validate/i18n/lt.po
  account_move_batch_validate/i18n/mk.po
  account_move_batch_validate/i18n/mn.po
  account_move_batch_validate/i18n/nb.po
  account_move_batch_validate/i18n/nl.po
  account_move_batch_validate/i18n/nl_BE.po
  account_move_batch_validate/i18n/pl.po
  account_move_batch_validate/i18n/pt.po
  account_move_batch_validate/i18n/pt_BR.po
  account_move_batch_validate/i18n/pt_PT.po
  account_move_batch_validate/i18n/ro.po
  account_move_batch_validate/i18n/ru.po
  account_move_batch_validate/i18n/sl.po
  account_move_batch_validate/i18n/sr@latin.po
  account_move_batch_validate/i18n/sv.po
  account_move_batch_validate/i18n/th.po
  account_move_batch_validate/i18n/tr.po
  account_move_batch_validate/i18n/vi.po
  account_move_batch_validate/i18n/zh_CN.po
  account_move_batch_validate/i18n/zh_TW.po
  account_move_batch_validate/models/__init__.py
  account_move_batch_validate/models/account_move.py
  account_move_batch_validate/readme/CONTRIBUTORS.rst
  account_move_batch_validate/readme/DESCRIPTION.rst
  account_move_batch_validate/static/description/icon.png
  account_move_batch_validate/tests/__init__.py
  account_move_batch_validate/tests/test_account_move_batch_validate.py
  account_move_batch_validate/views/account_move.xml
  account_move_batch_validate/wizard/__init__.py
  account_move_batch_validate/wizard/account_move_validate.py
  account_move_batch_validate/wizard/account_move_validate.xml
  oca_dependencies.txt
Labels: approved, merged 🎉, ready to merge

#939 [12.0][account_invoice_constraint_chronology] Add invoice state 'in-payment' to conditions
  account_invoice_constraint_chronology/i18n/account_invoice_constraint_chronology.pot
  account_invoice_constraint_chronology/model/account_invoice.py
Labels: approved, bot is merging ⏳, ready to merge

#1017 [13.0][IMP+FIX] account_asset_management: Add chatter entry in invoice for generated asset, FIX reference empty
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1033 [12.0][FIX] account_spread_cost_revenue: convert total amount to spread currency
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
Labels: approved, bot is merging ⏳
