Repository OCA/account-financial-tools, pull requests merged in 2020-05, with the labels that each got.

#979 [FIX][12.0] account_asset_management: Exception raised when changing asset profile in a move
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#970 [12.0][ENH] account_spreaad_cost_revenue, add optional exp/rev account
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/readme/CONTRIBUTORS.rst
  account_spread_cost_revenue/readme/HISTORY.rst
  account_spread_cost_revenue/readme/USAGE.rst
  account_spread_cost_revenue/views/account_spread.xml
  account_spread_cost_revenue/views/account_spread_template.xml
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.xml
Labels: approved, bot is merging ⏳

#985 [13.0][FIX] Broken pre-commit: E741 ambiguous variable name 'l'
  account_asset_management/models/account_asset.py
Labels: bot is merging ⏳

#942 [13.0][MIG] account_lock_to_date
  account_lock_to_date/README.rst
  account_lock_to_date/__init__.py
  account_lock_to_date/__manifest__.py
  account_lock_to_date/i18n/account_lock_to_date.pot
  account_lock_to_date/models/__init__.py
  account_lock_to_date/models/account_move.py
  account_lock_to_date/models/res_company.py
  account_lock_to_date/readme/CONTRIBUTORS.rst
  account_lock_to_date/readme/DESCRIPTION.rst
  account_lock_to_date/readme/USAGE.rst
  account_lock_to_date/static/description/icon.png
  account_lock_to_date/static/description/index.html
  account_lock_to_date/tests/__init__.py
  account_lock_to_date/tests/test_account_lock_to_date_update.py
  account_lock_to_date/wizards/__init__.py
  account_lock_to_date/wizards/account_update_lock_to_date.py
  account_lock_to_date/wizards/account_update_lock_to_date.xml
Labels: approved, bot is merging ⏳, ready to merge

#969 [12.0] [ADD] Account Clearance Plan
  account_clearance_plan/README.rst
  account_clearance_plan/__init__.py
  account_clearance_plan/__manifest__.py
  account_clearance_plan/models/__init__.py
  account_clearance_plan/models/account_invoice.py
  account_clearance_plan/models/res_company.py
  account_clearance_plan/models/res_config_settings.py
  account_clearance_plan/readme/CONTRIBUTORS.rst
  account_clearance_plan/readme/DESCRIPTION.rst
  account_clearance_plan/readme/ROADMAP.rst
  account_clearance_plan/readme/USAGE.rst
  account_clearance_plan/static/description/icon.png
  account_clearance_plan/static/description/index.html
  account_clearance_plan/tests/__init__.py
  account_clearance_plan/tests/test_account_clearance_plan.py
  account_clearance_plan/views/res_config_settings.xml
  account_clearance_plan/wizard/__init__.py
  account_clearance_plan/wizard/account_clearance_plan.py
  account_clearance_plan/wizard/account_clearance_plan_wizard.xml
  setup/account_clearance_plan/odoo/addons/account_clearance_plan
  setup/account_clearance_plan/setup.py
Labels: approved, bot is merging ⏳, ready to merge
