Repository OCA/account-financial-tools, pull requests merged in 2020-08, with the labels that each got.

#1034 [FIX] account_asset_management:
  account_asset_management/migrations/13.0.1.1.3/post-migration.py
  account_asset_management/security/account_asset_security.xml
Labels: approved, bot is merging ⏳

#993 [12.0][IMP] account_spread_cost_revenue, auto spread on validate invoice
  account_spread_cost_revenue/models/account_invoice.py
  account_spread_cost_revenue/models/account_invoice_line.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/readme/CONFIGURE.rst
  account_spread_cost_revenue/readme/HISTORY.rst
  account_spread_cost_revenue/readme/USAGE.rst
  account_spread_cost_revenue/security/account_spread_security.xml
  account_spread_cost_revenue/security/ir.model.access.csv
  account_spread_cost_revenue/tests/__init__.py
  account_spread_cost_revenue/tests/test_account_invoice_auto_spread.py
  account_spread_cost_revenue/views/account_spread_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#1038 [FIX] account_asset_management - Allow editing salvage value
  account_asset_management/models/account_asset_line.py
  account_asset_management/views/account_asset.xml
Labels: approved, bot is merging ⏳

#952 [13.0][IMP] account_asset_management: Improve code and translation
  account_asset_management/i18n/account_asset.pot
  account_asset_management/i18n/account_asset_management.pot
  account_asset_management/i18n/es.po
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_line.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/views/account_asset.xml
  account_asset_management/views/account_asset_profile.xml
Labels: bot is merging ⏳

#1043 [11.0][FIX] account_asset_management: test
  account_asset_management/tests/test_account_asset_management.py
Labels: approved, bot is merging ⏳

#1047 [9.0][FIX] account_credit_control migration
  .travis.yml
  account_credit_control/migrations/9.0.1.0.0/post-migration.py
Labels: bot is merging ⏳
