Repository OCA/account-financial-tools, pull requests merged in 2020-10, with the labels that each got.

#1053 [13.0][FIX]account_chart_update inactive taxes false positives
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1074 [FIX] travis
  .travis.yml
Labels: approved

#946 [12.0] [MIG] account_asset_batch_compute
  account_asset_batch_compute/__init__.py
  account_asset_batch_compute/__manifest__.py
  account_asset_batch_compute/models/__init__.py
  account_asset_batch_compute/models/account_asset.py
  account_asset_batch_compute/readme/CONTRIBUTORS.rst
  account_asset_batch_compute/readme/DESCRIPTION.rst
  account_asset_batch_compute/static/description/icon.svg
  account_asset_batch_compute/tests/__init__.py
  account_asset_batch_compute/tests/test_account_asset_batch_compute.py
  account_asset_batch_compute/wizards/__init__.py
  account_asset_batch_compute/wizards/account_asset_compute.py
  account_asset_batch_compute/wizards/account_asset_compute_views.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge
