Repository OCA/account-financial-tools, pull requests merged in 2020-04, with the labels that each got.

#823 [12.0][ADD] account_payment_netting
  account_payment_netting/__init__.py
  account_payment_netting/__manifest__.py
  account_payment_netting/models/__init__.py
  account_payment_netting/models/account_invoice.py
  account_payment_netting/models/account_payment.py
  account_payment_netting/readme/CONTRIBUTORS.rst
  account_payment_netting/readme/DESCRIPTION.rst
  account_payment_netting/readme/USAGE.rst
  account_payment_netting/static/description/icon.png
  account_payment_netting/static/description/index.html
  account_payment_netting/tests/__init__.py
  account_payment_netting/tests/test_account_payment_netting.py
  account_payment_netting/views/account_invoice_view.xml
  account_payment_netting/views/account_payment_view.xml
Labels: approved, merged 🎉, ready to merge

#960 [12.0][FIX]account_move_template: fix computed amount
  account_move_template/wizard/account_move_template_run.py
Labels: approved

#961 [13.0][FIX] account_asset_management: Fix tests
  account_asset_management/tests/test_account_asset_management.py
Labels: bot is merging ⏳

#945 [12.0][ADD] account_move_chatter: Chatter on journal entries
  account_move_chatter/README.rst
  account_move_chatter/__init__.py
  account_move_chatter/__manifest__.py
  account_move_chatter/i18n/account_move_chatter.pot
  account_move_chatter/i18n/es.po
  account_move_chatter/models/__init__.py
  account_move_chatter/models/account_move.py
  account_move_chatter/readme/CONFIGURE.rst
  account_move_chatter/readme/CONTRIBUTORS.rst
  account_move_chatter/readme/DESCRIPTION.rst
  account_move_chatter/readme/USAGE.rst
  account_move_chatter/static/description/icon.png
  account_move_chatter/static/description/index.html
  account_move_chatter/views/account_move_views.xml
Labels: approved, bot is merging ⏳, ready to merge

#973 [12.0] [IMP] Depreciation board compute upon asset confirmation
  account_asset_management/models/account_asset.py
Labels: approved, bot is merging ⏳
