Repository OCA/account-financial-tools, pull requests merged in 2021-12, with the labels that each got.

#1168 [12.0][ADD] account_move_line_partner_country: show Partner's Country on AML
  account_move_line_partner_country/__init__.py
  account_move_line_partner_country/__manifest__.py
  account_move_line_partner_country/models/__init__.py
  account_move_line_partner_country/models/account_move_line.py
  account_move_line_partner_country/readme/CONTRIBUTORS.rst
  account_move_line_partner_country/readme/DESCRIPTION.rst
  account_move_line_partner_country/tests/__init__.py
  account_move_line_partner_country/views/account_move_line.xml
Labels: bot is merging ⏳

#1282 [13.0][FIX] account_asset_management: Avoid the error when clicking on "Delete" button if there is a residual value and all the depreciation lines are posted
  account_asset_management/models/account_asset.py
  account_asset_management/tests/test_account_asset_management.py
Labels: approved, bot is merging ⏳

#1292 [13.0][FIX] stock_account_prepare_anglo_saxon_out_lines_hook: update hook
  stock_account_prepare_anglo_saxon_out_lines_hook/hooks.py
Labels: bot is merging ⏳

#1300 [14.0][FIX] greenify repo
  account_check_deposit/tests/test_check_deposit.py
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  base_vat_optional_vies/tests/test_res_partner.py
Labels: approved, bot is merging ⏳

#1296 [14.0][FIX] stock_account_prepare_anglo_saxon_out_lines_hook: update hook
  stock_account_prepare_anglo_saxon_out_lines_hook/hooks.py
Labels: bot is merging ⏳

#1295 [14.0][FIX] account_asset_management: Avoid the error when clicking on "Delete" button if there is a residual value and all the depreciation lines are posted
  account_asset_management/models/account_asset.py
  account_asset_management/tests/test_account_asset_management.py
Labels: bot is merging ⏳

#1299 [14.0][ADD] account_sequence_option
  account_sequence_option/__init__.py
  account_sequence_option/__manifest__.py
  account_sequence_option/data/account_sequence_option.xml
  account_sequence_option/demo/account_demo_options.xml
  account_sequence_option/models/__init__.py
  account_sequence_option/models/account_move.py
  account_sequence_option/models/sequence_option.py
  account_sequence_option/readme/CONTRIBUTORS.rst
  account_sequence_option/readme/DESCRIPTION.rst
  account_sequence_option/static/description/icon.png
  account_sequence_option/tests/__init__.py
  account_sequence_option/tests/test_account_sequence_option.py
  setup/account_sequence_option/odoo/addons/account_sequence_option
  setup/account_sequence_option/setup.py
Labels: bot is merging ⏳

#1290 [14.0][MIG]account_asset_management_menu: Migration to 14.0
  account_asset_management_menu/README.rst
  account_asset_management_menu/__init__.py
  account_asset_management_menu/__manifest__.py
  account_asset_management_menu/i18n/account_asset_management_menu.pot
  account_asset_management_menu/readme/CONFIGURATION.rst
  account_asset_management_menu/readme/CONTRIBUTORS.rst
  account_asset_management_menu/readme/DESCRIPTION.rst
  account_asset_management_menu/static/description/icon.png
  account_asset_management_menu/static/description/index.html
  account_asset_management_menu/views/menuitem.xml
  setup/account_asset_management_menu/odoo/addons/account_asset_management_menu
  setup/account_asset_management_menu/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1305 [15.0][FIX]account_move_line_purchase_info: remove migration script older version
  account_move_line_purchase_info/migrations/14.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳
