Repository OCA/account-financial-tools, pull requests merged in 2021-04, with the labels that each got.

#1149 [12.0][IMP] account_asset_management: Add analytic tags and propagate
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_line.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/models/account_move.py
  account_asset_management/readme/CONTRIBUTORS.rst
  account_asset_management/tests/account_asset_test_data.xml
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/views/account_asset.xml
  account_asset_management/views/account_asset_profile.xml
  account_asset_management/wizard/account_asset_remove.py
Labels: approved, bot is merging ⏳

#1151 [13.0][IMP] account_asset_management: Add analytic tags and propagate
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_line.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/models/account_move.py
  account_asset_management/readme/CONTRIBUTORS.rst
  account_asset_management/tests/account_asset_test_data.xml
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/views/account_asset.xml
  account_asset_management/views/account_asset_profile.xml
  account_asset_management/wizard/account_asset_remove.py
Labels: approved, bot is merging ⏳

#1156 [13.0][account_asset_management]: fix group_assets sorting
  account_asset_management/report/account_asset_report_xls.py
Labels: approved, bot is merging ⏳

#1157 [13.0][account_asset_management]: add user error when creating asset from bill
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1159 [14.0][FIX] account_asset_management: set invoice date
  account_asset_management/tests/test_account_asset_management.py
Labels: approved, bot is merging ⏳

#1158 [14.0][account_asset_management]: add user error when creating asset from bill
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1161 [12.0][FIX] account_asset_management: method_time migration was incomplete
  account_asset_management/migrations/12.0.1.0.0/post-migration.py
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/tests/test_account_asset_management.py
Labels: bot is merging ⏳

#1162 [13.0][FIX] account_asset_management: include 'number' method_time
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/models/account_move.py
  account_asset_management/tests/test_account_asset_management.py
Labels: approved, bot is merging ⏳

#1124 [14.0] account_asset_management: add reporting
  account_asset_management/__init__.py
  account_asset_management/__manifest__.py
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_group.py
  account_asset_management/readme/DESCRIPTION.rst
  account_asset_management/report/__init__.py
  account_asset_management/report/account_asset_report_xls.py
  account_asset_management/security/ir.model.access.csv
  account_asset_management/tests/__init__.py
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/tests/test_asset_management_xls.py
  account_asset_management/views/account_asset.xml
  account_asset_management/wizard/__init__.py
  account_asset_management/wizard/wiz_account_asset_report.py
  account_asset_management/wizard/wiz_account_asset_report.xml
  oca_dependencies.txt
Labels: approved, bot is merging ⏳, ready to merge

#1165 [12.0][FIX] account_asset_management: report on assets without code
  account_asset_management/report/account_asset_report_xls.py
  account_asset_management/tests/test_asset_management_xls.py
Labels: approved, bot is merging ⏳

#1089 [13.0][MIG] account_fiscal_month: Migration to 13.0
  account_fiscal_month/README.rst
  account_fiscal_month/__init__.py
  account_fiscal_month/__manifest__.py
  account_fiscal_month/data/date_range_type.xml
  account_fiscal_month/i18n/account_fiscal_month.pot
  account_fiscal_month/i18n/de.po
  account_fiscal_month/i18n/el_GR.po
  account_fiscal_month/i18n/es.po
  account_fiscal_month/i18n/es_EC.po
  account_fiscal_month/i18n/fi.po
  account_fiscal_month/i18n/fr.po
  account_fiscal_month/i18n/hr.po
  account_fiscal_month/i18n/hr_HR.po
  account_fiscal_month/i18n/it.po
  account_fiscal_month/i18n/lt.po
  account_fiscal_month/i18n/nl.po
  account_fiscal_month/i18n/nl_NL.po
  account_fiscal_month/i18n/pt.po
  account_fiscal_month/i18n/pt_BR.po
  account_fiscal_month/i18n/sk.po
  account_fiscal_month/i18n/sl.po
  account_fiscal_month/i18n/tr.po
  account_fiscal_month/i18n/tr_TR.po
  account_fiscal_month/models/__init__.py
  account_fiscal_month/models/date_range_type.py
  account_fiscal_month/models/res_company.py
  account_fiscal_month/readme/CONTRIBUTORS.rst
  account_fiscal_month/readme/DESCRIPTION.rst
  account_fiscal_month/static/description/icon.png
  account_fiscal_month/static/description/index.html
  account_fiscal_month/tests/__init__.py
  account_fiscal_month/tests/test_account_fiscal_month.py
  account_fiscal_month/views/date_range_type.xml
  setup/account_fiscal_month/odoo/addons/account_fiscal_month
  setup/account_fiscal_month/setup.py
Labels: approved, bot is merging ⏳
