Repository OCA/account-financial-tools, pull requests merged in 2021-08, with the labels that each got.

#1214 [13.0][add][account_move_print]
  account_move_print/__init__.py
  account_move_print/__manifest__.py
  account_move_print/readme/CONTRIBUTORS.rst
  account_move_print/readme/DESCRIPTION.rst
  account_move_print/readme/USAGE.rst
  account_move_print/report/journal_report.xml
  account_move_print/static/description/icon.png
  account_move_print/static/description/index.html
  setup/account_move_print/odoo/addons/account_move_print
  setup/account_move_print/setup.py
Labels: approved, bot is merging ⏳

#1209 [12.0][FIX] account_spread_cost_revenue: disable rights checking auto spread
  account_spread_cost_revenue/models/account_invoice_line.py
Labels: approved, bot is merging ⏳

#1221 [REF] adopting account_menu
  account_menu/__manifest__.py
Labels: bot is merging ⏳

#1224 [14.0][FIX] account_asset_management: make asset company match move's
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1223 [13.0][FIX] account_asset_management: make asset company match move's
  account_asset_management/models/account_move.py
Labels: bot is merging ⏳

#1219 [13.0][IMP] account_move_line_purchase_info optional in tree view
  account_move_line_purchase_info/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1220 [13.0][IMP] account_move_line_sale_info optional fields in tree view
  account_move_line_sale_info/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1187 [14.0.0][MIG] account_template_active
  account_template_active/README.rst
  account_template_active/__init__.py
  account_template_active/__manifest__.py
  account_template_active/i18n/account_template_active.pot
  account_template_active/i18n/fr.po
  account_template_active/models/__init__.py
  account_template_active/models/account_account_template.py
  account_template_active/models/account_fiscal_position_account_template.py
  account_template_active/models/account_fiscal_position_tax_template.py
  account_template_active/models/account_fiscal_position_template.py
  account_template_active/models/account_tax_template.py
  account_template_active/readme/CONTRIBUTORS.rst
  account_template_active/readme/DESCRIPTION.rst
  account_template_active/readme/USAGE.rst
  account_template_active/static/description/account_account_template_tree.png
  account_template_active/static/description/account_fiscal_position_template_form.png
  account_template_active/static/description/account_tax_template_tree.png
  account_template_active/tests/__init__.py
  account_template_active/tests/test_module.py
  account_template_active/views/view_account_account_template.xml
  account_template_active/views/view_account_fiscal_position_template.xml
  account_template_active/views/view_account_tax_template.xml
  setup/account_template_active/odoo/addons/account_template_active
  setup/account_template_active/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1212 [14.0][FIX] account_asset_management
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_group.py
  account_asset_management/models/account_asset_line.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/models/account_move.py
  account_asset_management/readme/HISTORY.rst
  account_asset_management/views/account_asset.xml
  account_asset_management/views/account_move.xml
  account_asset_management/views/account_move_line.xml
  account_asset_management/wizard/account_asset_remove.py
  account_asset_management/wizard/account_asset_remove.xml
Labels: approved, ready to merge, bot is merging ⏳
