Repository OCA/account-financial-tools, pull requests merged in 2021-11, with the labels that each got.

#1260 [14.0][MIG] stock_account_prepare_anglo_saxon_out_lines_hook
  setup/stock_account_prepare_anglo_saxon_out_lines_hook/odoo/addons/stock_account_prepare_anglo_saxon_out_lines_hook
  setup/stock_account_prepare_anglo_saxon_out_lines_hook/setup.py
  stock_account_prepare_anglo_saxon_out_lines_hook/README.rst
  stock_account_prepare_anglo_saxon_out_lines_hook/__init__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/__manifest__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/hooks.py
  stock_account_prepare_anglo_saxon_out_lines_hook/i18n/stock_account_prepare_anglo_saxon_out_lines_hook.pot
  stock_account_prepare_anglo_saxon_out_lines_hook/models/__init__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move.py
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move_line.py
  stock_account_prepare_anglo_saxon_out_lines_hook/static/description/icon.png
Labels: approved, ready to merge, bot is merging ⏳

#1259 [14.0][IMP] account_move_purchase_info: make purchase fields optional in journal entries
  account_move_line_purchase_info/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1269 [14.0][FIX] stock_account_prepare_anglo_saxon_out_lines_hook
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move.py
Labels: approved, bot is merging ⏳

#1261 [14.0][MIG] account_move_line_sale_info
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1251 [13.0][IMP] account_chart_update: refactor update taxes
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
  account_chart_update/wizard/wizard_chart_update_view.xml
Labels: bot is merging ⏳

#1267 [15.0][MIG] account move line sale info to 15
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/readme/CONFIGURE.rst
  account_move_line_sale_info/readme/CONTRIBUTORS.rst
  account_move_line_sale_info/readme/DESCRIPTION.rst
  account_move_line_sale_info/readme/USAGE.rst
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
  setup/account_move_line_sale_info/odoo/addons/account_move_line_sale_info
  setup/account_move_line_sale_info/setup.py
Labels: approved, bot is merging ⏳

#1270 [14.0] account_lock_date_update: add tax_lock_date
  account_lock_date_update/readme/DESCRIPTION.rst
  account_lock_date_update/readme/USAGE.rst
  account_lock_date_update/tests/test_account_lock_date_update.py
  account_lock_date_update/wizards/account_update_lock_date.py
  account_lock_date_update/wizards/account_update_lock_date.xml
Labels: bot is merging ⏳

#737 [11.0][ADD] account_spread_contract
  account_spread_contract/README.rst
  account_spread_contract/__init__.py
  account_spread_contract/__manifest__.py
  account_spread_contract/i18n/nl.po
  account_spread_contract/models/__init__.py
  account_spread_contract/models/account_analytic_account.py
  account_spread_contract/models/account_analytic_invoice_line.py
  account_spread_contract/models/account_spread_template.py
  account_spread_contract/readme/CONFIGURE.rst
  account_spread_contract/readme/CONTRIBUTORS.rst
  account_spread_contract/readme/DESCRIPTION.rst
  account_spread_contract/readme/HISTORY.rst
  account_spread_contract/readme/USAGE.rst
  account_spread_contract/static/description/index.html
  account_spread_contract/tests/__init__.py
  account_spread_contract/tests/test_account_spread_contract.py
  account_spread_contract/views/account_analytic_account.xml
  account_spread_contract/views/account_spread_template.xml
  account_spread_contract/wizards/__init__.py
  account_spread_contract/wizards/account_spread_contract_line_link_wizard.py
  account_spread_contract/wizards/account_spread_contract_line_link_wizard.xml
  oca_dependencies.txt
Labels: approved, ready to merge

#1266 [12.0][FIX] account_asset_management: Avoid the error when clicking on "Delete" button if there is a residual value and all the depreciation lines are posted.
  account_asset_management/models/account_asset.py
  account_asset_management/tests/test_account_asset_management.py
Labels: approved, ready to merge, bot is merging ⏳
