Repository OCA/account-financial-tools, pull requests merged in 2021-06, with the labels that each got.

#1195 [13.0][IMP]account_move_template: Archive account move templates
  account_move_template/models/account_move_template.py
  account_move_template/readme/CONTRIBUTORS.rst
  account_move_template/view/account_move_template.xml
Labels: approved, bot is merging ⏳

#1196 [14.0][IMP]account_move_template: Archive account move templates
  account_move_template/models/account_move_template.py
  account_move_template/readme/CONTRIBUTORS.rst
  account_move_template/view/account_move_template.xml
Labels: bot is merging ⏳

#1173 [13.0][ADD] account_move_line_sale_info
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/migrations/13.0.1.0.0/pre-migration.py
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
  oca_dependencies.txt
  stock_account_prepare_anglo_saxon_out_lines_hook/README.rst
  stock_account_prepare_anglo_saxon_out_lines_hook/__init__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/__manifest__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/hooks.py
  stock_account_prepare_anglo_saxon_out_lines_hook/models/__init__.py
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move.py
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move_line.py
  stock_account_prepare_anglo_saxon_out_lines_hook/static/description/icon.png
Labels: approved, bot is merging ⏳, ready to merge

#1199 [13.0][account_asset_management][imp] Carry forward depreciations from closed periods
  account_asset_management/models/account_asset.py
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/views/account_asset.xml
Labels: approved, bot is merging ⏳, ready to merge

#1201 [13.0][FIX][account_asset_management]: fix asset count compute
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳
