Repository OCA/account-financial-tools, pull requests merged in 2021-05, with the labels that each got.

#1140 [MIG] account_move_line_tax_editable: Migration to 14.0
  account_move_line_tax_editable/README.rst
  account_move_line_tax_editable/__init__.py
  account_move_line_tax_editable/__manifest__.py
  account_move_line_tax_editable/i18n/account_move_line_tax_editable.pot
  account_move_line_tax_editable/i18n/de.po
  account_move_line_tax_editable/i18n/es_EC.po
  account_move_line_tax_editable/i18n/fr.po
  account_move_line_tax_editable/i18n/hr.po
  account_move_line_tax_editable/i18n/pt.po
  account_move_line_tax_editable/i18n/tr_TR.po
  account_move_line_tax_editable/models/__init__.py
  account_move_line_tax_editable/models/account_move_line.py
  account_move_line_tax_editable/readme/CONTRIBUTORS.rst
  account_move_line_tax_editable/readme/DESCRIPTION.rst
  account_move_line_tax_editable/static/description/icon.png
  account_move_line_tax_editable/static/description/index.html
  account_move_line_tax_editable/tests/__init__.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
  account_move_line_tax_editable/views/account_move.xml
  account_move_line_tax_editable/views/account_move_line.xml
  setup/account_move_line_tax_editable/odoo/addons/account_move_line_tax_editable
  setup/account_move_line_tax_editable/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1172 [14.0][FIX] account_asset_management: Fix error from group_ids in asset when set profile_id + Fix _name_search
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_group.py
  account_asset_management/tests/test_account_asset_management.py
Labels: approved, bot is merging ⏳

#1170 [13.0][FIX] account_asset_management: Fix error from group_ids in asset when set profile_id
  account_asset_management/models/account_asset.py
Labels: approved, bot is merging ⏳

#1167 [14.0][MIG] account_move_force_removal module
  account_move_force_removal/README.rst
  account_move_force_removal/__init__.py
  account_move_force_removal/__manifest__.py
  account_move_force_removal/i18n/account_move_force_removal.pot
  account_move_force_removal/models/__init__.py
  account_move_force_removal/models/account_move.py
  account_move_force_removal/readme/CONTRIBUTORS.rst
  account_move_force_removal/readme/DESCRIPTION.rst
  account_move_force_removal/readme/USAGE.rst
  account_move_force_removal/static/description/icon.png
  account_move_force_removal/static/description/index.html
  account_move_force_removal/tests/__init__.py
  account_move_force_removal/tests/test_move.py
  setup/account_move_force_removal/odoo/addons/account_move_force_removal
  setup/account_move_force_removal/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1175 [13.0][FIX]account_asset_management: use column_invisible
  account_asset_management/views/account_move.xml
Labels: approved, bot is merging ⏳

#1176 [13.0][IMP]account_asset_management: add optional attribute for asset related columns in invoice lines
  account_asset_management/views/account_move.xml
Labels: approved, bot is merging ⏳

#1177 [14.0][account_asset_management]: forwardport column fixes
  account_asset_management/views/account_move.xml
Labels: approved, bot is merging ⏳

#1178 [13.0][add][account_move_line_used_currency]
  account_move_line_used_currency/__init__.py
  account_move_line_used_currency/__manifest__.py
  account_move_line_used_currency/init_hooks.py
  account_move_line_used_currency/models/__init__.py
  account_move_line_used_currency/models/account_move_line.py
  account_move_line_used_currency/readme/CONTRIBUTORS.rst
  account_move_line_used_currency/readme/DESCRIPTION.rst
  account_move_line_used_currency/tests/__init__.py
  account_move_line_used_currency/tests/test_account_move_line_used_currency.py
  account_move_line_used_currency/views/account_move_line_view.xml
  account_move_line_used_currency/views/account_move_view.xml
  setup/account_move_line_used_currency/odoo/addons/account_move_line_used_currency
  setup/account_move_line_used_currency/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1163 [14.0][FIX] account_asset_management: several forward ports
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_line.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/models/account_move.py
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/views/account_asset.xml
  account_asset_management/views/account_asset_profile.xml
  account_asset_management/wizard/account_asset_remove.py
Labels: approved, bot is merging ⏳, ready to merge

#1137 [11.0][FIX] account_asset_management: test
  account_asset_management/tests/test_account_asset_management.py
Labels: bot is merging ⏳

#1181 [12.0][IMP] - account_asset_management : use a method to get assets to compute for better inheritance
  account_asset_management/wizard/account_asset_compute.py
Labels: approved, bot is merging ⏳

#978 [ADD][12.0] account_template_active
  account_template_active/README.rst
  account_template_active/__init__.py
  account_template_active/__manifest__.py
  account_template_active/i18n/account_template_active.pot
  account_template_active/i18n/fr.po
  account_template_active/models/__init__.py
  account_template_active/models/account_account_template.py
  account_template_active/models/account_fiscal_position_account_template.py
  account_template_active/models/account_fiscal_position_tax_template.py
  account_template_active/models/account_fiscal_position_template.py
  account_template_active/models/account_tax_template.py
  account_template_active/readme/CONTRIBUTORS.rst
  account_template_active/readme/DESCRIPTION.rst
  account_template_active/readme/USAGE.rst
  account_template_active/static/description/account_account_template_tree.png
  account_template_active/static/description/account_fiscal_position_template_form.png
  account_template_active/static/description/account_tax_template_tree.png
  account_template_active/tests/__init__.py
  account_template_active/tests/test_module.py
  account_template_active/views/view_account_account_template.xml
  account_template_active/views/view_account_fiscal_position_template.xml
  account_template_active/views/view_account_tax_template.xml
Labels: approved, bot is merging ⏳, ready to merge

#1188 [FIX] account_chart_update: issue with xmlid
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳, ready to merge

#1190 [FIX] account_asset_management: Use API functions for date handling
  account_asset_management/models/account_fiscal_year.py
Labels: approved, bot is merging ⏳
