Repository OCA/account-financial-tools, pull requests merged in 2021-09, with the labels that each got.

#1229 [13.0][FIX] account_asset_management: fix _check_dates
  account_asset_management/models/account_asset.py
Labels: approved, bot is merging ⏳

#1227 [13.0][ADD] account_maturity_date_default: This addon set default due date in journal items
  account_maturity_date_default/README.rst
  account_maturity_date_default/__init__.py
  account_maturity_date_default/__manifest__.py
  account_maturity_date_default/i18n/account_maturity_date_default.pot
  account_maturity_date_default/models/__init__.py
  account_maturity_date_default/models/account_move_line.py
  account_maturity_date_default/readme/CONTRIBUTORS.rst
  account_maturity_date_default/readme/DESCRIPTION.rst
  account_maturity_date_default/static/description/icon.png
  account_maturity_date_default/static/description/index.html
  account_maturity_date_default/tests/__init__.py
  account_maturity_date_default/tests/test_account_move.py
  setup/account_maturity_date_default/odoo/addons/account_maturity_date_default
  setup/account_maturity_date_default/setup.py
Labels: approved, bot is merging ⏳

#1197 [12.0][ADD] account_move_line_drilldown
  account_move_line_drilldown/README.rst
  account_move_line_drilldown/__init__.py
  account_move_line_drilldown/__manifest__.py
  account_move_line_drilldown/hooks.py
  account_move_line_drilldown/models/__init__.py
  account_move_line_drilldown/models/account_account.py
  account_move_line_drilldown/models/account_group.py
  account_move_line_drilldown/models/account_move_line.py
  account_move_line_drilldown/readme/CONFIGURE.rst
  account_move_line_drilldown/readme/CONTRIBUTORS.readme
  account_move_line_drilldown/readme/DESCRIPTION.rst
  account_move_line_drilldown/readme/INSTALL.rst
  account_move_line_drilldown/readme/USAGE.rst
  account_move_line_drilldown/static/description/drilldown_pivot.png
  account_move_line_drilldown/static/description/drilldown_tree.png
  account_move_line_drilldown/static/description/index.html
  account_move_line_drilldown/tests/__init__.py
  account_move_line_drilldown/tests/test_account_move_line_drilldown.py
  account_move_line_drilldown/views/account_move_line_view.xml
Labels: work in progress, approved, ready to merge, bot is merging ⏳

#1239 [14.0][IMP] account_asset_management: hook for asset vals
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1235 [13.0][IMP] account_maturity_date_default: Define the maturity date of the entries when updating the journal entry date.
  account_maturity_date_default/models/__init__.py
  account_maturity_date_default/models/account_move.py
  account_maturity_date_default/tests/test_account_move.py
Labels: approved, bot is merging ⏳

#1233 [14.0][FIX] account_asset_management, fix multi currency problem.
  account_asset_management/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1230 [14.0][FIX] account_asset_management, error on remove for asset no depre
  account_asset_management/models/account_move.py
  account_asset_management/wizard/account_asset_remove.py
Labels: approved, bot is merging ⏳
