Repository OCA/account-financial-tools, pull requests merged in 2021-01, with the labels that each got.

#1107 [FIX] Freeze numpy version to 1.19.4
  requirements.txt
Labels: approved

#1105 [14.0][MIG] account_balance_line: Migration to 14.0
  account_balance_line/README.rst
  account_balance_line/__init__.py
  account_balance_line/__manifest__.py
  account_balance_line/i18n/account_balance_line.pot
  account_balance_line/i18n/ar.po
  account_balance_line/i18n/bs.po
  account_balance_line/i18n/ca.po
  account_balance_line/i18n/cs.po
  account_balance_line/i18n/de.po
  account_balance_line/i18n/en_GB.po
  account_balance_line/i18n/es.po
  account_balance_line/i18n/es_CR.po
  account_balance_line/i18n/es_EC.po
  account_balance_line/i18n/es_MX.po
  account_balance_line/i18n/fr.po
  account_balance_line/i18n/gl.po
  account_balance_line/i18n/hr.po
  account_balance_line/i18n/hr_HR.po
  account_balance_line/i18n/hu.po
  account_balance_line/i18n/it.po
  account_balance_line/i18n/ja.po
  account_balance_line/i18n/lt.po
  account_balance_line/i18n/mk.po
  account_balance_line/i18n/mn.po
  account_balance_line/i18n/nb.po
  account_balance_line/i18n/nb_NO.po
  account_balance_line/i18n/nl.po
  account_balance_line/i18n/nl_BE.po
  account_balance_line/i18n/pt.po
  account_balance_line/i18n/pt_BR.po
  account_balance_line/i18n/pt_PT.po
  account_balance_line/i18n/ro.po
  account_balance_line/i18n/ru.po
  account_balance_line/i18n/sl.po
  account_balance_line/i18n/sv.po
  account_balance_line/i18n/tr.po
  account_balance_line/i18n/zh_CN.po
  account_balance_line/i18n/zh_TW.po
  account_balance_line/readme/CONTRIBUTORS.rst
  account_balance_line/readme/DESCRIPTION.rst
  account_balance_line/readme/USAGE.rst
  account_balance_line/static/description/icon.png
  account_balance_line/static/description/index.html
  account_balance_line/views/account_move_line_view.xml
  setup/account_balance_line/odoo/addons/account_balance_line
  setup/account_balance_line/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1110 [14.0] [NEW] account_no_default: Module to set default_account_id as non-required.
  account_no_default/README.rst
  account_no_default/__init__.py
  account_no_default/__manifest__.py
  account_no_default/readme/CONTRIBUTORS.rst
  account_no_default/readme/DESCRIPTION.rst
  account_no_default/views/account_journal_views.xml
  setup/account_no_default/odoo/addons/account_no_default
  setup/account_no_default/setup.py
Labels: approved, bot is merging ⏳, ready to merge

#1109 [13.0]fix account_check_deposit multi-company record rule
  account_check_deposit/security/check_deposit_security.xml
Labels: approved, bot is merging ⏳, ready to merge

#1091 [13.0][ADD]product_category_tax
  product_category_tax/README.rst
  product_category_tax/__init__.py
  product_category_tax/__manifest__.py
  product_category_tax/models/__init__.py
  product_category_tax/models/product_category.py
  product_category_tax/models/product_template.py
  product_category_tax/readme/CONFIGURATION.rst
  product_category_tax/readme/CONTRIBUTORS.rst
  product_category_tax/readme/DESCRIPTION.rst
  product_category_tax/readme/USAGE.rst
  product_category_tax/static/description/icon.png
  product_category_tax/static/description/index.html
  product_category_tax/tests/__init__.py
  product_category_tax/tests/test_product_category_tax.py
  product_category_tax/views/product_category.xml
  product_category_tax/views/product_template.xml
Labels: approved, bot is merging ⏳

#1100 [13.0] [FIX] account lock to date crash fix
  account_lock_to_date/models/account_move.py
  account_lock_to_date/models/res_company.py
  account_lock_to_date/tests/test_account_lock_to_date_update.py
  account_lock_to_date/wizards/account_update_lock_to_date.py
Labels: approved, bot is merging ⏳, ready to merge

#1081 [14.0][MIG] account_fiscal_year
  account_fiscal_year/__init__.py
  account_fiscal_year/__manifest__.py
  account_fiscal_year/i18n/it.po
  account_fiscal_year/models/__init__.py
  account_fiscal_year/models/account_fiscal_year.py
  account_fiscal_year/models/res_company.py
  account_fiscal_year/readme/CONTRIBUTORS.rst
  account_fiscal_year/readme/DESCRIPTION.rst
  account_fiscal_year/readme/ROADMAP.rst
  account_fiscal_year/security/ir.model.access.csv
  account_fiscal_year/static/description/icon.png
  account_fiscal_year/static/description/index.html
  account_fiscal_year/tests/__init__.py
  account_fiscal_year/tests/test_account_fiscal_year.py
  account_fiscal_year/views/account_fiscal_year_views.xml
  setup/account_fiscal_year/odoo/addons/account_fiscal_year
  setup/account_fiscal_year/setup.py
Labels: approved, bot is merging ⏳, ready to merge
