Repository OCA/account-financial-tools, pull requests merged in 2022-12, with the labels that each got.

#1515 [FW][15.0][FIX] account_move_name_sequence: call flush before to post the moves
  account_move_name_sequence/models/account_move.py
Labels: bot is merging ⏳

#1514 [14.0][FIX] account_move_name_sequence: call flush before to post the moves
  account_move_name_sequence/models/account_move.py
Labels: bot is merging ⏳

#1502 [14.0][FIX] account_asset_management: Poor performance updating assets massively
  account_asset_management/models/account_asset_line.py
  account_asset_management/readme/CONTRIBUTORS.rst
Labels: approved, ready to merge, bot is merging ⏳

#1523 [15.0][FIX] account_asset_management: Poor performance updating assets massively
  account_asset_management/models/account_asset_line.py
Labels: bot is merging ⏳

#1521 [15.0][FIX] account_move_name_sequence: issue #1465
  account_move_name_sequence/models/account_journal.py
Labels: bot is merging ⏳

#1520 [14.0][FIX] account_move_name_sequence: issue #1465
  account_move_name_sequence/models/account_journal.py
Labels: bot is merging ⏳

#1477 [16.0][MIG] account_usability
  account_usability/README.rst
  account_usability/__init__.py
  account_usability/__manifest__.py
  account_usability/data/ir_module_category.xml
  account_usability/demo/res_groups.xml
  account_usability/i18n/account_usability.pot
  account_usability/i18n/es.po
  account_usability/i18n/fr.po
  account_usability/i18n/nl.po
  account_usability/i18n/pt.po
  account_usability/models/__init__.py
  account_usability/models/account_group.py
  account_usability/models/account_tag.py
  account_usability/models/account_tax_group.py
  account_usability/models/res_config_settings.py
  account_usability/readme/CONFIGURE.rst
  account_usability/readme/CONTRIBUTORS.rst
  account_usability/readme/DESCRIPTION.rst
  account_usability/readme/ROADMAP.rst
  account_usability/security/res_groups.xml
  account_usability/static/description/icon.png
  account_usability/static/description/index.html
  account_usability/views/menu.xml
  account_usability/views/res_config_settings_views.xml
  account_usability/views/view_account_account_template.xml
  account_usability/views/view_account_bank_statement.xml
  account_usability/views/view_account_chart_template.xml
  account_usability/views/view_account_fiscal_position_template.xml
  account_usability/views/view_account_group.xml
  account_usability/views/view_account_tag.xml
  account_usability/views/view_account_tax_template.xml
  setup/account_usability/odoo/addons/account_usability
  setup/account_usability/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1510 [16.0][MIG] account_move_name_sequence: Migration to 16.0
  account_move_name_sequence/README.rst
  account_move_name_sequence/__init__.py
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/i18n/account_move_name_sequence.pot
  account_move_name_sequence/models/__init__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/post_install.py
  account_move_name_sequence/readme/CONFIGURE.rst
  account_move_name_sequence/readme/CONTRIBUTORS.rst
  account_move_name_sequence/readme/DESCRIPTION.rst
  account_move_name_sequence/security/ir.model.access.csv
  account_move_name_sequence/static/description/icon.png
  account_move_name_sequence/static/description/index.html
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
  account_move_name_sequence/views/account_journal.xml
  account_move_name_sequence/views/account_move.xml
  setup/account_move_name_sequence/odoo/addons/account_move_name_sequence
  setup/account_move_name_sequence/setup.py
Labels: needs review, approved, bot is merging ⏳

#1527 [REF] account_move_name_sequence: Remove concurrency outdated cases from the readme
  account_move_name_sequence/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#1400 [14.0] account_cash_deposit: add support for loose coins in deposits
  account_cash_deposit/models/account_cash_deposit.py
  account_cash_deposit/tests/test_cash_deposit.py
  account_cash_deposit/views/account_cash_deposit.xml
Labels: bot is merging ⏳

#1495 [15.0][ADD] account_move_total_by_account_internal_group
  account_move_total_by_account_internal_group/README.rst
  account_move_total_by_account_internal_group/__init__.py
  account_move_total_by_account_internal_group/__manifest__.py
  account_move_total_by_account_internal_group/hooks.py
  account_move_total_by_account_internal_group/models/__init__.py
  account_move_total_by_account_internal_group/models/account_move.py
  account_move_total_by_account_internal_group/models/account_move_line.py
  account_move_total_by_account_internal_group/readme/CONTRIBUTORS.rst
  account_move_total_by_account_internal_group/readme/DESCRIPTION.rst
  account_move_total_by_account_internal_group/readme/USAGE.rst
  account_move_total_by_account_internal_group/static/description/icon.png
  account_move_total_by_account_internal_group/static/description/index.html
  account_move_total_by_account_internal_group/tests/__init__.py
  account_move_total_by_account_internal_group/tests/test_account_move_totals_by_account_internal_group.py
  account_move_total_by_account_internal_group/views/account_move_views.xml
  setup/account_move_total_by_account_internal_group/odoo/addons/account_move_total_by_account_internal_group
  setup/account_move_total_by_account_internal_group/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1533 [FIX] account_journal_general_sequence: let non-admin accounting managers renumber moves
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
Labels: bot is merging ⏳

#1516 [13.0][FIX] account_move_line_sale_info: add the sale line information to credit notes
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
Labels: approved, ready to merge, bot is merging ⏳

#1517 [14.0][FIX] account_move_line_sale_info: add the sale line information to credit notes
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
Labels: approved, ready to merge, bot is merging ⏳

#1351 [13.0][IMP] account_document_reversal: date for new account move.
  account_document_reversal/models/account_move.py
  account_document_reversal/models/account_payment.py
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1535 [14.0][IMP] account_chart_update: improve extensibility
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1536 [MIG] account_journal_general_sequence: v16 modifications
  account_journal_general_sequence/README.rst
  account_journal_general_sequence/__init__.py
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/i18n/account_journal_general_sequence.pot
  account_journal_general_sequence/i18n/es.po
  account_journal_general_sequence/models/__init__.py
  account_journal_general_sequence/models/account_journal.py
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/models/account_move_line.py
  account_journal_general_sequence/readme/CONFIGURE.rst
  account_journal_general_sequence/readme/CONTRIBUTORS.rst
  account_journal_general_sequence/readme/DESCRIPTION.rst
  account_journal_general_sequence/readme/INSTALL.rst
  account_journal_general_sequence/readme/USAGE.rst
  account_journal_general_sequence/security/ir.model.access.csv
  account_journal_general_sequence/static/description/icon.png
  account_journal_general_sequence/static/description/index.html
  account_journal_general_sequence/tests/__init__.py
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/views/account_journal.xml
  account_journal_general_sequence/views/account_move.xml
  account_journal_general_sequence/views/account_move_line.xml
  account_journal_general_sequence/wizards/__init__.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard_views.xml
  requirements.txt
  setup/account_journal_general_sequence/odoo/addons/account_journal_general_sequence
  setup/account_journal_general_sequence/setup.py
Labels: bot is merging ⏳
