Repository OCA/account-financial-tools, pull requests merged in 2022-04, with the labels that each got.

#1288 [15.0][MIG] account_balance_line
  account_balance_line/README.rst
  account_balance_line/__init__.py
  account_balance_line/__manifest__.py
  account_balance_line/i18n/account_balance_line.pot
  account_balance_line/i18n/ar.po
  account_balance_line/i18n/bs.po
  account_balance_line/i18n/ca.po
  account_balance_line/i18n/cs.po
  account_balance_line/i18n/de.po
  account_balance_line/i18n/en_GB.po
  account_balance_line/i18n/es.po
  account_balance_line/i18n/es_CR.po
  account_balance_line/i18n/es_EC.po
  account_balance_line/i18n/es_MX.po
  account_balance_line/i18n/fr.po
  account_balance_line/i18n/fr_FR.po
  account_balance_line/i18n/gl.po
  account_balance_line/i18n/hr.po
  account_balance_line/i18n/hr_HR.po
  account_balance_line/i18n/hu.po
  account_balance_line/i18n/it.po
  account_balance_line/i18n/ja.po
  account_balance_line/i18n/lt.po
  account_balance_line/i18n/mk.po
  account_balance_line/i18n/mn.po
  account_balance_line/i18n/nb.po
  account_balance_line/i18n/nb_NO.po
  account_balance_line/i18n/nl.po
  account_balance_line/i18n/nl_BE.po
  account_balance_line/i18n/pt.po
  account_balance_line/i18n/pt_BR.po
  account_balance_line/i18n/pt_PT.po
  account_balance_line/i18n/ro.po
  account_balance_line/i18n/ru.po
  account_balance_line/i18n/sl.po
  account_balance_line/i18n/sv.po
  account_balance_line/i18n/tr.po
  account_balance_line/i18n/zh_CN.po
  account_balance_line/i18n/zh_TW.po
  account_balance_line/readme/CONTRIBUTORS.rst
  account_balance_line/readme/DESCRIPTION.rst
  account_balance_line/readme/USAGE.rst
  account_balance_line/static/description/icon.png
  account_balance_line/static/description/index.html
  account_balance_line/views/account_move_line_view.xml
  setup/account_balance_line/odoo/addons/account_balance_line
  setup/account_balance_line/setup.py
Labels: approved, bot is merging ⏳

#1294 [15.0][MIG] account_move_line_menu
  account_move_line_menu/README.rst
  account_move_line_menu/__init__.py
  account_move_line_menu/__manifest__.py
  account_move_line_menu/i18n/account_move_line_menu.pot
  account_move_line_menu/i18n/fr.po
  account_move_line_menu/i18n/fr_FR.po
  account_move_line_menu/readme/CONTRIBUTORS.rst
  account_move_line_menu/readme/DESCRIPTION.rst
  account_move_line_menu/readme/USAGE.rst
  account_move_line_menu/static/description/icon.png
  account_move_line_menu/static/description/index.html
  account_move_line_menu/views/account_menu_views.xml
  setup/account_move_line_menu/odoo/addons/account_move_line_menu
  setup/account_move_line_menu/setup.py
Labels: approved, bot is merging ⏳

#1275 [15.0][MIG] account_menu: migrate module from 14.0 to 15.0
  account_usability/README.rst
  account_usability/__init__.py
  account_usability/__manifest__.py
  account_usability/demo/res_groups.xml
  account_usability/i18n/account_usability.pot
  account_usability/i18n/fr.po
  account_usability/i18n/fr_FR.po
  account_usability/i18n/nl.po
  account_usability/i18n/pt.po
  account_usability/models/__init__.py
  account_usability/models/account_group.py
  account_usability/models/account_tag.py
  account_usability/models/account_tax_group.py
  account_usability/models/res_config_settings.py
  account_usability/readme/CONFIGURE.rst
  account_usability/readme/CONTRIBUTORS.rst
  account_usability/readme/DESCRIPTION.rst
  account_usability/readme/ROADMAP.rst
  account_usability/static/description/icon.png
  account_usability/static/description/index.html
  account_usability/views/menu.xml
  account_usability/views/res_config_settings_views.xml
  account_usability/views/view_account_account_template.xml
  account_usability/views/view_account_bank_statement.xml
  account_usability/views/view_account_chart_template.xml
  account_usability/views/view_account_fiscal_position_template.xml
  account_usability/views/view_account_group.xml
  account_usability/views/view_account_tag.xml
  account_usability/views/view_account_tax_group.xml
  account_usability/views/view_account_tax_template.xml
  account_usability/views/view_account_type.xml
  setup/account_usability/odoo/addons/account_usability
  setup/account_usability/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1370 [14.0][IMP] account_asset_management: prevent from creating assets from tax lines
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1263 [14.0][MIG] account move fiscal year
  account_move_fiscal_year/README.rst
  account_move_fiscal_year/__init__.py
  account_move_fiscal_year/__manifest__.py
  account_move_fiscal_year/i18n/account_move_fiscal_year.pot
  account_move_fiscal_year/i18n/am.po
  account_move_fiscal_year/i18n/ar.po
  account_move_fiscal_year/i18n/ca.po
  account_move_fiscal_year/i18n/de.po
  account_move_fiscal_year/i18n/es.po
  account_move_fiscal_year/i18n/es_CO.po
  account_move_fiscal_year/i18n/es_EC.po
  account_move_fiscal_year/i18n/fr.po
  account_move_fiscal_year/i18n/fr_FR.po
  account_move_fiscal_year/i18n/gl.po
  account_move_fiscal_year/i18n/hr.po
  account_move_fiscal_year/i18n/hr_HR.po
  account_move_fiscal_year/i18n/it.po
  account_move_fiscal_year/i18n/nl.po
  account_move_fiscal_year/i18n/pt.po
  account_move_fiscal_year/i18n/pt_BR.po
  account_move_fiscal_year/i18n/pt_PT.po
  account_move_fiscal_year/i18n/sl.po
  account_move_fiscal_year/i18n/tr_TR.po
  account_move_fiscal_year/models/__init__.py
  account_move_fiscal_year/models/account_move.py
  account_move_fiscal_year/models/account_move_line.py
  account_move_fiscal_year/models/res_company.py
  account_move_fiscal_year/readme/CONFIGURE.rst
  account_move_fiscal_year/readme/CONTRIBUTORS.rst
  account_move_fiscal_year/readme/DESCRIPTION.rst
  account_move_fiscal_year/readme/INSTALL.rst
  account_move_fiscal_year/readme/USAGE.rst
  account_move_fiscal_year/static/description/icon.png
  account_move_fiscal_year/static/description/index.html
  account_move_fiscal_year/tests/__init__.py
  account_move_fiscal_year/tests/test_account_move_fiscal_year.py
  account_move_fiscal_year/views/account_move.xml
  account_move_fiscal_year/views/account_move_line.xml
  setup/account_move_fiscal_year/odoo/addons/account_move_fiscal_year
  setup/account_move_fiscal_year/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1243 [14.0][MIG] account_move_fiscal_month
  account_move_fiscal_month/README.rst
  account_move_fiscal_month/__init__.py
  account_move_fiscal_month/__manifest__.py
  account_move_fiscal_month/i18n/account_move_fiscal_month.pot
  account_move_fiscal_month/i18n/am.po
  account_move_fiscal_month/i18n/ca.po
  account_move_fiscal_month/i18n/de.po
  account_move_fiscal_month/i18n/es.po
  account_move_fiscal_month/i18n/es_EC.po
  account_move_fiscal_month/i18n/fr.po
  account_move_fiscal_month/i18n/gl.po
  account_move_fiscal_month/i18n/hr.po
  account_move_fiscal_month/i18n/hr_HR.po
  account_move_fiscal_month/i18n/it.po
  account_move_fiscal_month/i18n/nl.po
  account_move_fiscal_month/i18n/pt.po
  account_move_fiscal_month/i18n/pt_BR.po
  account_move_fiscal_month/i18n/pt_PT.po
  account_move_fiscal_month/i18n/sl.po
  account_move_fiscal_month/i18n/tr_TR.po
  account_move_fiscal_month/models/__init__.py
  account_move_fiscal_month/models/account_move.py
  account_move_fiscal_month/models/account_move_line.py
  account_move_fiscal_month/readme/CONFIGURE.rst
  account_move_fiscal_month/readme/CONTRIBUTORS.rst
  account_move_fiscal_month/readme/DESCRIPTION.rst
  account_move_fiscal_month/static/description/icon.png
  account_move_fiscal_month/static/description/index.html
  account_move_fiscal_month/tests/__init__.py
  account_move_fiscal_month/tests/test_account_move_fiscal_month.py
  account_move_fiscal_month/views/account_move.xml
  account_move_fiscal_month/views/account_move_line.xml
  setup/account_move_fiscal_month/odoo/addons/account_move_fiscal_month
  setup/account_move_fiscal_month/setup.py
  test-requirements.txt
Labels: approved, ready to merge, bot is merging ⏳

#1378 [14.0][FIX] account_asset_management + account_asset_transfer + account_journal_lock_date: Add post_install tag in tests to prevent test errors
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/tests/test_asset_management_xls.py
  account_asset_transfer/tests/test_account_asset_transfer.py
  account_journal_lock_date/tests/test_journal_lock_date.py
Labels: bot is merging ⏳

#1323 [14.0][FIX] account_asset_management: calculate day mistake, remove asset
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/wizard/account_asset_remove.py
Labels: approved, ready to merge, bot is merging ⏳

#1265 [14.0][FIX] account fiscal year fix
  account_fiscal_year/__manifest__.py
  account_fiscal_year/data/date_range_type.xml
  account_fiscal_year/security/ir.model.access.csv
Labels: needs fixing, approved, ready to merge, bot is merging ⏳

#1380 [15.0] [MIG] account_move_force_removal: Migration to 15.0
  account_move_force_removal/README.rst
  account_move_force_removal/__init__.py
  account_move_force_removal/__manifest__.py
  account_move_force_removal/i18n/account_move_force_removal.pot
  account_move_force_removal/models/__init__.py
  account_move_force_removal/models/account_move.py
  account_move_force_removal/readme/CONTRIBUTORS.rst
  account_move_force_removal/readme/DESCRIPTION.rst
  account_move_force_removal/readme/USAGE.rst
  account_move_force_removal/static/description/icon.png
  account_move_force_removal/static/description/index.html
  account_move_force_removal/tests/__init__.py
  account_move_force_removal/tests/test_move.py
  setup/account_move_force_removal/odoo/addons/account_move_force_removal
  setup/account_move_force_removal/setup.py
Labels: approved, bot is merging ⏳
