Repository OCA/account-financial-tools, pull requests merged in 2022-10, with the labels that each got.

#1304 [14.0][ADD] account_reconcile_show_boolean
  account_reconcile_show_boolean/README.rst
  account_reconcile_show_boolean/__init__.py
  account_reconcile_show_boolean/__manifest__.py
  account_reconcile_show_boolean/readme/CONTRIBUTORS.rst
  account_reconcile_show_boolean/readme/DESCRIPTION.rst
  account_reconcile_show_boolean/readme/USAGE.rst
  account_reconcile_show_boolean/static/description/icon.png
  account_reconcile_show_boolean/static/description/icon.svg
  account_reconcile_show_boolean/views/account_account_view.xml
  setup/account_reconcile_show_boolean/odoo/addons/account_reconcile_show_boolean
  setup/account_reconcile_show_boolean/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1425 [15.0][MIG] account_move_budget: Migrate to version 15.0
  account_move_budget/README.rst
  account_move_budget/__init__.py
  account_move_budget/__manifest__.py
  account_move_budget/i18n/account_move_budget.pot
  account_move_budget/i18n/fr.po
  account_move_budget/models/__init__.py
  account_move_budget/models/account_move_budget.py
  account_move_budget/models/account_move_budget_line.py
  account_move_budget/readme/CONTRIBUTORS.rst
  account_move_budget/readme/DESCRIPTION.rst
  account_move_budget/readme/USAGE.rst
  account_move_budget/security/ir.model.access.csv
  account_move_budget/static/description/icon.png
  account_move_budget/static/description/index.html
  account_move_budget/views/account_move_budget_line_views.xml
  account_move_budget/views/account_move_budget_views.xml
  setup/account_move_budget/odoo/addons/account_move_budget
  setup/account_move_budget/setup.py
Labels: approved, bot is merging ⏳

#1468 [14.0] account_fiscal_position_vat_check: remove field from warning banner
  account_fiscal_position_vat_check/views/res_partner.xml
Labels: needs review, approved, bot is merging ⏳

#1475 [14.0] account_check_deposit: filter source moves on state='posted'
  account_check_deposit/models/account_check_deposit.py
  account_check_deposit/views/account_check_deposit_view.xml
Labels: approved, bot is merging ⏳

#1448 [ADD] account_account_constraint_code
  account_account_constraint_code/README.rst
  account_account_constraint_code/__init__.py
  account_account_constraint_code/__manifest__.py
  account_account_constraint_code/models/__init__.py
  account_account_constraint_code/models/account_account.py
  account_account_constraint_code/readme/CONFIGURE.rst
  account_account_constraint_code/readme/CONTRIBUTORS.rst
  account_account_constraint_code/readme/DESCRIPTION.rst
  account_account_constraint_code/static/description/index.html
  account_account_constraint_code/tests/__init__.py
  account_account_constraint_code/tests/test_account_account.py
  setup/account_account_constraint_code/odoo/addons/account_account_constraint_code
  setup/account_account_constraint_code/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1231 [14.0][ADD] account_asset_low_value
  account_asset_low_value/README.rst
  account_asset_low_value/__init__.py
  account_asset_low_value/__manifest__.py
  account_asset_low_value/models/__init__.py
  account_asset_low_value/models/account_asset.py
  account_asset_low_value/readme/CONTRIBUTORS.rst
  account_asset_low_value/readme/DESCRIPTION.rst
  account_asset_low_value/static/description/icon.png
  account_asset_low_value/static/description/index.html
  account_asset_low_value/tests/__init__.py
  account_asset_low_value/tests/test_asset_low_value.py
  account_asset_low_value/views/account_asset_views.xml
  account_asset_low_value/wizard/__init__.py
  account_asset_low_value/wizard/account_asset_remove.py
  account_asset_low_value/wizard/account_asset_remove.xml
  setup/account_asset_low_value/odoo/addons/account_asset_low_value
  setup/account_asset_low_value/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1473 [16.0] [MIG] account_fiscal_year
  account_fiscal_year/README.rst
  account_fiscal_year/__init__.py
  account_fiscal_year/__manifest__.py
  account_fiscal_year/i18n/account_fiscal_year.pot
  account_fiscal_year/i18n/es.po
  account_fiscal_year/i18n/fr.po
  account_fiscal_year/i18n/fr_FR.po
  account_fiscal_year/i18n/it.po
  account_fiscal_year/i18n/nl.po
  account_fiscal_year/models/__init__.py
  account_fiscal_year/models/account_fiscal_year.py
  account_fiscal_year/models/res_company.py
  account_fiscal_year/readme/CONTRIBUTORS.rst
  account_fiscal_year/readme/DESCRIPTION.rst
  account_fiscal_year/readme/ROADMAP.rst
  account_fiscal_year/security/account_fiscal_year_rule.xml
  account_fiscal_year/security/ir.model.access.csv
  account_fiscal_year/static/description/icon.png
  account_fiscal_year/static/description/index.html
  account_fiscal_year/tests/__init__.py
  account_fiscal_year/tests/test_account_fiscal_year.py
  account_fiscal_year/views/account_fiscal_year_views.xml
  setup/account_fiscal_year/odoo/addons/account_fiscal_year
  setup/account_fiscal_year/setup.py
Labels: approved, ready to merge, bot is merging ⏳
