Repository OCA/account-financial-tools, pull requests merged in 2022-09, with the labels that each got.

#1450 [15.0][MIG] account_maturity_date_default: Migration to 15.0
  account_maturity_date_default/README.rst
  account_maturity_date_default/__init__.py
  account_maturity_date_default/__manifest__.py
  account_maturity_date_default/i18n/account_maturity_date_default.pot
  account_maturity_date_default/models/__init__.py
  account_maturity_date_default/models/account_move.py
  account_maturity_date_default/models/account_move_line.py
  account_maturity_date_default/readme/CONTRIBUTORS.rst
  account_maturity_date_default/readme/DESCRIPTION.rst
  account_maturity_date_default/static/description/icon.png
  account_maturity_date_default/static/description/index.html
  account_maturity_date_default/tests/__init__.py
  account_maturity_date_default/tests/test_account_move.py
  setup/account_maturity_date_default/odoo/addons/account_maturity_date_default
  setup/account_maturity_date_default/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1463 account_fiscal_year: change development_status to Production/Stable
  account_fiscal_year/__manifest__.py
Labels: bot is merging ⏳

#1467 [14.0][FIX] account_move_line_purchase_info: wrong migration script
  account_move_line_purchase_info/migrations/14.0.1.0.0/pre-migration.py
Labels: bot is merging ⏳

#1236 [14.0][ADD] account_move_line_check_number
  account_move_line_check_number/README.rst
  account_move_line_check_number/__init__.py
  account_move_line_check_number/__manifest__.py
  account_move_line_check_number/models/__init__.py
  account_move_line_check_number/models/account_move.py
  account_move_line_check_number/readme/CONTRIBUTORS.rst
  account_move_line_check_number/readme/DESCRIPTION.rst
  account_move_line_check_number/static/description/icon.png
  account_move_line_check_number/static/description/index.html
  account_move_line_check_number/views/account_move_views.xml
  setup/account_move_line_check_number/odoo/addons/account_move_line_check_number
  setup/account_move_line_check_number/setup.py
Labels: approved, bot is merging ⏳

#1469 [15.0][FIX] account_move_line_purchase_info: separate vendor bills from journal entries on PO
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/models/__init__.py
  account_move_line_purchase_info/models/purchase_order.py
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
  account_move_line_purchase_info/views/purchase_order_view.xml
Labels: bot is merging ⏳

#1470 [15.0][FIX] account_fiscal_year: avoid trigger of uninstall 'fiscalyear' date range type
  account_fiscal_year/migrations/15.0.1.0.0/pre-migration.py
Labels: needs review, approved, bot is merging ⏳
