Repository OCA/account-financial-tools, pull requests merged in 2022-01, with the labels that each got.

#1313 [UPD] account_asset_management: Mark as mature
  account_asset_management/__manifest__.py
Labels: approved, bot is merging ⏳

#1302 [15.0][FIX] account_move_line_*_info: call correct method _post()
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
Labels: approved, bot is merging ⏳

#1318 [12.0][IMP][MIG] account_asset_management: delete obsolete xmlids
  account_asset_management/migrations/12.0.1.0.0/post-migration.py
Labels: approved, bot is merging ⏳

#1317 [13.0][fix][account_asset_management] the asset can be removed irrespective of the Time Method used.
  account_asset_management/views/account_asset.xml
Labels: approved, bot is merging ⏳

#959 [13.0][MIG] account_document_reversal, migration to 13.0
  account_document_reversal/__init__.py
  account_document_reversal/__manifest__.py
  account_document_reversal/i18n/account_document_reversal.pot
  account_document_reversal/i18n/hr.po
  account_document_reversal/i18n/pt.po
  account_document_reversal/models/__init__.py
  account_document_reversal/models/account.py
  account_document_reversal/models/account_bank_statement.py
  account_document_reversal/models/account_document_reversal.py
  account_document_reversal/models/account_move.py
  account_document_reversal/models/account_payment.py
  account_document_reversal/models/purchase.py
  account_document_reversal/models/sale.py
  account_document_reversal/readme/CONFIGURE.rst
  account_document_reversal/readme/CONTRIBUTORS.rst
  account_document_reversal/readme/DESCRIPTION.rst
  account_document_reversal/readme/USAGE.rst
  account_document_reversal/static/description/icon.png
  account_document_reversal/static/description/index.html
  account_document_reversal/tests/__init__.py
  account_document_reversal/tests/test_invoice_reversal.py
  account_document_reversal/tests/test_payment_reversal.py
  account_document_reversal/views/account_move_view.xml
  account_document_reversal/views/account_payment_view.xml
  account_document_reversal/views/account_view.xml
  account_document_reversal/wizard/__init__.py
  account_document_reversal/wizard/reverse_account_document.py
  account_document_reversal/wizard/reverse_account_document_wizard.xml
  setup/account_document_reversal/odoo/addons/account_document_reversal
  setup/account_document_reversal/setup.py
Labels: bot is merging ⏳

#1319 [14.0][IMP] account_asset_management: assets can be removed irrespective of the Time Method used (FW port)
  account_asset_management/views/account_asset.xml
Labels: approved, ready to merge, bot is merging ⏳

#1232 [14.0][ADD] account_asset_transfer, AUC -> Asset
  account_asset_transfer/__init__.py
  account_asset_transfer/__manifest__.py
  account_asset_transfer/models/__init__.py
  account_asset_transfer/models/account_asset.py
  account_asset_transfer/models/account_asset_profile.py
  account_asset_transfer/readme/CONFIGURE.rst
  account_asset_transfer/readme/CONTRIBUTORS.rst
  account_asset_transfer/readme/DESCRIPTION.rst
  account_asset_transfer/readme/USAGE.rst
  account_asset_transfer/security/ir.model.access.csv
  account_asset_transfer/static/description/icon.png
  account_asset_transfer/tests/__init__.py
  account_asset_transfer/tests/test_account_asset_transfer.py
  account_asset_transfer/views/account_asset.xml
  account_asset_transfer/views/account_asset_profile.xml
  account_asset_transfer/wizard/__init__.py
  account_asset_transfer/wizard/account_asset_transfer.py
  account_asset_transfer/wizard/account_asset_transfer.xml
  setup/account_asset_transfer/odoo/addons/account_asset_transfer
  setup/account_asset_transfer/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1309 [15.0][MIG]base_vat_optional_vies: migration from 14.0 to 15.0
  base_vat_optional_vies/README.rst
  base_vat_optional_vies/__init__.py
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/i18n/.gitkeep
  base_vat_optional_vies/i18n/base_vat_optional_vies.pot
  base_vat_optional_vies/i18n/es.po
  base_vat_optional_vies/i18n/hr.po
  base_vat_optional_vies/i18n/pt.po
  base_vat_optional_vies/models/__init__.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONFIGURE.rst
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/readme/DESCRIPTION.rst
  base_vat_optional_vies/readme/USAGE.rst
  base_vat_optional_vies/static/description/icon.png
  base_vat_optional_vies/static/description/index.html
  base_vat_optional_vies/tests/__init__.py
  base_vat_optional_vies/tests/test_res_partner.py
  base_vat_optional_vies/views/res_partner_view.xml
  requirements.txt
  setup/base_vat_optional_vies/odoo/addons/base_vat_optional_vies
  setup/base_vat_optional_vies/setup.py
Labels: approved, bot is merging ⏳

#1315 [MIG][14.0] account_move_budget
  account_move_budget/README.rst
  account_move_budget/__init__.py
  account_move_budget/__manifest__.py
  account_move_budget/i18n/account_move_budget.pot
  account_move_budget/i18n/fr.po
  account_move_budget/models/__init__.py
  account_move_budget/models/account_move_budget.py
  account_move_budget/models/account_move_budget_line.py
  account_move_budget/readme/CONTRIBUTORS.rst
  account_move_budget/readme/DESCRIPTION.rst
  account_move_budget/readme/USAGE.rst
  account_move_budget/security/ir.model.access.csv
  account_move_budget/static/description/icon.png
  account_move_budget/static/description/index.html
  account_move_budget/views/account_move_budget_line_views.xml
  account_move_budget/views/account_move_budget_views.xml
  setup/account_move_budget/odoo/addons/account_move_budget
  setup/account_move_budget/setup.py
Labels: approved, bot is merging ⏳

#1314 [MIG][14.0] account_lock_to_date
  account_lock_to_date/README.rst
  account_lock_to_date/__init__.py
  account_lock_to_date/__manifest__.py
  account_lock_to_date/i18n/account_lock_to_date.pot
  account_lock_to_date/models/__init__.py
  account_lock_to_date/models/account_move.py
  account_lock_to_date/models/res_company.py
  account_lock_to_date/readme/CONTRIBUTORS.rst
  account_lock_to_date/readme/DESCRIPTION.rst
  account_lock_to_date/readme/USAGE.rst
  account_lock_to_date/security/ir.model.access.csv
  account_lock_to_date/static/description/icon.png
  account_lock_to_date/static/description/index.html
  account_lock_to_date/tests/__init__.py
  account_lock_to_date/tests/test_account_lock_to_date_update.py
  account_lock_to_date/wizards/__init__.py
  account_lock_to_date/wizards/account_update_lock_to_date.py
  account_lock_to_date/wizards/account_update_lock_to_date.xml
  setup/account_lock_to_date/odoo/addons/account_lock_to_date
  setup/account_lock_to_date/setup.py
Labels: approved, ready to merge, bot is merging ⏳
