Repository OCA/account-financial-tools, pull requests merged in 2022-07, with the labels that each got.

#1278 [14.0][MIG]account_move_reversal_choose_method: migration from 13.0 to 14.0
  account_move_reversal_choose_method/README.rst
  account_move_reversal_choose_method/__init__.py
  account_move_reversal_choose_method/__manifest__.py
  account_move_reversal_choose_method/i18n/account_move_reversal_choose_method.pot
  account_move_reversal_choose_method/readme/CONTRIBUTORS.rst
  account_move_reversal_choose_method/readme/DESCRIPTION.rst
  account_move_reversal_choose_method/static/description/icon.png
  account_move_reversal_choose_method/static/description/index.html
  account_move_reversal_choose_method/wizard/account_move_reversal_view.xml
  setup/account_move_reversal_choose_method/odoo/addons/account_move_reversal_choose_method
  setup/account_move_reversal_choose_method/setup.py
Labels: approved, bot is merging ⏳

#1436 [14.0][FIX] account_asset_management: Allow to write on moves with no asset permission
  account_asset_management/models/account_move.py
Labels: bot is merging ⏳

#1440 [FIX] account_move_name_sequence: Use account move date to compute prefix
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
Labels: approved, bot is merging ⏳

#1423 [14.0][ENH] account_asset_transfer: allow transfer asset without moves
  account_asset_transfer/README.rst
  account_asset_transfer/models/account_asset.py
  account_asset_transfer/readme/CONTRIBUTORS.rst
  account_asset_transfer/readme/DESCRIPTION.rst
  account_asset_transfer/static/description/index.html
  account_asset_transfer/tests/test_account_asset_transfer.py
  account_asset_transfer/views/account_asset.xml
  account_asset_transfer/wizard/account_asset_transfer.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1443 [FIX] 15.0 account_move_name_sequence: Use account move date to compute prefix
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
Labels: approved, bot is merging ⏳

#1445 [14.0][IMP] account_menu: Harmonize menu label
  account_menu/views/view_account_tax_group.xml
Labels: bot is merging ⏳

#1414 [15.0][FW][IMP] product_category_tax: apply onchanges on product variant
  product_category_tax/models/__init__.py
  product_category_tax/models/product_product.py
Labels: approved, bot is merging ⏳

#1449 [14.0][FIX] account_move_force_removal: Do tests in post-install
  account_move_force_removal/tests/test_move.py
Labels: approved, bot is merging ⏳
