Repository OCA/account-financial-tools, pull requests merged in 2022-05, with the labels that each got.

#1385 [14.0][FIX] account_sequence_option: maintain sequence of out-invoices when returning to draft and changing date.
  account_sequence_option/__manifest__.py
  account_sequence_option/readme/CONTRIBUTORS.rst
  account_sequence_option/tests/test_account_sequence_option.py
  account_sequence_option/views/account_move_views.xml
Labels: approved, bot is merging ⏳

#1387 [15.0][FIX] account_asset_management: add post-install tagged.
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/tests/test_asset_management_xls.py
Labels: bot is merging ⏳

#1357 [15.0][MIG] account fiscal year
  account_fiscal_year/README.rst
  account_fiscal_year/__init__.py
  account_fiscal_year/__manifest__.py
  account_fiscal_year/i18n/account_fiscal_year.pot
  account_fiscal_year/i18n/fr.po
  account_fiscal_year/i18n/fr_FR.po
  account_fiscal_year/i18n/it.po
  account_fiscal_year/i18n/nl.po
  account_fiscal_year/models/__init__.py
  account_fiscal_year/models/account_fiscal_year.py
  account_fiscal_year/models/res_company.py
  account_fiscal_year/readme/CONTRIBUTORS.rst
  account_fiscal_year/readme/DESCRIPTION.rst
  account_fiscal_year/readme/ROADMAP.rst
  account_fiscal_year/security/account_fiscal_year_rule.xml
  account_fiscal_year/security/ir.model.access.csv
  account_fiscal_year/static/description/icon.png
  account_fiscal_year/static/description/index.html
  account_fiscal_year/tests/__init__.py
  account_fiscal_year/tests/test_account_fiscal_year.py
  account_fiscal_year/views/account_fiscal_year_views.xml
  setup/account_fiscal_year/odoo/addons/account_fiscal_year
  setup/account_fiscal_year/setup.py
Labels: needs review, approved, bot is merging ⏳

#1326 [14.0][ENH] account_sequence_option, make demo file usable as template for custom module
  account_sequence_option/README.rst
  account_sequence_option/demo/account_demo_options.xml
  account_sequence_option/readme/DESCRIPTION.rst
  account_sequence_option/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1320 [MIG] account_asset_batch_compute: Migration to 14.0
  account_asset_batch_compute/README.rst
  account_asset_batch_compute/__init__.py
  account_asset_batch_compute/__manifest__.py
  account_asset_batch_compute/data/queue_data.xml
  account_asset_batch_compute/i18n/account_asset_batch_compute.pot
  account_asset_batch_compute/models/__init__.py
  account_asset_batch_compute/models/account_asset.py
  account_asset_batch_compute/readme/CONTRIBUTORS.rst
  account_asset_batch_compute/readme/DESCRIPTION.rst
  account_asset_batch_compute/static/description/icon.svg
  account_asset_batch_compute/static/description/index.html
  account_asset_batch_compute/tests/__init__.py
  account_asset_batch_compute/tests/test_account_asset_batch_compute.py
  account_asset_batch_compute/wizards/__init__.py
  account_asset_batch_compute/wizards/account_asset_compute.py
  account_asset_batch_compute/wizards/account_asset_compute_views.xml
  setup/account_asset_batch_compute/odoo/addons/account_asset_batch_compute
  setup/account_asset_batch_compute/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1359 [15.0][MIG] account_move_print
  account_move_print/README.rst
  account_move_print/__init__.py
  account_move_print/__manifest__.py
  account_move_print/i18n/account_move_print.pot
  account_move_print/readme/CONTRIBUTORS.rst
  account_move_print/readme/DESCRIPTION.rst
  account_move_print/readme/USAGE.rst
  account_move_print/report/journal_report.xml
  account_move_print/static/description/icon.png
  account_move_print/static/description/index.html
  setup/account_move_print/odoo/addons/account_move_print
  setup/account_move_print/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1213 [14.0][ADD] account_asset_number
  account_asset_number/README.rst
  account_asset_number/__init__.py
  account_asset_number/__manifest__.py
  account_asset_number/models/__init__.py
  account_asset_number/models/account_asset.py
  account_asset_number/models/account_asset_profile.py
  account_asset_number/readme/CONFIGURE.rst
  account_asset_number/readme/CONTRIBUTORS.rst
  account_asset_number/readme/DESCRIPTION.rst
  account_asset_number/report/__init__.py
  account_asset_number/report/account_asset_number_report.xml
  account_asset_number/report/account_asset_report_xls.py
  account_asset_number/static/description/icon.png
  account_asset_number/static/description/index.html
  account_asset_number/views/account_asset.xml
  account_asset_number/views/account_asset_profile.xml
  setup/account_asset_number/odoo/addons/account_asset_number
  setup/account_asset_number/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1386 [15.0][IMP] account_move_force_removal: add a new user group.
  account_move_force_removal/__manifest__.py
  account_move_force_removal/migrations/15.0.1.0.1/post-migration.py
  account_move_force_removal/models/account_move.py
  account_move_force_removal/security/account_move_force_removal_security.xml
  account_move_force_removal/tests/test_move.py
Labels: approved, bot is merging ⏳

#1352 [14.0][FIX] account_move_line_tax_editable: make tax field actually editable
  account_move_line_tax_editable/i18n/es.po
  account_move_line_tax_editable/models/account_move_line.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
Labels: needs review, approved, bot is merging ⏳

#1390 [13.0][FIX] account_move_line_tax_editable: make tax field actually editable (backport)
  account_move_line_tax_editable/i18n/es.po
  account_move_line_tax_editable/models/account_move_line.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
Labels: approved, bot is merging ⏳

#1393 [FIX] account_move_force_removal: buggy migration script
  account_move_force_removal/migrations/15.0.1.0.1/post-migration.py
Labels: approved, bot is merging ⏳

#1349 [13.0][ADD]: account_move_line_purchase_info: script post_install for update references on new column purchase_line_id from stock.move
  account_move_line_purchase_info/__init__.py
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/hooks.py
Labels: needs review, approved, bot is merging ⏳

#1394 [14.0] Add module account_move_name_sequence
  .copier-answers.yml
  .github/workflows/test.yml
  .pylintrc
  .pylintrc-mandatory
  account_move_name_sequence/README.rst
  account_move_name_sequence/__init__.py
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/models/__init__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/post_install.py
  account_move_name_sequence/readme/CONFIGURE.rst
  account_move_name_sequence/readme/CONTRIBUTORS.rst
  account_move_name_sequence/readme/DESCRIPTION.rst
  account_move_name_sequence/security/ir.model.access.csv
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
  account_move_name_sequence/views/account_journal.xml
  account_move_name_sequence/views/account_move.xml
  setup/account_move_name_sequence/odoo/addons/account_move_name_sequence
  setup/account_move_name_sequence/setup.py
Labels: approved, bot is merging ⏳

#1391 [15.0][MIG]account_move_line_tax_editable
  account_move_line_tax_editable/README.rst
  account_move_line_tax_editable/__init__.py
  account_move_line_tax_editable/__manifest__.py
  account_move_line_tax_editable/i18n/account_move_line_tax_editable.pot
  account_move_line_tax_editable/i18n/de.po
  account_move_line_tax_editable/i18n/es.po
  account_move_line_tax_editable/i18n/es_EC.po
  account_move_line_tax_editable/i18n/fr.po
  account_move_line_tax_editable/i18n/hr.po
  account_move_line_tax_editable/i18n/pt.po
  account_move_line_tax_editable/i18n/tr_TR.po
  account_move_line_tax_editable/models/__init__.py
  account_move_line_tax_editable/models/account_move_line.py
  account_move_line_tax_editable/readme/CONTRIBUTORS.rst
  account_move_line_tax_editable/readme/DESCRIPTION.rst
  account_move_line_tax_editable/static/description/icon.png
  account_move_line_tax_editable/static/description/index.html
  account_move_line_tax_editable/tests/__init__.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
  account_move_line_tax_editable/views/account_move.xml
  account_move_line_tax_editable/views/account_move_line.xml
  setup/account_move_line_tax_editable/odoo/addons/account_move_line_tax_editable
  setup/account_move_line_tax_editable/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1396 [FIX] account_move_name_sequence: Fix sequence domain to assign only if it is empty
  account_move_name_sequence/post_install.py
Labels: needs review, bot is merging ⏳

#1397 [REF] account_move_name_sequence: Moves with name '/' can not be posted
  account_move_name_sequence/models/account_move.py
Labels: approved, bot is merging ⏳

#1398 [FIX] account_move_name_sequence: Fix required journal fields in view
  account_move_name_sequence/views/account_journal.xml
Labels: approved, bot is merging ⏳

#1399 [REF] account_move_name_sequence: Add maintainers to myself
  account_move_name_sequence/__manifest__.py
Labels: bot is merging ⏳

#1389 [14.0][FIX] *: assertEquals -> assertEqual
  account_asset_batch_compute/tests/test_account_asset_batch_compute.py
  account_move_template/tests/test_account_move_template.py
Labels: approved, bot is merging ⏳

#1402 [13.0] [FIX] account_netting: Post move to reconcile
  account_netting/wizards/account_move_make_netting.py
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
Labels: bot is merging ⏳

#1405 [REF] account_move_name_sequence: Adding concurrency cases in README
  account_move_name_sequence/readme/DESCRIPTION.rst
Labels: bot is merging ⏳

#1407 [FIX] [14.0] base_vat_optional_vies: Simple VAT check after VIES check fails
  base_vat_optional_vies/models/res_partner.py
Labels: needs review, bot is merging ⏳

#1411 [REF] account_move_name_sequence: Use Odoo native methods + Typos
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/readme/CONFIGURE.rst
  account_move_name_sequence/readme/CONTRIBUTORS.rst
  account_move_name_sequence/views/account_journal.xml
  account_move_name_sequence/views/account_move.xml
Labels: approved, bot is merging ⏳

#1410 [MIG] account_move_name_sequence: Migration to 15.0
  account_move_name_sequence/README.rst
  account_move_name_sequence/__init__.py
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/i18n/account_move_name_sequence.pot
  account_move_name_sequence/models/__init__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/post_install.py
  account_move_name_sequence/readme/CONFIGURE.rst
  account_move_name_sequence/readme/CONTRIBUTORS.rst
  account_move_name_sequence/readme/DESCRIPTION.rst
  account_move_name_sequence/security/ir.model.access.csv
  account_move_name_sequence/static/description/icon.png
  account_move_name_sequence/static/description/index.html
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
  account_move_name_sequence/views/account_journal.xml
  account_move_name_sequence/views/account_move.xml
  setup/account_move_name_sequence/odoo/addons/account_move_name_sequence
  setup/account_move_name_sequence/setup.py
Labels: bot is merging ⏳

#1412 [13.0][IMP] product_category_tax: apply onchanges on product variant
  product_category_tax/models/__init__.py
  product_category_tax/models/product_product.py
Labels: approved, bot is merging ⏳

#1413 [14.0][FW][IMP] product_category_tax: apply onchanges on product variant
  product_category_tax/models/__init__.py
  product_category_tax/models/product_product.py
Labels: approved, bot is merging ⏳
