Repository OCA/account-financial-tools, pull requests merged in 2022-11, with the labels that each got.

#1486 [14.0][MIG] account_move_line_used_currency
  account_move_line_used_currency/README.rst
  account_move_line_used_currency/__init__.py
  account_move_line_used_currency/__manifest__.py
  account_move_line_used_currency/i18n/account_move_line_used_currency.pot
  account_move_line_used_currency/init_hooks.py
  account_move_line_used_currency/models/__init__.py
  account_move_line_used_currency/models/account_move_line.py
  account_move_line_used_currency/readme/CONTRIBUTORS.rst
  account_move_line_used_currency/readme/DESCRIPTION.rst
  account_move_line_used_currency/static/description/icon.png
  account_move_line_used_currency/static/description/index.html
  account_move_line_used_currency/tests/__init__.py
  account_move_line_used_currency/tests/test_account_move_line_used_currency.py
  account_move_line_used_currency/views/account_move_line_view.xml
  account_move_line_used_currency/views/account_move_view.xml
  setup/account_move_line_used_currency/odoo/addons/account_move_line_used_currency
  setup/account_move_line_used_currency/setup.py
Labels: approved, bot is merging ⏳

#1482 [15.0][ADD] account_chart_update_l10n_eu_oss
  account_chart_update/wizard/wizard_chart_update.py
  account_chart_update_l10n_eu_oss/README.rst
  account_chart_update_l10n_eu_oss/__init__.py
  account_chart_update_l10n_eu_oss/__manifest__.py
  account_chart_update_l10n_eu_oss/readme/CONTRIBUTORS.rst
  account_chart_update_l10n_eu_oss/readme/DESCRIPTION.rst
  account_chart_update_l10n_eu_oss/static/description/index.html
  account_chart_update_l10n_eu_oss/wizard/__init__.py
  account_chart_update_l10n_eu_oss/wizard/wizard_chart_update.py
  setup/account_chart_update_l10n_eu_oss/odoo/addons/account_chart_update_l10n_eu_oss
  setup/account_chart_update_l10n_eu_oss/setup.py
Labels: approved, ready to merge

#1489 [15.0][UPD] repo template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  account_invoice_constraint_chronology/__init__.py
Labels: bot is merging ⏳

#1488 [15.0][ADD] account_chart_update_l10n_eu_oss_oca
  account_chart_update_l10n_eu_oss_oca/README.rst
  account_chart_update_l10n_eu_oss_oca/__init__.py
  account_chart_update_l10n_eu_oss_oca/__manifest__.py
  account_chart_update_l10n_eu_oss_oca/readme/CONTRIBUTORS.rst
  account_chart_update_l10n_eu_oss_oca/readme/DESCRIPTION.rst
  account_chart_update_l10n_eu_oss_oca/static/description/icon.png
  account_chart_update_l10n_eu_oss_oca/static/description/index.html
  account_chart_update_l10n_eu_oss_oca/wizard/__init__.py
  account_chart_update_l10n_eu_oss_oca/wizard/wizard_chart_update.py
  setup/account_chart_update_l10n_eu_oss_oca/odoo/addons/account_chart_update_l10n_eu_oss_oca
  setup/account_chart_update_l10n_eu_oss_oca/setup.py
Labels: approved, bot is merging ⏳

#1490 [15.0][IMP] account_move_line_purchase_info: Journal Entries are not bills
  account_move_line_purchase_info/models/purchase_order.py
Labels: approved, ready to merge, bot is merging ⏳

#1498 [15.0][UPT] copier template
  .copier-answers.yml
  .pre-commit-config.yaml
Labels: bot is merging ⏳

#1500 [UPD] copier v13.0
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  requirements.txt
Labels: bot is merging ⏳

#1505 [13.0][FIX] account_move_line_cumulated_balance: Avoid error if record does not have partner.
  account_move_line_cumulated_balance/models/account_move_line.py
Labels: approved, bot is merging ⏳
