Repository OCA/account-financial-tools, pull requests merged in 2022-03, with the labels that each got.

#1345 [14.0] Add module account_cash_deposit
  account_cash_deposit/README.rst
  account_cash_deposit/__init__.py
  account_cash_deposit/__manifest__.py
  account_cash_deposit/data/cash_unit_cad.xml
  account_cash_deposit/data/cash_unit_chf.xml
  account_cash_deposit/data/cash_unit_eur.xml
  account_cash_deposit/data/cash_unit_usd.xml
  account_cash_deposit/data/sequence.xml
  account_cash_deposit/i18n/account_cash_deposit.pot
  account_cash_deposit/i18n/fr.po
  account_cash_deposit/models/__init__.py
  account_cash_deposit/models/account_cash_deposit.py
  account_cash_deposit/models/cash_unit.py
  account_cash_deposit/models/res_currency.py
  account_cash_deposit/readme/CONFIGURE.rst
  account_cash_deposit/readme/CONTRIBUTORS.rst
  account_cash_deposit/readme/DESCRIPTION.rst
  account_cash_deposit/readme/USAGE.rst
  account_cash_deposit/report/report.xml
  account_cash_deposit/report/report_cashdeposit.xml
  account_cash_deposit/security/ir.model.access.csv
  account_cash_deposit/security/security.xml
  account_cash_deposit/static/description/cash_deposit_form.png
  account_cash_deposit/static/description/currency_form_view.png
  account_cash_deposit/tests/__init__.py
  account_cash_deposit/tests/test_cash_deposit.py
  account_cash_deposit/views/account_cash_deposit.xml
  account_cash_deposit/views/cash_unit.xml
  account_cash_deposit/views/res_currency.xml
  account_cash_deposit/wizards/__init__.py
  account_cash_deposit/wizards/account_cash_order_reception.py
  account_cash_deposit/wizards/account_cash_order_reception_view.xml
  setup/account_cash_deposit/odoo/addons/account_cash_deposit
  setup/account_cash_deposit/setup.py
Labels: approved, bot is merging ⏳

#1277 [14.0][MIG]account_move_print: migration from 13.0 to 14.0
  account_move_print/README.rst
  account_move_print/__init__.py
  account_move_print/__manifest__.py
  account_move_print/i18n/account_move_print.pot
  account_move_print/readme/CONTRIBUTORS.rst
  account_move_print/readme/DESCRIPTION.rst
  account_move_print/readme/USAGE.rst
  account_move_print/report/journal_report.xml
  account_move_print/static/description/icon.png
  account_move_print/static/description/index.html
  setup/account_move_print/odoo/addons/account_move_print
  setup/account_move_print/setup.py
Labels: bot is merging ⏳

#1361 [13.0][FIX] account_asset_management: add move line migration scripts
  account_asset_management/migrations/13.0.1.0.0/post-migration.py
Labels: approved

#1365 [13.0][FIX] pre-commit
  account_asset_management/migrations/13.0.1.0.0/post-migration.py
Labels: bot is merging ⏳

#1364 [14.0][FIX] account_chart_update: do not match twice the same repartition line
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1367 [14.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .pre-commit-config.yaml
  README.md
  account_asset_management/models/account_asset.py
  account_asset_management/report/account_asset_report_xls.py
  account_asset_management/tests/test_asset_management_xls.py
  account_balance_line/views/account_move_line_view.xml
  account_check_deposit/tests/test_check_deposit.py
  account_journal_lock_date/tests/test_journal_lock_date.py
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_template/tests/test_account_move_template_options.py
  product_category_tax/tests/test_product_category_tax.py
Labels: help wanted, needs review
