Repository OCA/account-financial-tools, pull requests merged in 2022-08, with the labels that each got.

#1451 [13.0][FIX] account_chart_update: Incorrect call in find account method
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1453 [14.0][FIX] account_chart_update: Incorrect call in find account method
  account_chart_update/wizard/wizard_chart_update.py
Labels: bot is merging ⏳

#1454 [15.0][FIX] account_chart_update: Incorrect call in find account method
  account_chart_update/wizard/wizard_chart_update.py
Labels: bot is merging ⏳

#1437 [13.0] [IMP] `product_category_tax`: copy taxes when creating products programatically
  product_category_tax/models/product_category.py
  product_category_tax/models/product_product.py
  product_category_tax/models/product_template.py
  product_category_tax/tests/test_product_category_tax.py
Labels: approved, ready to merge, bot is merging ⏳

#1456 [REF] account_move_name_sequence: Added concurrency tests to module
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/demo/ir_sequence_demo.xml
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_sequence_concurrency.py
Labels: approved, ready to merge, bot is merging ⏳

#1438 [13.0][ADD] account_move_line_cumulated_balance: Show field cumulated balance
  account_move_line_cumulated_balance/README.rst
  account_move_line_cumulated_balance/__init__.py
  account_move_line_cumulated_balance/__manifest__.py
  account_move_line_cumulated_balance/i18n/account_move_line_cumulated_balance.pot
  account_move_line_cumulated_balance/i18n/es.po
  account_move_line_cumulated_balance/models/__init__.py
  account_move_line_cumulated_balance/models/account_move_line.py
  account_move_line_cumulated_balance/readme/CONFIGURE.rst
  account_move_line_cumulated_balance/readme/CONTRIBUTORS.rst
  account_move_line_cumulated_balance/readme/DESCRIPTION.rst
  account_move_line_cumulated_balance/readme/ROADMAP.rst
  account_move_line_cumulated_balance/readme/USAGE.rst
  account_move_line_cumulated_balance/static/description/icon.png
  account_move_line_cumulated_balance/static/description/index.html
  account_move_line_cumulated_balance/tests/__init__.py
  account_move_line_cumulated_balance/tests/test_account_move_line_cumulated_balance.py
  account_move_line_cumulated_balance/views/account_move_views.xml
  setup/account_move_line_cumulated_balance/odoo/addons/account_move_line_cumulated_balance
  setup/account_move_line_cumulated_balance/setup.py
Labels: bot is merging ⏳
