Repository OCA/account-financial-tools, pull requests merged in 2022-02, with the labels that each got.

#1329 [13.0][FIX] stock_account_prepare_anglo_saxon_out_lines_hook: update hook
  stock_account_prepare_anglo_saxon_out_lines_hook/hooks.py
Labels: bot is merging ⏳

#1330 [14.0][FIX] stock_account_prepare_anglo_saxon_out_lines_hook: update hook
  stock_account_prepare_anglo_saxon_out_lines_hook/hooks.py
Labels: bot is merging ⏳

#1333 [12.0][IMP] account_asset_management: Add chatter + activities to assets.
  account_asset_management/models/account_asset.py
  account_asset_management/views/account_asset.xml
Labels: approved, bot is merging ⏳

#1334 [13.0][IMP] account_asset_management: Add chatter + activities to assets.
  account_asset_management/models/account_asset.py
  account_asset_management/views/account_asset.xml
Labels: approved, bot is merging ⏳

#1335 [14.0][IMP] account_asset_management: Add chatter + activities to assets.
  account_asset_management/models/account_asset.py
  account_asset_management/views/account_asset.xml
Labels: approved, bot is merging ⏳

#1332 [14.0][IMP] account_asset_management: set asset_profile_id on invoice creation
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1336 [13.0][IMP] account_asset_management: set asset_profile_id on invoice creation
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1340 [13.0][FIX] stock_account_prepare_anglo_saxon_out_lines_hook: partner on aml
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move.py
Labels: bot is merging ⏳

#1341 [14.0][FIX] stock_account_prepare_anglo_saxon_out_lines_hook: partner on aml
  stock_account_prepare_anglo_saxon_out_lines_hook/models/account_move.py
Labels: bot is merging ⏳

#1337 [14.0][IMP] account_asset_management: add forward ports
  account_asset_management/__manifest__.py
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_line.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/models/account_move.py
  account_asset_management/readme/CONTRIBUTORS.rst
  account_asset_management/readme/HISTORY.rst
  account_asset_management/security/ir.model.access.csv
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/views/account_asset.xml
  account_asset_management/views/account_asset_profile.xml
  account_asset_management/wizard/__init__.py
  account_asset_management/wizard/wiz_asset_move_reverse.py
  account_asset_management/wizard/wiz_asset_move_reverse.xml
Labels: approved, bot is merging ⏳

#1291 [14.0][FIX] account_asset_management: sudo smart button asset
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1328 [FIX][14.0] account_loan: missing acl line
  account_loan/security/ir.model.access.csv
Labels: approved, ready to merge, bot is merging ⏳

#1338 [14.0][FIX] *: avoid some deprecation warnings
  account_chart_update/wizard/wizard_chart_update.py
  account_loan/model/account_loan_line.py
  account_loan/model/account_move.py
  account_loan/tests/test_loan.py
  account_loan/wizard/account_loan_post.py
Labels: approved, bot is merging ⏳

#1312 [MIG][15.0] product_category_tax
  product_category_tax/README.rst
  product_category_tax/__init__.py
  product_category_tax/__manifest__.py
  product_category_tax/i18n/product_category_tax.pot
  product_category_tax/models/__init__.py
  product_category_tax/models/product_category.py
  product_category_tax/models/product_template.py
  product_category_tax/readme/CONFIGURATION.rst
  product_category_tax/readme/CONTRIBUTORS.rst
  product_category_tax/readme/DESCRIPTION.rst
  product_category_tax/readme/USAGE.rst
  product_category_tax/static/description/icon.png
  product_category_tax/static/description/index.html
  product_category_tax/tests/__init__.py
  product_category_tax/tests/test_product_category_tax.py
  product_category_tax/views/product_category.xml
  product_category_tax/views/product_template.xml
  setup/product_category_tax/odoo/addons/product_category_tax
  setup/product_category_tax/setup.py
Labels: approved, bot is merging ⏳

#1342 [FIX] account_invoice_constraint_chronology: modify past invoices
  account_invoice_constraint_chronology/model/account_move.py
  account_invoice_constraint_chronology/tests/test_account_invoice_constraint_chronology.py
Labels: approved, bot is merging ⏳
