Repository OCA/account-financial-tools, pull requests merged in 2022-06, with the labels that each got.

#1406 [ADD] account_journal_general_sequence: account move entry sequence
  account_journal_general_sequence/README.rst
  account_journal_general_sequence/__init__.py
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/i18n/account_journal_general_sequence.pot
  account_journal_general_sequence/i18n/es.po
  account_journal_general_sequence/models/__init__.py
  account_journal_general_sequence/models/account_journal.py
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/models/account_move_line.py
  account_journal_general_sequence/readme/CONFIGURE.rst
  account_journal_general_sequence/readme/CONTRIBUTORS.rst
  account_journal_general_sequence/readme/DESCRIPTION.rst
  account_journal_general_sequence/readme/USAGE.rst
  account_journal_general_sequence/security/ir.model.access.csv
  account_journal_general_sequence/static/description/icon.png
  account_journal_general_sequence/static/description/index.html
  account_journal_general_sequence/tests/__init__.py
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/views/account_journal.xml
  account_journal_general_sequence/views/account_move.xml
  account_journal_general_sequence/views/account_move_line.xml
  account_journal_general_sequence/wizards/__init__.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard_views.xml
  requirements.txt
  setup/account_journal_general_sequence/odoo/addons/account_journal_general_sequence
  setup/account_journal_general_sequence/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1417 [MIG] account_journal_general_sequence: account move entry sequence
  account_journal_general_sequence/README.rst
  account_journal_general_sequence/__init__.py
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/i18n/account_journal_general_sequence.pot
  account_journal_general_sequence/i18n/es.po
  account_journal_general_sequence/models/__init__.py
  account_journal_general_sequence/models/account_journal.py
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/models/account_move_line.py
  account_journal_general_sequence/readme/CONFIGURE.rst
  account_journal_general_sequence/readme/CONTRIBUTORS.rst
  account_journal_general_sequence/readme/DESCRIPTION.rst
  account_journal_general_sequence/readme/USAGE.rst
  account_journal_general_sequence/security/ir.model.access.csv
  account_journal_general_sequence/static/description/icon.png
  account_journal_general_sequence/static/description/index.html
  account_journal_general_sequence/tests/__init__.py
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/views/account_journal.xml
  account_journal_general_sequence/views/account_move.xml
  account_journal_general_sequence/views/account_move_line.xml
  account_journal_general_sequence/wizards/__init__.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard_views.xml
  requirements.txt
  setup/account_journal_general_sequence/odoo/addons/account_journal_general_sequence
  setup/account_journal_general_sequence/setup.py
Labels: needs review, approved, bot is merging ⏳

#1418 [14.0] account_fiscal_position_vat_check: use warning banner
  account_fiscal_position_vat_check/__manifest__.py
  account_fiscal_position_vat_check/models/partner.py
  account_fiscal_position_vat_check/readme/CONFIGURE.rst
  account_fiscal_position_vat_check/readme/DESCRIPTION.rst
  account_fiscal_position_vat_check/readme/USAGE.rst
  account_fiscal_position_vat_check/static/description/fiscal_position_form.jpg
  account_fiscal_position_vat_check/static/description/fiscal_position_form.png
  account_fiscal_position_vat_check/static/description/vat_check_invoice_validation.jpg
  account_fiscal_position_vat_check/static/description/vat_check_invoice_validation.png
  account_fiscal_position_vat_check/static/description/warning_banner_vat_required.png
  account_fiscal_position_vat_check/views/res_partner.xml
Labels: needs review, approved, bot is merging ⏳

#1421 [FIX] account_journal_general_sequence: bottleneck at install
  account_journal_general_sequence/README.rst
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/readme/INSTALL.rst
  account_journal_general_sequence/static/description/index.html
  account_journal_general_sequence/tests/test_numbering.py
Labels: needs review

#1420 [FIX] account_journal_general_sequence: bottleneck at install
  account_journal_general_sequence/README.rst
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/readme/INSTALL.rst
  account_journal_general_sequence/static/description/index.html
  account_journal_general_sequence/tests/test_numbering.py
Labels: needs review, bot is merging ⏳

#1424 [15.0][FIX] base_vat_optional_vies: Simple VAT error message, uncheck vies_passed field
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/tests/test_res_partner.py
Labels: needs review, approved, bot is merging ⏳

#1429 [FIX][base_vat_optional_vies] Set country id with ref, one line exercise test_validate_wrong_vat_shows_simple_message
  base_vat_optional_vies/tests/test_res_partner.py
Labels: needs review, approved, bot is merging ⏳

#1428 [14.0][BKP] base_vat_optional_vies: Simple VAT error message, uncheck vies_passed field
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/tests/test_res_partner.py
Labels: needs review, approved, bot is merging ⏳

#1434 [15.0][FIX] Add entry_number field in ledger reports views
  account_journal_general_sequence/views/account_move_line.xml
Labels: needs review, approved, bot is merging ⏳

#1433 [14.0][FIX] Add entry_number field in ledger reports views
  account_journal_general_sequence/views/account_move_line.xml
Labels: needs review, approved, bot is merging ⏳
