Repository OCA/account-financial-tools, pull requests merged in 2023-05, with the labels that each got.

#1642 [FIX] account_usability: broken account.tax.group search
  account_usability/views/view_account_tax_group.xml
Labels: needs review, approved, bot is merging ⏳

#1644 [14.0][FIX] account_check_deposit: Remove create on payment line wizard
  account_check_deposit/views/account_check_deposit_view.xml
Labels: approved, bot is merging ⏳

#1632 [14.0][FIX] *: remove `python-dateutil` and `freezegun` from depends
  account_asset_management/__manifest__.py
  account_journal_general_sequence/__manifest__.py
  requirements.txt
Labels: approved, bot is merging ⏳

#1543 [15.0][MIG]account_fiscal_month: Migration to 15.0
  account_fiscal_month/README.rst
  account_fiscal_month/__init__.py
  account_fiscal_month/__manifest__.py
  account_fiscal_month/data/date_range_type.xml
  account_fiscal_month/i18n/account_fiscal_month.pot
  account_fiscal_month/i18n/de.po
  account_fiscal_month/i18n/el_GR.po
  account_fiscal_month/i18n/es.po
  account_fiscal_month/i18n/es_EC.po
  account_fiscal_month/i18n/fi.po
  account_fiscal_month/i18n/fr.po
  account_fiscal_month/i18n/hr.po
  account_fiscal_month/i18n/hr_HR.po
  account_fiscal_month/i18n/it.po
  account_fiscal_month/i18n/lt.po
  account_fiscal_month/i18n/nl.po
  account_fiscal_month/i18n/nl_NL.po
  account_fiscal_month/i18n/pt.po
  account_fiscal_month/i18n/pt_BR.po
  account_fiscal_month/i18n/sk.po
  account_fiscal_month/i18n/sl.po
  account_fiscal_month/i18n/tr.po
  account_fiscal_month/i18n/tr_TR.po
  account_fiscal_month/models/__init__.py
  account_fiscal_month/models/date_range_type.py
  account_fiscal_month/models/res_company.py
  account_fiscal_month/readme/CONTRIBUTORS.rst
  account_fiscal_month/readme/DESCRIPTION.rst
  account_fiscal_month/static/description/icon.png
  account_fiscal_month/static/description/index.html
  account_fiscal_month/tests/__init__.py
  account_fiscal_month/tests/test_account_fiscal_month.py
  account_fiscal_month/views/date_range_type.xml
  setup/account_fiscal_month/odoo/addons/account_fiscal_month
  setup/account_fiscal_month/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1627 [15.0][MIG] account_move_fiscal_month
  account_move_fiscal_month/README.rst
  account_move_fiscal_month/__init__.py
  account_move_fiscal_month/__manifest__.py
  account_move_fiscal_month/i18n/account_move_fiscal_month.pot
  account_move_fiscal_month/i18n/am.po
  account_move_fiscal_month/i18n/ca.po
  account_move_fiscal_month/i18n/de.po
  account_move_fiscal_month/i18n/es.po
  account_move_fiscal_month/i18n/es_EC.po
  account_move_fiscal_month/i18n/fr.po
  account_move_fiscal_month/i18n/gl.po
  account_move_fiscal_month/i18n/hr.po
  account_move_fiscal_month/i18n/hr_HR.po
  account_move_fiscal_month/i18n/it.po
  account_move_fiscal_month/i18n/nl.po
  account_move_fiscal_month/i18n/pt.po
  account_move_fiscal_month/i18n/pt_BR.po
  account_move_fiscal_month/i18n/pt_PT.po
  account_move_fiscal_month/i18n/sl.po
  account_move_fiscal_month/i18n/tr_TR.po
  account_move_fiscal_month/models/__init__.py
  account_move_fiscal_month/models/account_move.py
  account_move_fiscal_month/models/account_move_line.py
  account_move_fiscal_month/readme/CONFIGURE.rst
  account_move_fiscal_month/readme/CONTRIBUTORS.rst
  account_move_fiscal_month/readme/DESCRIPTION.rst
  account_move_fiscal_month/static/description/icon.png
  account_move_fiscal_month/static/description/index.html
  account_move_fiscal_month/tests/__init__.py
  account_move_fiscal_month/tests/test_account_move_fiscal_month.py
  account_move_fiscal_month/views/account_move.xml
  account_move_fiscal_month/views/account_move_line.xml
  setup/account_move_fiscal_month/odoo/addons/account_move_fiscal_month
  setup/account_move_fiscal_month/setup.py
Labels: approved, bot is merging ⏳

#1508 [16.0][MIG] account_move_line_tax_editable: Migration to 16.0
  account_move_line_tax_editable/README.rst
  account_move_line_tax_editable/__init__.py
  account_move_line_tax_editable/__manifest__.py
  account_move_line_tax_editable/i18n/account_move_line_tax_editable.pot
  account_move_line_tax_editable/i18n/de.po
  account_move_line_tax_editable/i18n/es.po
  account_move_line_tax_editable/i18n/es_EC.po
  account_move_line_tax_editable/i18n/fr.po
  account_move_line_tax_editable/i18n/hr.po
  account_move_line_tax_editable/i18n/pt.po
  account_move_line_tax_editable/i18n/tr_TR.po
  account_move_line_tax_editable/models/__init__.py
  account_move_line_tax_editable/models/account_move_line.py
  account_move_line_tax_editable/readme/CONTRIBUTORS.rst
  account_move_line_tax_editable/readme/DESCRIPTION.rst
  account_move_line_tax_editable/static/description/icon.png
  account_move_line_tax_editable/static/description/index.html
  account_move_line_tax_editable/tests/__init__.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
  account_move_line_tax_editable/views/account_move.xml
  setup/account_move_line_tax_editable/odoo/addons/account_move_line_tax_editable
  setup/account_move_line_tax_editable/setup.py
Labels: needs review, bot is merging ⏳

#1650 [16.0][FIX] account_fiscal_year: website in __manifest__.py
  account_fiscal_year/__manifest__.py
Labels: bot is merging ⏳
