Repository OCA/account-financial-tools, pull requests merged in 2023-06, with the labels that each got.

#1611 [16.0][MIG] account_asset_batch_compute: Migration to 16.0
  account_asset_batch_compute/README.rst
  account_asset_batch_compute/__init__.py
  account_asset_batch_compute/__manifest__.py
  account_asset_batch_compute/data/queue_data.xml
  account_asset_batch_compute/i18n/account_asset_batch_compute.pot
  account_asset_batch_compute/i18n/es.po
  account_asset_batch_compute/models/__init__.py
  account_asset_batch_compute/models/account_asset.py
  account_asset_batch_compute/readme/CONTRIBUTORS.rst
  account_asset_batch_compute/readme/DESCRIPTION.rst
  account_asset_batch_compute/static/description/icon.svg
  account_asset_batch_compute/static/description/index.html
  account_asset_batch_compute/tests/__init__.py
  account_asset_batch_compute/tests/test_account_asset_batch_compute.py
  account_asset_batch_compute/wizards/__init__.py
  account_asset_batch_compute/wizards/account_asset_compute.py
  account_asset_batch_compute/wizards/account_asset_compute_views.xml
  setup/account_asset_batch_compute/odoo/addons/account_asset_batch_compute
  setup/account_asset_batch_compute/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1245 [14.0][ADD] account_spread_cost_revenue_enhanced
  account_spread_cost_revenue_enhanced/README.rst
  account_spread_cost_revenue_enhanced/__init__.py
  account_spread_cost_revenue_enhanced/__manifest__.py
  account_spread_cost_revenue_enhanced/models/__init__.py
  account_spread_cost_revenue_enhanced/models/account_spread.py
  account_spread_cost_revenue_enhanced/models/account_spread_line.py
  account_spread_cost_revenue_enhanced/readme/CONTRIBUTORS.rst
  account_spread_cost_revenue_enhanced/readme/DESCRIPTION.rst
  account_spread_cost_revenue_enhanced/security/ir.model.access.csv
  account_spread_cost_revenue_enhanced/static/description/icon.png
  account_spread_cost_revenue_enhanced/static/description/index.html
  account_spread_cost_revenue_enhanced/views/account_spread.xml
  account_spread_cost_revenue_enhanced/wizards/__init__.py
  account_spread_cost_revenue_enhanced/wizards/account_spread_link_move_line.py
  account_spread_cost_revenue_enhanced/wizards/account_spread_link_move_line.xml
  setup/account_spread_cost_revenue_enhanced/odoo/addons/account_spread_cost_revenue_enhanced
  setup/account_spread_cost_revenue_enhanced/setup.py
Labels: approved, bot is merging ⏳

#1671 [FIX] account_journal_general_sequence: unique entry number per journal
  account_journal_general_sequence/i18n/account_journal_general_sequence.pot
  account_journal_general_sequence/i18n/es.po
  account_journal_general_sequence/models/account_move.py
Labels: bot is merging ⏳

#1672 [FIX] account_journal_general_sequence: unique entry number per journal
  account_journal_general_sequence/i18n/account_journal_general_sequence.pot
  account_journal_general_sequence/i18n/es.po
  account_journal_general_sequence/models/account_move.py
Labels: bot is merging ⏳

#1673 [FIX] account_journal_general_sequence: unique entry number per journal
  account_journal_general_sequence/i18n/account_journal_general_sequence.pot
  account_journal_general_sequence/i18n/es.po
  account_journal_general_sequence/models/account_move.py
Labels: bot is merging ⏳

#1670 [15.0][FIX] account_asset_management: Allow to write on moves with no asset permission
  account_asset_management/models/account_move.py
Labels: bot is merging ⏳

#1674 [16.0][FIX] account_asset_management: Allow to write on moves with no asset permission
  account_asset_management/models/account_move.py
Labels: bot is merging ⏳

#1675 [FIX] account_journal_general_sequence: optimize recomputes when renumbering
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/tests/test_numbering.py
Labels: bot is merging ⏳

#1677 [FIX] account_journal_general_sequence: optimize recomputes when renumbering
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/tests/test_numbering.py
Labels: bot is merging ⏳

#1676 [FIX] account_journal_general_sequence: optimize recomputes when renumbering
  account_journal_general_sequence/models/account_move.py
  account_journal_general_sequence/tests/test_numbering.py
Labels: bot is merging ⏳

#1666 [16.0][FIX] account_invoice_constraint_chronology: maintain numbering consistency when changing invoice dates
  account_invoice_constraint_chronology/model/account_move.py
  account_invoice_constraint_chronology/tests/test_account_invoice_constraint_chronology.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1679 [14.0][IMP] account_asset_management: add asset_profile_id and asset_id on invoice_lines form
  account_asset_management/views/account_move.xml
Labels: approved, bot is merging ⏳

#1665 [FIX] account_journal_general_sequence fix multicompany
  account_journal_general_sequence/__manifest__.py
  account_journal_general_sequence/migrations/16.0.2.0.0/post-migration.py
  account_journal_general_sequence/models/account_journal.py
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/views/account_journal.xml
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
Labels: needs review, bot is merging ⏳
