Repository OCA/account-financial-tools, pull requests merged in 2023-11, with the labels that each got.

#1542 [16.0][MIG] account_partner_required
  account_partner_required/README.rst
  account_partner_required/__init__.py
  account_partner_required/__manifest__.py
  account_partner_required/i18n/account_partner_required.pot
  account_partner_required/i18n/ar.po
  account_partner_required/i18n/bs.po
  account_partner_required/i18n/cs.po
  account_partner_required/i18n/de.po
  account_partner_required/i18n/en_GB.po
  account_partner_required/i18n/es.po
  account_partner_required/i18n/es_CR.po
  account_partner_required/i18n/es_EC.po
  account_partner_required/i18n/es_MX.po
  account_partner_required/i18n/fr.po
  account_partner_required/i18n/hr.po
  account_partner_required/i18n/hu.po
  account_partner_required/i18n/it.po
  account_partner_required/i18n/ja.po
  account_partner_required/i18n/lt.po
  account_partner_required/i18n/mk.po
  account_partner_required/i18n/mn.po
  account_partner_required/i18n/nb.po
  account_partner_required/i18n/nl.po
  account_partner_required/i18n/nl_BE.po
  account_partner_required/i18n/nl_NL.po
  account_partner_required/i18n/pt.po
  account_partner_required/i18n/pt_BR.po
  account_partner_required/i18n/ro.po
  account_partner_required/i18n/ru.po
  account_partner_required/i18n/sl.po
  account_partner_required/i18n/sv.po
  account_partner_required/i18n/tr.po
  account_partner_required/i18n/tr_TR.po
  account_partner_required/i18n/zh_CN.po
  account_partner_required/i18n/zh_TW.po
  account_partner_required/models/__init__.py
  account_partner_required/models/account_account.py
  account_partner_required/models/account_move_line.py
  account_partner_required/readme/CONFIGURE.rst
  account_partner_required/readme/CONTRIBUTORS.rst
  account_partner_required/readme/DESCRIPTION.rst
  account_partner_required/readme/USAGE.rst
  account_partner_required/static/description/icon.png
  account_partner_required/static/description/index.html
  account_partner_required/tests/__init__.py
  account_partner_required/tests/test_account_partner_required.py
  account_partner_required/views/account_account.xml
  setup/account_partner_required/odoo/addons/account_partner_required
  setup/account_partner_required/setup.py
Labels: needs review, bot is merging ⏳

#1769 [14.0][FIX] pre-commit with new copier template
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_asset_compute_batch/i18n/account_asset_compute_batch.pot
  account_asset_compute_batch/security/account_asset_security.xml
  account_asset_compute_batch/views/account_asset_compute_batch.xml
  account_asset_management/data/cron.xml
  account_asset_management/i18n/account_asset_management.pot
  account_asset_management/security/account_asset_security.xml
  account_asset_management/views/account_asset.xml
  account_asset_management/views/account_asset_group.xml
  account_asset_management/views/account_asset_profile.xml
  account_cash_deposit/i18n/account_cash_deposit.pot
  account_cash_deposit/report/report_cashdeposit.xml
  account_chart_update/i18n/de.po
  account_chart_update/wizard/wizard_chart_update_view.xml
  account_check_deposit/i18n/account_check_deposit.pot
  account_check_deposit/report/report_checkdeposit.xml
  account_journal_lock_date/i18n/hr.po
  account_journal_lock_date/views/account_journal.xml
  account_loan/i18n/account_loan.pot
  account_loan/views/account_loan_lines_view.xml
  account_loan/views/account_loan_view.xml
  account_move_budget/i18n/account_move_budget.pot
  account_move_transfer_partner/wizard/wizard_account_move_transfer_partner_view.xml
  account_spread_cost_revenue/i18n/account_spread_cost_revenue.pot
  account_spread_cost_revenue/security/account_spread_security.xml
Labels: approved, bot is merging ⏳

#1772 [16.0][FIX TESTS] account_fiscal_month: share date.range.type between companies
  account_fiscal_month/data/date_range_type.xml
Labels: bot is merging ⏳

#1770 [16.0] account_netting: fix and improve strings
  account_netting/wizards/account_move_make_netting.py
Labels: bot is merging ⏳

#1765 [16.0] account_move_template: fix and improve strings
  account_move_template/models/account_move_template.py
  account_move_template/tests/test_account_move_template_options.py
  account_move_template/wizard/account_move_template_run.py
Labels: bot is merging ⏳

#1758 [15.0] dotfiles update needs manual intervention
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_asset_management/i18n/account_asset_management.pot
  account_check_deposit/i18n/account_check_deposit.pot
  account_check_deposit/report/report_checkdeposit.xml
  account_move_budget/i18n/account_move_budget.pot
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1763 [14.0][FIX] remove duplicated field in account_menu
  account_menu/views/view_account_tag.xml
Labels: bot is merging ⏳

#1778 account_check_deposit: fix printing report
  account_check_deposit/report/report_checkdeposit.xml
Labels: bot is merging ⏳

#1669 [16.0][MIG] account_move_line_check_number
  account_move_line_check_number/README.rst
  account_move_line_check_number/__init__.py
  account_move_line_check_number/__manifest__.py
  account_move_line_check_number/i18n/account_move_line_check_number.pot
  account_move_line_check_number/models/__init__.py
  account_move_line_check_number/models/account_move.py
  account_move_line_check_number/readme/CONTRIBUTORS.rst
  account_move_line_check_number/readme/DESCRIPTION.rst
  account_move_line_check_number/static/description/icon.png
  account_move_line_check_number/static/description/index.html
  account_move_line_check_number/views/account_move_views.xml
  setup/account_move_line_check_number/odoo/addons/account_move_line_check_number
  setup/account_move_line_check_number/setup.py
Labels: approved, bot is merging ⏳

#1755 [FIX] account_move_name_sequence: redefine _onchange_journal_id
  account_move_name_sequence/models/account_move.py
Labels: approved, bot is merging ⏳

#1458 [FWD][15.0] [IMP] `product_category_tax`: copy taxes when creating products programatically
  product_category_tax/models/product_category.py
  product_category_tax/models/product_product.py
  product_category_tax/models/product_template.py
  product_category_tax/tests/test_product_category_tax.py
Labels: approved, bot is merging ⏳

#1584 [IMP] account_menu: Show Account move lines on Partner
  account_usability/__manifest__.py
  account_usability/views/view_account_move_line.xml
Labels: approved, bot is merging ⏳

#1754 [16.0][ADD] account_account_tag_code
  account_account_tag_code/README.rst
  account_account_tag_code/__init__.py
  account_account_tag_code/__manifest__.py
  account_account_tag_code/models/__init__.py
  account_account_tag_code/models/account_account_tag.py
  account_account_tag_code/views/account_account_tag_views.xml
  setup/account_account_tag_code/odoo/addons/account_account_tag_code
  setup/account_account_tag_code/setup.py
Labels: approved, bot is merging ⏳

#1781 [FIX] wizard_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
Labels: bot is merging ⏳

#1646 [15.0][MIG] account_spread_cost_revenue
  account_spread_cost_revenue/README.rst
  account_spread_cost_revenue/__init__.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/data/spread_cron.xml
  account_spread_cost_revenue/i18n/account_spread_cost_revenue.pot
  account_spread_cost_revenue/i18n/fr.po
  account_spread_cost_revenue/i18n/nl.po
  account_spread_cost_revenue/i18n/pt.po
  account_spread_cost_revenue/models/__init__.py
  account_spread_cost_revenue/models/account_move.py
  account_spread_cost_revenue/models/account_move_line.py
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/models/account_spread_line.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/models/res_company.py
  account_spread_cost_revenue/readme/CONFIGURE.rst
  account_spread_cost_revenue/readme/CONTRIBUTORS.rst
  account_spread_cost_revenue/readme/CREDITS.rst
  account_spread_cost_revenue/readme/DESCRIPTION.rst
  account_spread_cost_revenue/readme/HISTORY.rst
  account_spread_cost_revenue/readme/USAGE.rst
  account_spread_cost_revenue/security/account_spread_security.xml
  account_spread_cost_revenue/security/ir.model.access.csv
  account_spread_cost_revenue/static/description/create_spread.png
  account_spread_cost_revenue/static/description/icon.png
  account_spread_cost_revenue/static/description/index.html
  account_spread_cost_revenue/static/description/invoice_line_1.png
  account_spread_cost_revenue/static/description/invoice_line_2.png
  account_spread_cost_revenue/static/description/spread.png
  account_spread_cost_revenue/static/description/update_spread.png
  account_spread_cost_revenue/static/src/js/account_spread.js
  account_spread_cost_revenue/static/src/scss/account_spread.scss
  account_spread_cost_revenue/tests/__init__.py
  account_spread_cost_revenue/tests/test_account_invoice_auto_spread.py
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
  account_spread_cost_revenue/tests/test_account_spread_cost_revenue.py
  account_spread_cost_revenue/tests/test_compute_spread_board.py
  account_spread_cost_revenue/views/account_move.xml
  account_spread_cost_revenue/views/account_spread.xml
  account_spread_cost_revenue/views/account_spread_template.xml
  account_spread_cost_revenue/views/res_company.xml
  account_spread_cost_revenue/wizards/__init__.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.xml
  setup/account_spread_cost_revenue/odoo/addons/account_spread_cost_revenue
  setup/account_spread_cost_revenue/setup.py
Labels: bot is merging ⏳
