Repository OCA/account-financial-tools, pull requests merged in 2023-03, with the labels that each got.

#1597 TEST: check why loan provoques a fail.
  .copier-answers.yml
  .pre-commit-config.yaml
  account_loan/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#1600 [14.0] [IMP] account_loan
  account_loan/views/account_loan_view.xml
Labels: approved, bot is merging ⏳

#1593 [15.0][MIG] account_lock_to_date
  account_lock_to_date/README.rst
  account_lock_to_date/__init__.py
  account_lock_to_date/__manifest__.py
  account_lock_to_date/i18n/account_lock_to_date.pot
  account_lock_to_date/i18n/fr.po
  account_lock_to_date/models/__init__.py
  account_lock_to_date/models/account_move.py
  account_lock_to_date/models/res_company.py
  account_lock_to_date/readme/CONTRIBUTORS.rst
  account_lock_to_date/readme/DESCRIPTION.rst
  account_lock_to_date/readme/USAGE.rst
  account_lock_to_date/security/ir.model.access.csv
  account_lock_to_date/static/description/icon.png
  account_lock_to_date/static/description/index.html
  account_lock_to_date/tests/__init__.py
  account_lock_to_date/tests/test_account_lock_to_date_update.py
  account_lock_to_date/wizards/__init__.py
  account_lock_to_date/wizards/account_update_lock_to_date.py
  account_lock_to_date/wizards/account_update_lock_to_date.xml
  setup/account_lock_to_date/odoo/addons/account_lock_to_date
  setup/account_lock_to_date/setup.py
Labels: approved, bot is merging ⏳

#1574 [14.0][IMP] account_move_template: force_company
  account_move_template/tests/test_account_move_template.py
Labels: approved, bot is merging ⏳

#1513 [14.0][IMP] account_asset_management: big code cleanup
  account_asset_management/models/account_account.py
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_line.py
  account_asset_management/models/account_move.py
  account_asset_management/views/account_account.xml
  account_asset_management/views/account_asset.xml
  account_asset_management/wizard/account_asset_remove.py
Labels: approved, bot is merging ⏳

#1608 [16.0][FIX] account_cash_deposit: fix empty error
  account_cash_deposit/models/account_cash_deposit.py
Labels: bot is merging ⏳

#1609 [14.0][FIX] account_cash_deposit: fix empty error
  account_cash_deposit/models/account_cash_deposit.py
Labels: bot is merging ⏳

#1605 [14.0][IMP] account_loan: remove numpy from explicit requirements
  account_loan/__manifest__.py
  requirements.txt
  test-requirements.txt
Labels: bot is merging ⏳

#1583 [IMP] account_menu: Show Account move lines on Partner
  account_menu/__manifest__.py
  account_menu/views/view_account_move_line.xml
Labels: approved, bot is merging ⏳

#1321 [14.0][ADD] account_asset_from_expense
  account_asset_from_expense/README.rst
  account_asset_from_expense/__init__.py
  account_asset_from_expense/__manifest__.py
  account_asset_from_expense/models/__init__.py
  account_asset_from_expense/models/hr_expense.py
  account_asset_from_expense/readme/CONTRIBUTORS.rst
  account_asset_from_expense/readme/DESCRIPTION.rst
  account_asset_from_expense/security/ir.model.access.csv
  account_asset_from_expense/static/description/icon.png
  account_asset_from_expense/static/description/index.html
  account_asset_from_expense/tests/__init__.py
  account_asset_from_expense/tests/test_account_asset_from_expense.py
  account_asset_from_expense/views/hr_expense_views.xml
  setup/account_asset_from_expense/odoo/addons/account_asset_from_expense
  setup/account_asset_from_expense/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1615 [16.0][FIX] account_move_name_sequence: computed fields raising warning
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/account_move.py
Labels: bot is merging ⏳

#1624 [14.0][FIX] account_fiscal_year: fix website in manifest
  account_fiscal_year/__manifest__.py
Labels: approved, bot is merging ⏳

#1619 [14.0][IMP] account_chart_update: Update account groups too
  account_chart_update/security/ir.model.access.csv
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
  account_chart_update/wizard/wizard_chart_update_view.xml
Labels: needs review, approved, bot is merging ⏳
