Repository OCA/account-financial-tools, pull requests merged in 2023-09, with the labels that each got.

#1708 [16.0][MIG] account_fiscal_month: Migration to 16.0
  account_fiscal_month/README.rst
  account_fiscal_month/__init__.py
  account_fiscal_month/__manifest__.py
  account_fiscal_month/data/date_range_type.xml
  account_fiscal_month/i18n/account_fiscal_month.pot
  account_fiscal_month/i18n/de.po
  account_fiscal_month/i18n/el_GR.po
  account_fiscal_month/i18n/es.po
  account_fiscal_month/i18n/es_EC.po
  account_fiscal_month/i18n/fi.po
  account_fiscal_month/i18n/fr.po
  account_fiscal_month/i18n/hr.po
  account_fiscal_month/i18n/hr_HR.po
  account_fiscal_month/i18n/it.po
  account_fiscal_month/i18n/lt.po
  account_fiscal_month/i18n/nl.po
  account_fiscal_month/i18n/nl_NL.po
  account_fiscal_month/i18n/pt.po
  account_fiscal_month/i18n/pt_BR.po
  account_fiscal_month/i18n/sk.po
  account_fiscal_month/i18n/sl.po
  account_fiscal_month/i18n/tr.po
  account_fiscal_month/i18n/tr_TR.po
  account_fiscal_month/models/__init__.py
  account_fiscal_month/models/date_range_type.py
  account_fiscal_month/models/res_company.py
  account_fiscal_month/readme/CONTRIBUTORS.rst
  account_fiscal_month/readme/DESCRIPTION.rst
  account_fiscal_month/static/description/icon.png
  account_fiscal_month/static/description/index.html
  account_fiscal_month/tests/__init__.py
  account_fiscal_month/tests/test_account_fiscal_month.py
  account_fiscal_month/views/date_range_type.xml
  setup/account_fiscal_month/odoo/addons/account_fiscal_month
  setup/account_fiscal_month/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1710 [16.0][MIG] account_move_fiscal_year: Migration to 16.0
  account_move_fiscal_year/README.rst
  account_move_fiscal_year/__init__.py
  account_move_fiscal_year/__manifest__.py
  account_move_fiscal_year/i18n/account_move_fiscal_year.pot
  account_move_fiscal_year/i18n/am.po
  account_move_fiscal_year/i18n/ar.po
  account_move_fiscal_year/i18n/ca.po
  account_move_fiscal_year/i18n/de.po
  account_move_fiscal_year/i18n/es.po
  account_move_fiscal_year/i18n/es_CO.po
  account_move_fiscal_year/i18n/es_EC.po
  account_move_fiscal_year/i18n/fr.po
  account_move_fiscal_year/i18n/fr_FR.po
  account_move_fiscal_year/i18n/gl.po
  account_move_fiscal_year/i18n/hr.po
  account_move_fiscal_year/i18n/hr_HR.po
  account_move_fiscal_year/i18n/it.po
  account_move_fiscal_year/i18n/nl.po
  account_move_fiscal_year/i18n/pt.po
  account_move_fiscal_year/i18n/pt_BR.po
  account_move_fiscal_year/i18n/pt_PT.po
  account_move_fiscal_year/i18n/sl.po
  account_move_fiscal_year/i18n/tr_TR.po
  account_move_fiscal_year/models/__init__.py
  account_move_fiscal_year/models/account_move.py
  account_move_fiscal_year/models/account_move_line.py
  account_move_fiscal_year/models/res_company.py
  account_move_fiscal_year/readme/CONTRIBUTORS.rst
  account_move_fiscal_year/readme/DESCRIPTION.rst
  account_move_fiscal_year/readme/INSTALL.rst
  account_move_fiscal_year/readme/USAGE.rst
  account_move_fiscal_year/static/description/icon.png
  account_move_fiscal_year/static/description/index.html
  account_move_fiscal_year/tests/__init__.py
  account_move_fiscal_year/tests/test_account_move_fiscal_year.py
  account_move_fiscal_year/views/account_move.xml
  account_move_fiscal_year/views/account_move_line.xml
  setup/account_move_fiscal_year/odoo/addons/account_move_fiscal_year
  setup/account_move_fiscal_year/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1322 [14.0][ENH] account_asset_transfer: add feature expand asset line
  account_asset_transfer/README.rst
  account_asset_transfer/readme/USAGE.rst
  account_asset_transfer/static/description/index.html
  account_asset_transfer/tests/test_account_asset_transfer.py
  account_asset_transfer/wizard/account_asset_transfer.py
  account_asset_transfer/wizard/account_asset_transfer.xml
Labels: approved, ready to merge, bot is merging ⏳

#1240 [14.0][ADD] account_asset_stock_move
  account_asset_stock_move/__init__.py
  account_asset_stock_move/__manifest__.py
  account_asset_stock_move/models/__init__.py
  account_asset_stock_move/models/stock_move.py
  account_asset_stock_move/models/stock_picking.py
  account_asset_stock_move/readme/CONFIGURE.rst
  account_asset_stock_move/readme/CONTRIBUTORS.rst
  account_asset_stock_move/readme/DESCRIPTION.rst
  account_asset_stock_move/readme/USAGE.rst
  account_asset_stock_move/static/description/icon.png
  account_asset_stock_move/tests/__init__.py
  account_asset_stock_move/tests/test_account_asset_stock_move.py
  account_asset_stock_move/views/stock.xml
  setup/account_asset_stock_move/odoo/addons/account_asset_stock_move
  setup/account_asset_stock_move/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1507 [15.0][MIG] account_asset_transfer
  account_asset_transfer/README.rst
  account_asset_transfer/__init__.py
  account_asset_transfer/__manifest__.py
  account_asset_transfer/i18n/account_asset_transfer.pot
  account_asset_transfer/models/__init__.py
  account_asset_transfer/models/account_asset.py
  account_asset_transfer/models/account_asset_profile.py
  account_asset_transfer/readme/CONFIGURE.rst
  account_asset_transfer/readme/CONTRIBUTORS.rst
  account_asset_transfer/readme/DESCRIPTION.rst
  account_asset_transfer/readme/USAGE.rst
  account_asset_transfer/security/ir.model.access.csv
  account_asset_transfer/static/description/icon.png
  account_asset_transfer/static/description/index.html
  account_asset_transfer/tests/__init__.py
  account_asset_transfer/tests/test_account_asset_transfer.py
  account_asset_transfer/views/account_asset.xml
  account_asset_transfer/views/account_asset_profile.xml
  account_asset_transfer/wizard/__init__.py
  account_asset_transfer/wizard/account_asset_transfer.py
  account_asset_transfer/wizard/account_asset_transfer.xml
  setup/account_asset_transfer/odoo/addons/account_asset_transfer
  setup/account_asset_transfer/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1728 [14.0][IMP][14.0]Add some optional fields to loan tree view
  account_loan/static/description/index.html
  account_loan/views/account_loan_view.xml
Labels: bot is merging ⏳

#1723 [15.0][FIX] account_asset_management: KeyError
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳
