Repository OCA/account-financial-tools, pull requests merged in 2023-01, with the labels that each got.

#1481 [16.0][MIG] account_move_print: Migration to 16.0
  account_move_print/README.rst
  account_move_print/__init__.py
  account_move_print/__manifest__.py
  account_move_print/i18n/account_move_print.pot
  account_move_print/readme/CONTRIBUTORS.rst
  account_move_print/readme/DESCRIPTION.rst
  account_move_print/readme/USAGE.rst
  account_move_print/report/journal_report.xml
  account_move_print/static/description/icon.png
  account_move_print/static/description/index.html
  setup/account_move_print/odoo/addons/account_move_print
  setup/account_move_print/setup.py
Labels: bot is merging ⏳

#1545 [14.0][FIX] account_balance_line: Show balance field (instead of adding it again) to avoid it being shown twice in some cases.
  account_balance_line/views/account_move_line_view.xml
Labels: bot is merging ⏳

#1546 [15.0][FIX] account_balance_line: Show balance field (instead of adding it again) to avoid it being shown twice in some cases.
  account_balance_line/views/account_move_line_view.xml
Labels: approved, bot is merging ⏳

#1547 [FIX] pre-commit fixes
  .copier-answers.yml
  .editorconfig
  .flake8
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  LICENSE
  README.md
  account_cash_basis_group_base_line/__manifest__.py
  account_chart_update/__manifest__.py
  account_chart_update/i18n/de.po
  account_chart_update/i18n/es.po
  account_check_deposit/__manifest__.py
  account_cost_center/__manifest__.py
  account_fiscal_year/__manifest__.py
  account_fiscal_year_auto_create/__manifest__.py
  account_invoice_constraint_chronology/__manifest__.py
  account_journal_lock_date/i18n/hr.po
  account_loan/__manifest__.py
  account_move_chatter/__manifest__.py
  account_move_line_purchase_info/__manifest__.py
  account_netting/__manifest__.py
  account_payment_netting/__manifest__.py
  account_permanent_lock_move/__init__.py
  account_spread_cost_revenue/__manifest__.py
  account_subsequence_fiscal_year/__manifest__.py
  account_voucher_print/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#872 12.0 imp account check deposit
  account_check_deposit/__manifest__.py
  account_check_deposit/migrations/12.0.2.0.1/post-migration.py
  account_check_deposit/models/__init__.py
  account_check_deposit/models/account_deposit.py
  account_check_deposit/models/account_journal.py
  account_check_deposit/readme/DESCRIPTION.rst
  account_check_deposit/readme/ROADMAP.rst
  account_check_deposit/report/report_checkdeposit.xml
  account_check_deposit/views/account_deposit_view.xml
  account_check_deposit/views/account_journal_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#1551 [FIX] account_chart_update: false positive detecting diff on Html fields
  account_chart_update/readme/CONTRIBUTORS.rst
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1552 [FIX] account_chart_update: responsive views
  account_chart_update/wizard/wizard_chart_update_view.xml
Labels: needs review, approved, bot is merging ⏳

#1550 [14.0][FIX] account_menu - split filter between name and sequence on tax group
  account_menu/views/view_account_tax_group.xml
Labels: approved, ready to merge, bot is merging ⏳

#1531 [16.0][MIG] account_cash_deposit
  account_cash_deposit/README.rst
  account_cash_deposit/__init__.py
  account_cash_deposit/__manifest__.py
  account_cash_deposit/data/cash_unit_cad.xml
  account_cash_deposit/data/cash_unit_chf.xml
  account_cash_deposit/data/cash_unit_eur.xml
  account_cash_deposit/data/cash_unit_usd.xml
  account_cash_deposit/data/sequence.xml
  account_cash_deposit/i18n/account_cash_deposit.pot
  account_cash_deposit/i18n/fr.po
  account_cash_deposit/models/__init__.py
  account_cash_deposit/models/account_cash_deposit.py
  account_cash_deposit/models/cash_unit.py
  account_cash_deposit/models/res_currency.py
  account_cash_deposit/readme/CONFIGURE.rst
  account_cash_deposit/readme/CONTRIBUTORS.rst
  account_cash_deposit/readme/DESCRIPTION.rst
  account_cash_deposit/readme/USAGE.rst
  account_cash_deposit/report/report.xml
  account_cash_deposit/report/report_cashdeposit.xml
  account_cash_deposit/security/ir.model.access.csv
  account_cash_deposit/security/security.xml
  account_cash_deposit/static/description/cash_deposit_form.png
  account_cash_deposit/static/description/currency_form_view.png
  account_cash_deposit/static/description/icon.png
  account_cash_deposit/static/description/index.html
  account_cash_deposit/tests/__init__.py
  account_cash_deposit/tests/test_cash_deposit.py
  account_cash_deposit/views/account_cash_deposit.xml
  account_cash_deposit/views/cash_unit.xml
  account_cash_deposit/views/res_currency.xml
  account_cash_deposit/wizards/__init__.py
  account_cash_deposit/wizards/account_cash_order_reception.py
  account_cash_deposit/wizards/account_cash_order_reception_view.xml
  setup/account_cash_deposit/odoo/addons/account_cash_deposit
  setup/account_cash_deposit/setup.py
Labels: bot is merging ⏳

#1544 [13.0][IMP] product_category_tax: prevent write when onchange is triggered
  product_category_tax/models/product_template.py
Labels: approved, bot is merging ⏳

#1491 16.0 mig account_template_active
  account_template_active/README.rst
  account_template_active/__init__.py
  account_template_active/__manifest__.py
  account_template_active/i18n/account_template_active.pot
  account_template_active/i18n/fr.po
  account_template_active/models/__init__.py
  account_template_active/models/account_account_template.py
  account_template_active/models/account_fiscal_position_account_template.py
  account_template_active/models/account_fiscal_position_tax_template.py
  account_template_active/models/account_fiscal_position_template.py
  account_template_active/models/account_tax_template.py
  account_template_active/readme/CONTRIBUTORS.rst
  account_template_active/readme/DESCRIPTION.rst
  account_template_active/readme/USAGE.rst
  account_template_active/static/description/account_account_template_tree.png
  account_template_active/static/description/account_fiscal_position_template_form.png
  account_template_active/static/description/account_tax_template_tree.png
  account_template_active/static/description/icon.png
  account_template_active/static/description/index.html
  account_template_active/tests/__init__.py
  account_template_active/tests/test_module.py
  account_template_active/views/view_account_account_template.xml
  account_template_active/views/view_account_fiscal_position_template.xml
  account_template_active/views/view_account_tax_template.xml
  setup/account_template_active/odoo/addons/account_template_active
  setup/account_template_active/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1559 [16.0][FIX] account_usability : incorrect hierarchy of groups
  account_usability/readme/CONFIGURE.rst
  account_usability/readme/DEVELOP.rst
  account_usability/readme/ROADMAP.rst
  account_usability/security/res_groups.xml
Labels: approved, bot is merging ⏳

#1562 [16.0][FIX] account_move_name_sequence: Not propagate with_prefix parameter
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
Labels: bot is merging ⏳

#1566 [15.0][FIX] account_move_name_sequence: Not propagate with_prefix parameter
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
Labels: bot is merging ⏳

#1565 [16.0][FIX] account_fiscal_position_vat_check: fix view
  account_fiscal_position_vat_check/views/res_partner.xml
Labels: approved, bot is merging ⏳

#1534 [13.0][FIX]account_move_line_sale_info: pick the info directly form sale line ids field
  account_move_line_sale_info/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1570 [14.0][FIX]account_move_line_sale_info: picke info directly form sale line ids field
  account_move_line_sale_info/models/account_move.py
Labels: bot is merging ⏳

#1573 [FIX] account_journal_general_sequence: let non admins delete sequence ranges
  .copier-answers.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
Labels: bot is merging ⏳
