Repository OCA/account-financial-tools, pull requests merged in 2023-07, with the labels that each got.

#1371 [14.0][ADD] account_move_transfer_partner
  account_move_transfer_partner/README.rst
  account_move_transfer_partner/__init__.py
  account_move_transfer_partner/__manifest__.py
  account_move_transfer_partner/readme/CONTRIBUTORS.rst
  account_move_transfer_partner/readme/DESCRIPTION.rst
  account_move_transfer_partner/readme/USAGE.rst
  account_move_transfer_partner/security/ir.model.access.csv
  account_move_transfer_partner/static/description/index.html
  account_move_transfer_partner/tests/__init__.py
  account_move_transfer_partner/tests/test_account_move_transfer_partner.py
  account_move_transfer_partner/wizard/__init__.py
  account_move_transfer_partner/wizard/wizard_account_move_transfer_partner.py
  account_move_transfer_partner/wizard/wizard_account_move_transfer_partner_view.xml
  setup/account_move_transfer_partner/odoo/addons/account_move_transfer_partner
  setup/account_move_transfer_partner/setup.py
Labels: bot is merging ⏳

#1354 [14.0][FIX] account_move_line_sale_info: adjust migration script
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/migrations/14.0.1.0.2/pre-migration.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1356 [14.0][ADD] account_move_line_landed_cost_info
  account_move_line_landed_cost_info/README.rst
  account_move_line_landed_cost_info/__init__.py
  account_move_line_landed_cost_info/__manifest__.py
  account_move_line_landed_cost_info/hooks.py
  account_move_line_landed_cost_info/models/__init__.py
  account_move_line_landed_cost_info/models/account_move.py
  account_move_line_landed_cost_info/models/stock_valuation_adjustment_lines.py
  account_move_line_landed_cost_info/readme/CONTRIBUTORS.rst
  account_move_line_landed_cost_info/readme/DESCRIPTION.rst
  account_move_line_landed_cost_info/readme/USAGE.rst
  account_move_line_landed_cost_info/static/description/icon.png
  account_move_line_landed_cost_info/static/description/index.html
  account_move_line_landed_cost_info/views/account_move_view.xml
  setup/account_move_line_landed_cost_info/odoo/addons/account_move_line_landed_cost_info
  setup/account_move_line_landed_cost_info/setup.py
Labels: needs review, approved, bot is merging ⏳

#1685 [16.0][FIX] account_asset_management - use company from env and not user
  account_asset_management/wizard/wiz_account_asset_report.py
Labels: bot is merging ⏳

#1684 [15.0][FIX] account_asset_management - use company from env and not user
  account_asset_management/wizard/wiz_account_asset_report.py
Labels: bot is merging ⏳

#1683 [14.0][FIX] account_asset_management - use company from env and not user
  account_asset_management/wizard/wiz_account_asset_report.py
Labels: approved, bot is merging ⏳

#1686 [16.0][FIX] account_asset_management: pass for context correct active_id.
  account_asset_management/wizard/wiz_asset_move_reverse.py
Labels: approved, bot is merging ⏳

#1693 [15.0][FIX] account_chart_update: do not repartion in groups + do append False IDS
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1694 [16.0][FIX] account_chart_update: do not repartion in groups + do append False IDs
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1692 [FIX] account_document_reversal: reversal from bank statement lines was not working correctly
  account_document_reversal/models/account_bank_statement.py
  account_document_reversal/models/account_payment.py
  account_document_reversal/tests/test_payment_reversal.py
Labels: approved, bot is merging ⏳

#1350 [13.0][FIX] account_document_reversal: pass active_ids and active_model cor…
  account_document_reversal/models/account_move.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1700 [FIX] base_vat_optional_vies: Fix error installing vatnumber
  base_vat_optional_vies/__manifest__.py
  requirements.txt
Labels: bot is merging ⏳

#1703 [13.0][IMP] account_document_reversal: Exclude cancelled payments from bank reconciliation
  account_document_reversal/models/__init__.py
  account_document_reversal/models/account_bank_statement.py
  account_document_reversal/models/reconciliation_widget.py
  account_document_reversal/tests/test_payment_reversal.py
Labels: bot is merging ⏳
