Repository OCA/account-financial-tools, pull requests merged in 2023-10, with the labels that each got.

#1730 [IMP][14.0]account_loan: add loan lines menu item
  account_loan/__manifest__.py
  account_loan/model/account_loan_line.py
  account_loan/views/account_loan_lines_view.xml
  account_loan/views/account_loan_view.xml
Labels: approved, bot is merging ⏳

#1737 [16.0]account_loan: Porting pr 1728, 1730
  account_loan/__manifest__.py
  account_loan/models/account_loan_line.py
  account_loan/views/account_loan_lines_view.xml
  account_loan/views/account_loan_view.xml
Labels: approved, bot is merging ⏳

#1682 [16.0][IMP] account_asset_management: add asset_profile_id and asset_id on invoice_lines form
  account_asset_management/views/account_move.xml
Labels: bot is merging ⏳

#1734 [16.0][ADD] account_journal_restrict_mode
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  account_journal_restrict_mode/README.rst
  account_journal_restrict_mode/__init__.py
  account_journal_restrict_mode/__manifest__.py
  account_journal_restrict_mode/hooks.py
  account_journal_restrict_mode/models/__init__.py
  account_journal_restrict_mode/models/account_journal.py
  account_journal_restrict_mode/readme/CONTRIBUTORS.rst
  account_journal_restrict_mode/readme/DESCRIPTION.rst
  account_journal_restrict_mode/readme/ROADMAP.rst
  account_journal_restrict_mode/static/description/icon.png
  account_journal_restrict_mode/static/description/index.html
  account_journal_restrict_mode/tests/__init__.py
  account_journal_restrict_mode/tests/test_account_journal_restrict_mode.py
  setup/account_journal_restrict_mode/odoo/addons/account_journal_restrict_mode
  setup/account_journal_restrict_mode/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1741 [14.0][FIX] account_move_line_sale_info: tests: _post -> action_post
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
Labels: approved, bot is merging ⏳

#1460 [15.0][ADD] stock_account_no_auto_reconcile
  setup/stock_account_no_auto_reconcile/odoo/addons/stock_account_no_auto_reconcile
  setup/stock_account_no_auto_reconcile/setup.py
  stock_account_no_auto_reconcile/README.rst
  stock_account_no_auto_reconcile/__init__.py
  stock_account_no_auto_reconcile/__manifest__.py
  stock_account_no_auto_reconcile/models/__init__.py
  stock_account_no_auto_reconcile/models/account_move.py
  stock_account_no_auto_reconcile/models/company.py
  stock_account_no_auto_reconcile/models/res_config_settings.py
  stock_account_no_auto_reconcile/readme/CONTRIBUTORS.rst
  stock_account_no_auto_reconcile/readme/DESCRIPTION.rst
  stock_account_no_auto_reconcile/readme/USAGE.rst
  stock_account_no_auto_reconcile/static/description/index.html
  stock_account_no_auto_reconcile/tests/__init__.py
  stock_account_no_auto_reconcile/tests/test_account_no_auto_reconcile.py
  stock_account_no_auto_reconcile/views/res_config_settings_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1709 [16.0][MIG] account_move_fiscal_month: Migration to 16.0
  account_move_fiscal_month/README.rst
  account_move_fiscal_month/__init__.py
  account_move_fiscal_month/__manifest__.py
  account_move_fiscal_month/i18n/account_move_fiscal_month.pot
  account_move_fiscal_month/i18n/am.po
  account_move_fiscal_month/i18n/ca.po
  account_move_fiscal_month/i18n/de.po
  account_move_fiscal_month/i18n/es.po
  account_move_fiscal_month/i18n/es_EC.po
  account_move_fiscal_month/i18n/fr.po
  account_move_fiscal_month/i18n/gl.po
  account_move_fiscal_month/i18n/hr.po
  account_move_fiscal_month/i18n/hr_HR.po
  account_move_fiscal_month/i18n/it.po
  account_move_fiscal_month/i18n/nl.po
  account_move_fiscal_month/i18n/pt.po
  account_move_fiscal_month/i18n/pt_BR.po
  account_move_fiscal_month/i18n/pt_PT.po
  account_move_fiscal_month/i18n/sl.po
  account_move_fiscal_month/i18n/tr_TR.po
  account_move_fiscal_month/models/__init__.py
  account_move_fiscal_month/models/account_move.py
  account_move_fiscal_month/models/account_move_line.py
  account_move_fiscal_month/readme/CONFIGURE.rst
  account_move_fiscal_month/readme/CONTRIBUTORS.rst
  account_move_fiscal_month/readme/DESCRIPTION.rst
  account_move_fiscal_month/static/description/icon.png
  account_move_fiscal_month/static/description/index.html
  account_move_fiscal_month/tests/__init__.py
  account_move_fiscal_month/tests/test_account_move_fiscal_month.py
  account_move_fiscal_month/views/account_move.xml
  account_move_fiscal_month/views/account_move_line.xml
  setup/account_move_fiscal_month/odoo/addons/account_move_fiscal_month
  setup/account_move_fiscal_month/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1744 [15.0] [IMP] improve tests performance
  account_lock_date_update/tests/test_account_lock_date_update.py
  account_maturity_date_default/tests/test_account_move.py
  account_move_force_removal/tests/test_move.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
Labels: approved, bot is merging ⏳

#1745 [16.0] [IMP] improve tests performance
  account_lock_date_update/tests/test_account_lock_date_update.py
  account_move_line_tax_editable/tests/test_account_move_line_tax_editable.py
Labels: bot is merging ⏳

#1747 [15.0][FIX] account_asset_management: use Reversal Date to Accounting Date of reversal entry
  account_asset_management/wizard/wiz_asset_move_reverse.py
Labels: approved, bot is merging ⏳

#1748 [16.0][FIX] account_asset_management: use Reversal Date to Accounting Date of reversal entry
  account_asset_management/wizard/wiz_asset_move_reverse.py
Labels: bot is merging ⏳

#1750 [16.0][FIX] account_loan: Use the proper tree on the loan view
  account_loan/views/account_loan_lines_view.xml
  account_loan/views/account_loan_view.xml
Labels: bot is merging ⏳

#1749 [14.0][FIX] account_loan: Use the proper tree on the loan view
  account_loan/views/account_loan_lines_view.xml
  account_loan/views/account_loan_view.xml
Labels: bot is merging ⏳

#1742 [FIX] account_move_name_sequence: inverse name
  account_move_name_sequence/models/account_move.py
Labels: bot is merging ⏳

#1658 [16.0][MIG] account_move_budget
  account_move_budget/README.rst
  account_move_budget/__init__.py
  account_move_budget/__manifest__.py
  account_move_budget/i18n/account_move_budget.pot
  account_move_budget/i18n/fr.po
  account_move_budget/models/__init__.py
  account_move_budget/models/account_move_budget.py
  account_move_budget/models/account_move_budget_line.py
  account_move_budget/readme/CONTRIBUTORS.rst
  account_move_budget/readme/DESCRIPTION.rst
  account_move_budget/readme/USAGE.rst
  account_move_budget/security/ir.model.access.csv
  account_move_budget/static/description/icon.png
  account_move_budget/static/description/index.html
  account_move_budget/tests/__init__.py
  account_move_budget/tests/test_account_move_budget.py
  account_move_budget/views/account_move_budget_line_views.xml
  account_move_budget/views/account_move_budget_views.xml
  setup/account_move_budget/odoo/addons/account_move_budget
  setup/account_move_budget/setup.py
Labels: bot is merging ⏳

#1760 [CHG][16.0] account_loan: modifications to work in multi-company context
  account_loan/data/ir_sequence_data.xml
  account_loan/security/account_loan_security.xml
Labels: approved, bot is merging ⏳
