Repository OCA/account-financial-tools, pull requests merged in 2023-02, with the labels that each got.

#1576 [FIX] account_journal_general_sequence: let non admins delete sequence ranges
  account_journal_general_sequence/tests/test_numbering.py
  account_journal_general_sequence/wizards/account_move_renumber_wizard.py
Labels: bot is merging ⏳

#1572 [16.0][MIG] base vat optional vies: Migration to 16.0
  base_vat_optional_vies/README.rst
  base_vat_optional_vies/__init__.py
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/i18n/.gitkeep
  base_vat_optional_vies/i18n/base_vat_optional_vies.pot
  base_vat_optional_vies/i18n/es.po
  base_vat_optional_vies/i18n/hr.po
  base_vat_optional_vies/i18n/pt.po
  base_vat_optional_vies/models/__init__.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONFIGURE.rst
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/readme/DESCRIPTION.rst
  base_vat_optional_vies/readme/USAGE.rst
  base_vat_optional_vies/static/description/icon.png
  base_vat_optional_vies/static/description/index.html
  base_vat_optional_vies/tests/__init__.py
  base_vat_optional_vies/tests/test_res_partner.py
  base_vat_optional_vies/views/res_partner_view.xml
  setup/base_vat_optional_vies/odoo/addons/base_vat_optional_vies
  setup/base_vat_optional_vies/setup.py
Labels: needs review, approved, ready to merge, bot is merging ⏳

#1492 16.0 mig account fiscal year auto create (from 12.0)
  account_fiscal_year_auto_create/README.rst
  account_fiscal_year_auto_create/__init__.py
  account_fiscal_year_auto_create/__manifest__.py
  account_fiscal_year_auto_create/data/ir_cron.xml
  account_fiscal_year_auto_create/i18n/account_fiscal_year_auto_create.pot
  account_fiscal_year_auto_create/i18n/fr.po
  account_fiscal_year_auto_create/models/__init__.py
  account_fiscal_year_auto_create/models/account_fiscal_year.py
  account_fiscal_year_auto_create/readme/CONTRIBUTORS.rst
  account_fiscal_year_auto_create/readme/DESCRIPTION.rst
  account_fiscal_year_auto_create/static/description/icon.png
  account_fiscal_year_auto_create/static/description/index.html
  account_fiscal_year_auto_create/tests/__init__.py
  account_fiscal_year_auto_create/tests/test_module.py
  setup/account_fiscal_year_auto_create/odoo/addons/account_fiscal_year_auto_create
  setup/account_fiscal_year_auto_create/setup.py
Labels: needs review, bot is merging ⏳

#1571 [15.0][FIX]account_move_line_sale_info: picke info directly form sale line ids field
  account_move_line_sale_info/models/account_move.py
Labels: bot is merging ⏳

#1244 [14.0][MIG] account_spread_cost_revenue
  account_spread_cost_revenue/README.rst
  account_spread_cost_revenue/__init__.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/data/spread_cron.xml
  account_spread_cost_revenue/i18n/account_spread_cost_revenue.pot
  account_spread_cost_revenue/i18n/fr.po
  account_spread_cost_revenue/i18n/nl.po
  account_spread_cost_revenue/i18n/pt.po
  account_spread_cost_revenue/models/__init__.py
  account_spread_cost_revenue/models/account_move.py
  account_spread_cost_revenue/models/account_move_line.py
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/models/account_spread_line.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/models/res_company.py
  account_spread_cost_revenue/readme/CONFIGURE.rst
  account_spread_cost_revenue/readme/CONTRIBUTORS.rst
  account_spread_cost_revenue/readme/CREDITS.rst
  account_spread_cost_revenue/readme/DESCRIPTION.rst
  account_spread_cost_revenue/readme/HISTORY.rst
  account_spread_cost_revenue/readme/USAGE.rst
  account_spread_cost_revenue/security/account_spread_security.xml
  account_spread_cost_revenue/security/ir.model.access.csv
  account_spread_cost_revenue/static/description/create_spread.png
  account_spread_cost_revenue/static/description/icon.png
  account_spread_cost_revenue/static/description/index.html
  account_spread_cost_revenue/static/description/invoice_line_1.png
  account_spread_cost_revenue/static/description/invoice_line_2.png
  account_spread_cost_revenue/static/description/spread.png
  account_spread_cost_revenue/static/description/update_spread.png
  account_spread_cost_revenue/static/src/js/account_spread.js
  account_spread_cost_revenue/static/src/scss/account_spread.scss
  account_spread_cost_revenue/templates/assets.xml
  account_spread_cost_revenue/tests/__init__.py
  account_spread_cost_revenue/tests/test_account_invoice_auto_spread.py
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
  account_spread_cost_revenue/tests/test_account_spread_cost_revenue.py
  account_spread_cost_revenue/tests/test_compute_spread_board.py
  account_spread_cost_revenue/views/account_move.xml
  account_spread_cost_revenue/views/account_spread.xml
  account_spread_cost_revenue/views/account_spread_template.xml
  account_spread_cost_revenue/views/res_company.xml
  account_spread_cost_revenue/wizards/__init__.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.xml
  setup/account_spread_cost_revenue/odoo/addons/account_spread_cost_revenue
  setup/account_spread_cost_revenue/setup.py
Labels: needs review, bot is merging ⏳

#1579 [14.0][FIX] account_loan, account_loan_line & account_loan_generate_entries: fix read
  account_loan/model/account_loan.py
  account_loan/model/account_loan_line.py
  account_loan/wizard/account_loan_generate_entries.py
Labels: bot is merging ⏳

#1528 [15.0][MIG] account_asset_low_value
  account_asset_low_value/README.rst
  account_asset_low_value/__init__.py
  account_asset_low_value/__manifest__.py
  account_asset_low_value/i18n/account_asset_low_value.pot
  account_asset_low_value/models/__init__.py
  account_asset_low_value/models/account_asset.py
  account_asset_low_value/readme/CONTRIBUTORS.rst
  account_asset_low_value/readme/DESCRIPTION.rst
  account_asset_low_value/static/description/icon.png
  account_asset_low_value/static/description/index.html
  account_asset_low_value/tests/__init__.py
  account_asset_low_value/tests/test_asset_low_value.py
  account_asset_low_value/views/account_asset_views.xml
  account_asset_low_value/wizard/__init__.py
  account_asset_low_value/wizard/account_asset_remove.py
  account_asset_low_value/wizard/account_asset_remove.xml
  setup/account_asset_low_value/odoo/addons/account_asset_low_value
  setup/account_asset_low_value/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1578 [14.0][FIX] account_asset_management: use Reversal Date to Accounting Date of reversal entry
  account_asset_management/wizard/wiz_asset_move_reverse.py
Labels: approved, bot is merging ⏳

#1519 [15.0][MIG] account_asset_number
  account_asset_number/README.rst
  account_asset_number/__init__.py
  account_asset_number/__manifest__.py
  account_asset_number/i18n/account_asset_number.pot
  account_asset_number/i18n/hr.po
  account_asset_number/models/__init__.py
  account_asset_number/models/account_asset.py
  account_asset_number/models/account_asset_profile.py
  account_asset_number/readme/CONFIGURE.rst
  account_asset_number/readme/CONTRIBUTORS.rst
  account_asset_number/readme/DESCRIPTION.rst
  account_asset_number/report/__init__.py
  account_asset_number/report/account_asset_number_report.xml
  account_asset_number/report/account_asset_report_xls.py
  account_asset_number/static/description/icon.png
  account_asset_number/static/description/index.html
  account_asset_number/tests/__init__.py
  account_asset_number/tests/test_account_asset_number.py
  account_asset_number/views/account_asset.xml
  account_asset_number/views/account_asset_profile.xml
  setup/account_asset_number/odoo/addons/account_asset_number
  setup/account_asset_number/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1582 [14.0][FIX] account_financial_tools: fix read
  account_netting/wizards/account_move_make_netting.py
Labels: bot is merging ⏳

#1422 [15.0] [MIG] account_move_fiscal_year
  account_move_fiscal_year/README.rst
  account_move_fiscal_year/__init__.py
  account_move_fiscal_year/__manifest__.py
  account_move_fiscal_year/i18n/account_move_fiscal_year.pot
  account_move_fiscal_year/i18n/am.po
  account_move_fiscal_year/i18n/ar.po
  account_move_fiscal_year/i18n/ca.po
  account_move_fiscal_year/i18n/de.po
  account_move_fiscal_year/i18n/es.po
  account_move_fiscal_year/i18n/es_CO.po
  account_move_fiscal_year/i18n/es_EC.po
  account_move_fiscal_year/i18n/fr.po
  account_move_fiscal_year/i18n/fr_FR.po
  account_move_fiscal_year/i18n/gl.po
  account_move_fiscal_year/i18n/hr.po
  account_move_fiscal_year/i18n/hr_HR.po
  account_move_fiscal_year/i18n/it.po
  account_move_fiscal_year/i18n/nl.po
  account_move_fiscal_year/i18n/pt.po
  account_move_fiscal_year/i18n/pt_BR.po
  account_move_fiscal_year/i18n/pt_PT.po
  account_move_fiscal_year/i18n/sl.po
  account_move_fiscal_year/i18n/tr_TR.po
  account_move_fiscal_year/models/__init__.py
  account_move_fiscal_year/models/account_move.py
  account_move_fiscal_year/models/account_move_line.py
  account_move_fiscal_year/models/res_company.py
  account_move_fiscal_year/readme/CONTRIBUTORS.rst
  account_move_fiscal_year/readme/DESCRIPTION.rst
  account_move_fiscal_year/readme/INSTALL.rst
  account_move_fiscal_year/readme/USAGE.rst
  account_move_fiscal_year/static/description/icon.png
  account_move_fiscal_year/static/description/index.html
  account_move_fiscal_year/tests/__init__.py
  account_move_fiscal_year/tests/test_account_move_fiscal_year.py
  account_move_fiscal_year/views/account_move.xml
  account_move_fiscal_year/views/account_move_line.xml
  setup/account_move_fiscal_year/odoo/addons/account_move_fiscal_year
  setup/account_move_fiscal_year/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1585 [IMP] account_menu: Show Account move lines on Partner
  account_usability/__manifest__.py
  account_usability/views/view_account_move_line.xml
Labels: bot is merging ⏳

#1234 [14.0][ADD] account_asset_compute_batch
  account_asset_compute_batch/__init__.py
  account_asset_compute_batch/__manifest__.py
  account_asset_compute_batch/data/service_cron.xml
  account_asset_compute_batch/models/__init__.py
  account_asset_compute_batch/models/account_asset.py
  account_asset_compute_batch/models/account_asset_compute_batch.py
  account_asset_compute_batch/models/account_asset_line.py
  account_asset_compute_batch/models/account_move.py
  account_asset_compute_batch/readme/CONTRIBUTORS.rst
  account_asset_compute_batch/readme/DESCRIPTION.rst
  account_asset_compute_batch/readme/USAGE.rst
  account_asset_compute_batch/security/account_asset_security.xml
  account_asset_compute_batch/security/ir.model.access.csv
  account_asset_compute_batch/static/description/icon.png
  account_asset_compute_batch/tests/__init__.py
  account_asset_compute_batch/tests/test_account_asset_compute_batch.py
  account_asset_compute_batch/views/account_asset_compute_batch.xml
  account_asset_compute_batch/wizard/__init__.py
  account_asset_compute_batch/wizard/account_asset_compute.py
  account_asset_compute_batch/wizard/account_asset_compute.xml
  account_asset_management/models/account_asset.py
  setup/account_asset_compute_batch/odoo/addons/account_asset_compute_batch
  setup/account_asset_compute_batch/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1119 [13.0][ADD] account_move_line_residual: New module to add residual amount on journal items
  account_move_line_residual/README.rst
  account_move_line_residual/__init__.py
  account_move_line_residual/__manifest__.py
  account_move_line_residual/i18n/account_move_line_residual.pot
  account_move_line_residual/i18n/es.po
  account_move_line_residual/readme/CONTRIBUTORS.rst
  account_move_line_residual/readme/DESCRIPTION.rst
  account_move_line_residual/readme/USAGE.rst
  account_move_line_residual/static/description/icon.png
  account_move_line_residual/static/description/index.html
  account_move_line_residual/views/account_move_line_view.xml
  setup/account_move_line_residual/odoo/addons/account_move_line_residual
  setup/account_move_line_residual/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1596 [FIX] account_usability: add to view required field
  account_usability/views/view_account_chart_template.xml
Labels: bot is merging ⏳

#1595 [15.0][MIG] account_move_line_residual: Migration to version 15.0
  account_move_line_residual/README.rst
  account_move_line_residual/__init__.py
  account_move_line_residual/__manifest__.py
  account_move_line_residual/i18n/account_move_line_residual.pot
  account_move_line_residual/i18n/es.po
  account_move_line_residual/readme/CONTRIBUTORS.rst
  account_move_line_residual/readme/DESCRIPTION.rst
  account_move_line_residual/readme/USAGE.rst
  account_move_line_residual/static/description/icon.png
  account_move_line_residual/static/description/index.html
  account_move_line_residual/views/account_move_line_view.xml
  setup/account_move_line_residual/odoo/addons/account_move_line_residual
  setup/account_move_line_residual/setup.py
Labels: needs review, approved, bot is merging ⏳
