Repository OCA/account-financial-tools, pull requests merged in 2023-12, with the labels that each got.

#1788 [FIX] account_asset_management: Display significant information about the error
  account_asset_management/models/account_asset.py
Labels: approved, bot is merging ⏳

#1780 [17.0][MIG] account_move_print: Migration to 17.0
  account_move_print/README.rst
  account_move_print/__init__.py
  account_move_print/__manifest__.py
  account_move_print/i18n/account_move_print.pot
  account_move_print/i18n/es.po
  account_move_print/i18n/hr.po
  account_move_print/i18n/tr.po
  account_move_print/pyproject.toml
  account_move_print/readme/CONTRIBUTORS.md
  account_move_print/readme/DESCRIPTION.md
  account_move_print/readme/USAGE.md
  account_move_print/report/journal_report.xml
  account_move_print/static/description/icon.png
  account_move_print/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1355 [14.0][FIX] account_move_line_purchase_info: migration and init hook
  account_move_line_purchase_info/__init__.py
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/hooks.py
  account_move_line_purchase_info/migrations/14.0.1.0.3/pre-migration.py
Labels: bot is merging ⏳, stale
