Repository OCA/account-financial-tools, pull requests merged in 2023-08, with the labels that each got.

#1404 [MIG] account_asset_batch_compute: Migration to 15.0
  account_asset_batch_compute/README.rst
  account_asset_batch_compute/__init__.py
  account_asset_batch_compute/__manifest__.py
  account_asset_batch_compute/data/queue_data.xml
  account_asset_batch_compute/i18n/account_asset_batch_compute.pot
  account_asset_batch_compute/models/__init__.py
  account_asset_batch_compute/models/account_asset.py
  account_asset_batch_compute/readme/CONTRIBUTORS.rst
  account_asset_batch_compute/readme/DESCRIPTION.rst
  account_asset_batch_compute/static/description/icon.svg
  account_asset_batch_compute/static/description/index.html
  account_asset_batch_compute/tests/__init__.py
  account_asset_batch_compute/tests/test_account_asset_batch_compute.py
  account_asset_batch_compute/wizards/__init__.py
  account_asset_batch_compute/wizards/account_asset_compute.py
  account_asset_batch_compute/wizards/account_asset_compute_views.xml
  setup/account_asset_batch_compute/odoo/addons/account_asset_batch_compute
  setup/account_asset_batch_compute/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1691 [15.0][IMP] account_chart_update: Update account groups too
  account_chart_update/security/ir.model.access.csv
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
  account_chart_update/wizard/wizard_chart_update_view.xml
Labels: bot is merging ⏳

#1707 [16.0][IMP] account_chart_update: Update account groups too
  account_chart_update/security/ir.model.access.csv
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
  account_chart_update/wizard/wizard_chart_update_view.xml
Labels: bot is merging ⏳

#1688 [14.0][IMP] field vies_passed is synced from parent to childs
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/models/__init__.py
  base_vat_optional_vies/models/res_config_settings.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/tests/__init__.py
  base_vat_optional_vies/tests/test_config_settings.py
  base_vat_optional_vies/tests/test_res_partner.py
  base_vat_optional_vies/views/res_config_settings_views.xml
  requirements.txt
Labels: needs review, approved, bot is merging ⏳

#1706 [16.0][FIX][account_chart_update] Remove account tax browsing since already a recordset
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1711 [16.0][MIG] account_move_line_sale_info: Migration to 16.0
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/i18n/es_AR.po
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/readme/CONTRIBUTORS.rst
  account_move_line_sale_info/readme/DESCRIPTION.rst
  account_move_line_sale_info/readme/USAGE.rst
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/static/description/index.html
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
  setup/account_move_line_sale_info/odoo/addons/account_move_line_sale_info
  setup/account_move_line_sale_info/setup.py
Labels: approved, bot is merging ⏳

#1713 [15.0][FIX+IMP] account_chart_update: Don't depend on l10n_generic_coa + TransactionCase
  account_chart_update/__manifest__.py
  account_chart_update/tests/test_account_chart_update.py
Labels: bot is merging ⏳

#1714 [16.0][FIX+IMP] account_chart_update: Don't depend on l10n_generic_coa + TransactionCase
  account_chart_update/__manifest__.py
  account_chart_update/tests/test_account_chart_update.py
Labels: bot is merging ⏳

#1716 [15.0][IMP] base_vat_optional_vies: vies sync in children contact
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/models/__init__.py
  base_vat_optional_vies/models/res_config_settings.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/tests/tes_config_settings.py
  base_vat_optional_vies/tests/test_res_partner.py
  base_vat_optional_vies/views/res_config_settings_view.xml
Labels: bot is merging ⏳

#1717 [15.0][FIX] account_move_template: Make test resilient
  account_move_template/tests/test_account_move_template_options.py
Labels: approved, bot is merging ⏳

#1718 [16.0][FIX] account_move_name_sequence: do not create duplicated sequences
  account_move_name_sequence/models/account_journal.py
Labels: bot is merging ⏳

#1719 [15.0][FIX] account_move_name_sequence: do not create duplicated sequences
  account_move_name_sequence/models/account_journal.py
Labels: bot is merging ⏳
