Repository OCA/account-financial-tools, pull requests merged in 2024-05, with the labels that each got.

#1871 [14.0][BCK] account_asset_management: KeyError
  account_asset_management/models/account_move.py
Labels: bot is merging ⏳

#1287 [14.0][ADD] account_move_default_journal: A module to have more meaningful …
  account_move_default_journal/README.rst
  account_move_default_journal/__init__.py
  account_move_default_journal/__manifest__.py
  account_move_default_journal/models/__init__.py
  account_move_default_journal/models/account_config_settings.py
  account_move_default_journal/models/account_move.py
  account_move_default_journal/models/res_company.py
  account_move_default_journal/readme/CONTRIBUTORS.rst
  account_move_default_journal/readme/DESCRIPTION.rst
  account_move_default_journal/static/description/index.html
  account_move_default_journal/tests/__init__.py
  account_move_default_journal/tests/test_defaults.py
  account_move_default_journal/views/account_config_settings.xml
  account_move_default_journal/views/res_company_views.xml
  setup/account_move_default_journal/odoo/addons/account_move_default_journal
  setup/account_move_default_journal/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1850 [12.0][FIX] account_asset_management: asset report multicompany
  account_asset_management/security/account_asset_security.xml
Labels: approved, ready to merge, bot is merging ⏳

#1873 [17.0][MIG] account_account_tag_code: Migration to 17.0
  account_account_tag_code/README.rst
  account_account_tag_code/__init__.py
  account_account_tag_code/__manifest__.py
  account_account_tag_code/i18n/account_account_tag_code.pot
  account_account_tag_code/i18n/es.po
  account_account_tag_code/i18n/it.po
  account_account_tag_code/models/__init__.py
  account_account_tag_code/models/account_account_tag.py
  account_account_tag_code/pyproject.toml
  account_account_tag_code/readme/CONTRIBUTORS.md
  account_account_tag_code/readme/DESCRIPTION.md
  account_account_tag_code/static/description/icon.png
  account_account_tag_code/static/description/index.html
  account_account_tag_code/tests/__init__.py
  account_account_tag_code/tests/test_account_tag_display_name.py
  account_account_tag_code/views/account_account_tag_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1874 [17.0][MIG] account_spread_cost_revenue: Migration to 17.0
  account_spread_cost_revenue/README.rst
  account_spread_cost_revenue/__init__.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/data/spread_cron.xml
  account_spread_cost_revenue/i18n/account_spread_cost_revenue.pot
  account_spread_cost_revenue/i18n/fr.po
  account_spread_cost_revenue/i18n/it.po
  account_spread_cost_revenue/i18n/nl.po
  account_spread_cost_revenue/i18n/pt.po
  account_spread_cost_revenue/models/__init__.py
  account_spread_cost_revenue/models/account_move.py
  account_spread_cost_revenue/models/account_move_line.py
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/models/account_spread_line.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/models/res_company.py
  account_spread_cost_revenue/pyproject.toml
  account_spread_cost_revenue/readme/CONFIGURE.md
  account_spread_cost_revenue/readme/CONTRIBUTORS.md
  account_spread_cost_revenue/readme/CREDITS.md
  account_spread_cost_revenue/readme/DESCRIPTION.md
  account_spread_cost_revenue/readme/HISTORY.md
  account_spread_cost_revenue/readme/USAGE.md
  account_spread_cost_revenue/security/account_spread_security.xml
  account_spread_cost_revenue/security/ir.model.access.csv
  account_spread_cost_revenue/static/description/create_spread.png
  account_spread_cost_revenue/static/description/icon.png
  account_spread_cost_revenue/static/description/index.html
  account_spread_cost_revenue/static/description/invoice_line_1.png
  account_spread_cost_revenue/static/description/invoice_line_2.png
  account_spread_cost_revenue/static/description/spread.png
  account_spread_cost_revenue/static/description/update_spread.png
  account_spread_cost_revenue/tests/__init__.py
  account_spread_cost_revenue/tests/test_account_invoice_auto_spread.py
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
  account_spread_cost_revenue/tests/test_account_spread_cost_revenue.py
  account_spread_cost_revenue/tests/test_compute_spread_board.py
  account_spread_cost_revenue/views/account_move.xml
  account_spread_cost_revenue/views/account_spread.xml
  account_spread_cost_revenue/views/account_spread_template.xml
  account_spread_cost_revenue/views/res_company.xml
  account_spread_cost_revenue/wizards/__init__.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.xml
Labels: approved, ready to merge, bot is merging ⏳

#1887 [16.0][IMP] account_move_template: Company compatibility in tests
  account_move_template/tests/test_account_move_template_options.py
Labels: bot is merging ⏳

#1885 [17.0][MIG] account_move_post_date_user: Migration to 17.0
  account_move_post_date_user/README.rst
  account_move_post_date_user/__init__.py
  account_move_post_date_user/__manifest__.py
  account_move_post_date_user/i18n/account_move_post_date_user.pot
  account_move_post_date_user/i18n/it.po
  account_move_post_date_user/models/__init__.py
  account_move_post_date_user/models/account_move.py
  account_move_post_date_user/pyproject.toml
  account_move_post_date_user/readme/CONTRIBUTORS.md
  account_move_post_date_user/readme/DESCRIPTION.md
  account_move_post_date_user/static/description/icon.png
  account_move_post_date_user/static/description/index.html
  account_move_post_date_user/tests/__init__.py
  account_move_post_date_user/tests/test_account_move_post_date_user.py
  account_move_post_date_user/views/account_move.xml
Labels: approved, bot is merging ⏳

#1664 [16.0][FIX] account_asset_management: create refund invoices with assets
  account_asset_management/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳
