Repository OCA/account-financial-tools, pull requests merged in 2024-03, with the labels that each got.

#1590 [15.0][MIG] account_asset_compute_batch
  account_asset_compute_batch/README.rst
  account_asset_compute_batch/__init__.py
  account_asset_compute_batch/__manifest__.py
  account_asset_compute_batch/data/service_cron.xml
  account_asset_compute_batch/i18n/account_asset_compute_batch.pot
  account_asset_compute_batch/models/__init__.py
  account_asset_compute_batch/models/account_asset.py
  account_asset_compute_batch/models/account_asset_compute_batch.py
  account_asset_compute_batch/models/account_asset_line.py
  account_asset_compute_batch/models/account_move.py
  account_asset_compute_batch/readme/CONTRIBUTORS.rst
  account_asset_compute_batch/readme/DESCRIPTION.rst
  account_asset_compute_batch/readme/USAGE.rst
  account_asset_compute_batch/security/account_asset_security.xml
  account_asset_compute_batch/security/ir.model.access.csv
  account_asset_compute_batch/static/description/icon.png
  account_asset_compute_batch/static/description/index.html
  account_asset_compute_batch/tests/__init__.py
  account_asset_compute_batch/tests/test_account_asset_compute_batch.py
  account_asset_compute_batch/views/account_asset_compute_batch.xml
  account_asset_compute_batch/wizard/__init__.py
  account_asset_compute_batch/wizard/account_asset_compute.py
  account_asset_compute_batch/wizard/account_asset_compute.xml
  account_asset_management/models/account_asset.py
  setup/account_asset_compute_batch/odoo/addons/account_asset_compute_batch
  setup/account_asset_compute_batch/setup.py
Labels: approved, bot is merging ⏳

#1740 [16.0][MIG] account_spread_cost_revenue
  account_spread_cost_revenue/README.rst
  account_spread_cost_revenue/__init__.py
  account_spread_cost_revenue/__manifest__.py
  account_spread_cost_revenue/data/spread_cron.xml
  account_spread_cost_revenue/i18n/account_spread_cost_revenue.pot
  account_spread_cost_revenue/i18n/fr.po
  account_spread_cost_revenue/i18n/nl.po
  account_spread_cost_revenue/i18n/pt.po
  account_spread_cost_revenue/models/__init__.py
  account_spread_cost_revenue/models/account_move.py
  account_spread_cost_revenue/models/account_move_line.py
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/models/account_spread_line.py
  account_spread_cost_revenue/models/account_spread_template.py
  account_spread_cost_revenue/models/res_company.py
  account_spread_cost_revenue/readme/CONFIGURE.rst
  account_spread_cost_revenue/readme/CONTRIBUTORS.rst
  account_spread_cost_revenue/readme/CREDITS.rst
  account_spread_cost_revenue/readme/DESCRIPTION.rst
  account_spread_cost_revenue/readme/HISTORY.rst
  account_spread_cost_revenue/readme/USAGE.rst
  account_spread_cost_revenue/security/account_spread_security.xml
  account_spread_cost_revenue/security/ir.model.access.csv
  account_spread_cost_revenue/static/description/create_spread.png
  account_spread_cost_revenue/static/description/icon.png
  account_spread_cost_revenue/static/description/index.html
  account_spread_cost_revenue/static/description/invoice_line_1.png
  account_spread_cost_revenue/static/description/invoice_line_2.png
  account_spread_cost_revenue/static/description/spread.png
  account_spread_cost_revenue/static/description/update_spread.png
  account_spread_cost_revenue/tests/__init__.py
  account_spread_cost_revenue/tests/test_account_invoice_auto_spread.py
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
  account_spread_cost_revenue/tests/test_account_spread_cost_revenue.py
  account_spread_cost_revenue/tests/test_compute_spread_board.py
  account_spread_cost_revenue/views/account_move.xml
  account_spread_cost_revenue/views/account_spread.xml
  account_spread_cost_revenue/views/account_spread_template.xml
  account_spread_cost_revenue/views/res_company.xml
  account_spread_cost_revenue/wizards/__init__.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.py
  account_spread_cost_revenue/wizards/account_spread_invoice_line_link_wizard.xml
  setup/account_spread_cost_revenue/odoo/addons/account_spread_cost_revenue
  setup/account_spread_cost_revenue/setup.py
Labels: approved, bot is merging ⏳

#1790 [16.0][FIX] account_asset_management: Display significant information about the error
  account_asset_management/models/account_asset.py
Labels: approved, bot is merging ⏳

#1822 [16.0][ADD] account_move_post_date_user
  account_move_post_date_user/README.rst
  account_move_post_date_user/__init__.py
  account_move_post_date_user/__manifest__.py
  account_move_post_date_user/models/__init__.py
  account_move_post_date_user/models/account_move.py
  account_move_post_date_user/readme/CONTRIBUTORS.rst
  account_move_post_date_user/readme/DESCRIPTION.rst
  account_move_post_date_user/static/description/icon.png
  account_move_post_date_user/static/description/index.html
  account_move_post_date_user/tests/__init__.py
  account_move_post_date_user/tests/test_account_move_post_date_user.py
  account_move_post_date_user/views/account_move.xml
  setup/account_move_post_date_user/odoo/addons/account_move_post_date_user
  setup/account_move_post_date_user/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1829 [14.0][FIX] account_cash_deposit: fix qweb report generation
  account_cash_deposit/report/report_cashdeposit.xml
Labels: bot is merging ⏳

#1826 [17.0][MIG] account_tax_repartition_line_tax_group_account
  account_tax_repartition_line_tax_group_account/README.rst
  account_tax_repartition_line_tax_group_account/__init__.py
  account_tax_repartition_line_tax_group_account/__manifest__.py
  account_tax_repartition_line_tax_group_account/i18n/account_tax_repartition_line_tax_group_account.pot
  account_tax_repartition_line_tax_group_account/models/__init__.py
  account_tax_repartition_line_tax_group_account/models/account_tax_group.py
  account_tax_repartition_line_tax_group_account/models/account_tax_repartition_line.py
  account_tax_repartition_line_tax_group_account/pyproject.toml
  account_tax_repartition_line_tax_group_account/readme/CONFIGURE.md
  account_tax_repartition_line_tax_group_account/readme/CONTRIBUTORS.md
  account_tax_repartition_line_tax_group_account/readme/DESCRIPTION.md
  account_tax_repartition_line_tax_group_account/readme/USAGE.md
  account_tax_repartition_line_tax_group_account/static/description/icon.png
  account_tax_repartition_line_tax_group_account/static/description/index.html
  account_tax_repartition_line_tax_group_account/tests/__init__.py
  account_tax_repartition_line_tax_group_account/tests/test_account_tax_repartition_line_tax_group_account.py
  account_tax_repartition_line_tax_group_account/views/account_tax_group_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#1828 [16.0][FIX] account_spread_cost_revenue, invalid reconcile case invoice_line_ids > 1
  account_spread_cost_revenue/models/account_spread.py
Labels: approved, ready to merge, bot is merging ⏳

#1840 [FIX] account_journal_general_sequence: provide defaults for sorting
  account_journal_general_sequence/models/account_move.py
Labels: bot is merging ⏳

#1842 [15.0][FWP][IMP] product_category_tax: prevent write when onchange is triggered
  product_category_tax/models/product_template.py
Labels: approved, bot is merging ⏳

#1777 [17.0][MIG] account_move_name_sequence: Migration to 17.0
  account_move_name_sequence/README.rst
  account_move_name_sequence/__init__.py
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/hooks.py
  account_move_name_sequence/i18n/account_move_name_sequence.pot
  account_move_name_sequence/i18n/ar.po
  account_move_name_sequence/i18n/es.po
  account_move_name_sequence/i18n/fr.po
  account_move_name_sequence/i18n/hr.po
  account_move_name_sequence/models/__init__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/pyproject.toml
  account_move_name_sequence/readme/CONFIGURE.md
  account_move_name_sequence/readme/CONTRIBUTORS.md
  account_move_name_sequence/readme/DESCRIPTION.md
  account_move_name_sequence/security/ir.model.access.csv
  account_move_name_sequence/static/description/icon.png
  account_move_name_sequence/static/description/index.html
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
  account_move_name_sequence/views/account_journal.xml
  account_move_name_sequence/views/account_move.xml
Labels: approved, ready to merge, bot is merging ⏳
