Repository OCA/account-financial-tools, pull requests merged in 2024-12, with the labels that each got.

#1975 [IMP] Refactore to add hooks in order to add infos in vals
  account_loan/models/account_loan_line.py
Labels: approved, ready to merge, bot is merging ⏳

#1978 [FIX] [16.0] account_chart_update: Write Chart Template on Company only when changes
  account_chart_update/wizard/wizard_chart_update.py
Labels: needs review, approved, bot is merging ⏳

#1823 [16.0][FIX] account_asset_management: Set the default date from and date to for Financial Assets report wizard
  account_asset_management/wizard/wiz_account_asset_report.xml
Labels: bot is merging ⏳

#1997 [16.0][FIX] account_invoice_constraint_chronology - fix unit test
  account_invoice_constraint_chronology/tests/test_account_invoice_constraint_chronology.py
Labels: bot is merging ⏳

#1996 [16.0][FIX] account_asset_management: fix asset report
  account_asset_management/report/account_asset_report_xls.py
Labels: bot is merging ⏳

#1991 [18.0][MIG] account_journal_restrict_mode: Migration to 18.0
  account_journal_restrict_mode/README.rst
  account_journal_restrict_mode/__init__.py
  account_journal_restrict_mode/__manifest__.py
  account_journal_restrict_mode/hooks.py
  account_journal_restrict_mode/i18n/account_journal_restrict_mode.pot
  account_journal_restrict_mode/i18n/es.po
  account_journal_restrict_mode/i18n/it.po
  account_journal_restrict_mode/models/__init__.py
  account_journal_restrict_mode/models/account_journal.py
  account_journal_restrict_mode/pyproject.toml
  account_journal_restrict_mode/readme/CONTRIBUTORS.md
  account_journal_restrict_mode/readme/DESCRIPTION.md
  account_journal_restrict_mode/readme/ROADMAP.md
  account_journal_restrict_mode/static/description/icon.png
  account_journal_restrict_mode/static/description/index.html
  account_journal_restrict_mode/tests/__init__.py
  account_journal_restrict_mode/tests/test_account_journal_restrict_mode.py
Labels: approved, ready to merge, bot is merging ⏳

#1993 [18.0][MIG] account_move_post_date_user
  account_move_post_date_user/README.rst
  account_move_post_date_user/__init__.py
  account_move_post_date_user/__manifest__.py
  account_move_post_date_user/i18n/account_move_post_date_user.pot
  account_move_post_date_user/i18n/it.po
  account_move_post_date_user/models/__init__.py
  account_move_post_date_user/models/account_move.py
  account_move_post_date_user/pyproject.toml
  account_move_post_date_user/readme/CONTRIBUTORS.md
  account_move_post_date_user/readme/DESCRIPTION.md
  account_move_post_date_user/static/description/icon.png
  account_move_post_date_user/static/description/index.html
  account_move_post_date_user/tests/__init__.py
  account_move_post_date_user/tests/test_account_move_post_date_user.py
  account_move_post_date_user/views/account_move.xml
Labels: approved, bot is merging ⏳
