Repository OCA/account-financial-tools, pull requests merged in 2024-08, with the labels that each got.

#1791 [16.0][ADD] stock_account_anglo_saxon_cogs_kit
  setup/stock_account_anglo_saxon_cogs_kit/odoo/addons/stock_account_anglo_saxon_cogs_kit
  setup/stock_account_anglo_saxon_cogs_kit/setup.py
  stock_account_anglo_saxon_cogs_kit/README.rst
  stock_account_anglo_saxon_cogs_kit/__init__.py
  stock_account_anglo_saxon_cogs_kit/__manifest__.py
  stock_account_anglo_saxon_cogs_kit/models/__init__.py
  stock_account_anglo_saxon_cogs_kit/models/account_move_line.py
  stock_account_anglo_saxon_cogs_kit/readme/CONTRIBUTORS.rst
  stock_account_anglo_saxon_cogs_kit/readme/DESCRIPTION.rst
  stock_account_anglo_saxon_cogs_kit/static/description/index.html
  stock_account_anglo_saxon_cogs_kit/tests/__init__.py
  stock_account_anglo_saxon_cogs_kit/tests/test_stock_account_anglo_saxon_cogs_kit.py
Labels: approved, ready to merge, bot is merging ⏳

#1506 [16.0][IMP] account_fiscal_year add fields on res.company
  account_fiscal_year/__manifest__.py
  account_fiscal_year/i18n/account_fiscal_year.pot
  account_fiscal_year/i18n/fr.po
  account_fiscal_year/models/account_fiscal_year.py
  account_fiscal_year/models/res_company.py
  account_fiscal_year/readme/DESCRIPTION.rst
  account_fiscal_year/static/description/account_fiscal_year_form.png
  account_fiscal_year/static/description/res_company_tree.png
  account_fiscal_year/views/res_company_views.xml
Labels: needs review, bot is merging ⏳, stale

#1924 [FW][17.0][IMP] account_fiscal_year add fields on res.company
  account_fiscal_year/__manifest__.py
  account_fiscal_year/i18n/account_fiscal_year.pot
  account_fiscal_year/i18n/fr.po
  account_fiscal_year/models/account_fiscal_year.py
  account_fiscal_year/models/res_company.py
  account_fiscal_year/readme/DESCRIPTION.md
  account_fiscal_year/static/description/account_fiscal_year_form.png
  account_fiscal_year/static/description/res_company_tree.png
  account_fiscal_year/views/res_company_views.xml
Labels: needs review, approved, bot is merging ⏳

#1881 [ADD] [17.0] mail_template_substitute_account_move
  mail_template_substitute_account_move/README.rst
  mail_template_substitute_account_move/__init__.py
  mail_template_substitute_account_move/__manifest__.py
  mail_template_substitute_account_move/models/__init__.py
  mail_template_substitute_account_move/models/account_move.py
  mail_template_substitute_account_move/pyproject.toml
  mail_template_substitute_account_move/readme/CONTRIBUTORS.md
  mail_template_substitute_account_move/readme/DESCRIPTION.md
  mail_template_substitute_account_move/readme/ROADMAP.md
  mail_template_substitute_account_move/readme/USAGE.md
  mail_template_substitute_account_move/static/description/icon.png
  mail_template_substitute_account_move/static/description/icon.svg
  mail_template_substitute_account_move/static/description/index.html
  mail_template_substitute_account_move/tests/__init__.py
  mail_template_substitute_account_move/tests/test_mail_template_substitute_account_move.py
Labels: approved, ready to merge, bot is merging ⏳
