Repository OCA/account-financial-tools, pull requests merged in 2024-06, with the labels that each got.

#1830 [MIG] [17.0] account_partner_required migration to 17.0
  account_partner_required/README.rst
  account_partner_required/__init__.py
  account_partner_required/__manifest__.py
  account_partner_required/i18n/account_partner_required.pot
  account_partner_required/i18n/ar.po
  account_partner_required/i18n/bs.po
  account_partner_required/i18n/cs.po
  account_partner_required/i18n/de.po
  account_partner_required/i18n/en_GB.po
  account_partner_required/i18n/es.po
  account_partner_required/i18n/es_CR.po
  account_partner_required/i18n/es_EC.po
  account_partner_required/i18n/es_MX.po
  account_partner_required/i18n/fr.po
  account_partner_required/i18n/hr.po
  account_partner_required/i18n/hu.po
  account_partner_required/i18n/it.po
  account_partner_required/i18n/ja.po
  account_partner_required/i18n/lt.po
  account_partner_required/i18n/mk.po
  account_partner_required/i18n/mn.po
  account_partner_required/i18n/nb.po
  account_partner_required/i18n/nl.po
  account_partner_required/i18n/nl_BE.po
  account_partner_required/i18n/nl_NL.po
  account_partner_required/i18n/pt.po
  account_partner_required/i18n/pt_BR.po
  account_partner_required/i18n/ro.po
  account_partner_required/i18n/ru.po
  account_partner_required/i18n/sl.po
  account_partner_required/i18n/sv.po
  account_partner_required/i18n/tr.po
  account_partner_required/i18n/tr_TR.po
  account_partner_required/i18n/zh_CN.po
  account_partner_required/i18n/zh_TW.po
  account_partner_required/models/__init__.py
  account_partner_required/models/account_account.py
  account_partner_required/models/account_move_line.py
  account_partner_required/pyproject.toml
  account_partner_required/readme/CONFIGURE.md
  account_partner_required/readme/CONTRIBUTORS.md
  account_partner_required/readme/DESCRIPTION.md
  account_partner_required/readme/USAGE.md
  account_partner_required/static/description/icon.png
  account_partner_required/static/description/index.html
  account_partner_required/tests/__init__.py
  account_partner_required/tests/test_account_partner_required.py
  account_partner_required/views/account_account.xml
Labels: approved, ready to merge, bot is merging ⏳

#1884 [14.0][FIX] account_loan: account.loan.pay.amount, crud permission to group_account_manager
  account_loan/README.rst
  account_loan/readme/CONTRIBUTORS.rst
  account_loan/security/ir.model.access.csv
  account_loan/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1756 [16.0][MIG] account_move_line_repair_info: Migration to 16.0.
  account_move_line_repair_info/README.rst
  account_move_line_repair_info/__init__.py
  account_move_line_repair_info/__manifest__.py
  account_move_line_repair_info/hooks.py
  account_move_line_repair_info/i18n/account_move_line_repair_info.pot
  account_move_line_repair_info/models/__init__.py
  account_move_line_repair_info/models/account_move.py
  account_move_line_repair_info/models/repair_order.py
  account_move_line_repair_info/models/stock_valuation_layer.py
  account_move_line_repair_info/readme/CONTRIBUTORS.rst
  account_move_line_repair_info/readme/DESCRIPTION.rst
  account_move_line_repair_info/readme/USAGE.rst
  account_move_line_repair_info/security/account_security.xml
  account_move_line_repair_info/static/description/icon.png
  account_move_line_repair_info/static/description/index.html
  account_move_line_repair_info/tests/__init__.py
  account_move_line_repair_info/tests/test_account_move_line_repair_info.py
  account_move_line_repair_info/views/account_move_view.xml
  setup/account_move_line_repair_info/odoo/addons/account_move_line_repair_info
  setup/account_move_line_repair_info/setup.py
Labels: bot is merging ⏳

#1904 [15.0][FIX] account_asset_management: Allow to unlink w/o billing permission
  account_asset_management/models/account_move.py
Labels: approved, bot is merging ⏳

#1587 [IMP] account_menu: Show Account move lines on Partner
  account_menu/__manifest__.py
  account_menu/views/view_account_move_line.xml
Labels: bot is merging ⏳, stale
