Repository OCA/account-financial-tools, pull requests merged in 2024-02, with the labels that each got.

#1813 [FIX] account_loan: use company_ids in ir.rule multi-company
  account_loan/data/ir_sequence_data.xml
  account_loan/security/account_loan_security.xml
  account_loan/tests/test_loan.py
Labels: bot is merging ⏳

#1457 [FWD][14.0] [IMP] `product_category_tax`: copy taxes when creating products programatically
  product_category_tax/models/product_category.py
  product_category_tax/models/product_product.py
  product_category_tax/models/product_template.py
  product_category_tax/tests/test_product_category_tax.py
Labels: approved, bot is merging ⏳

#1816 [16.0][IMP] account_loan: add multi-company ir_rule for 'account_loan_line'
  account_loan/models/account_loan_line.py
  account_loan/security/account_loan_security.xml
Labels: approved, bot is merging ⏳

#1567 [15.0][ENH] account_asset_management: default salvage value
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/views/account_asset_profile.xml
Labels: approved, ready to merge, bot is merging ⏳

#1820 [16.0][ENH] account_asset_management: default salvage value on profile
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/views/account_asset_profile.xml
Labels: approved, bot is merging ⏳

#1789 [14.0][MIG] account_partner_required: Migration to 14.0
  account_partner_required/README.rst
  account_partner_required/__init__.py
  account_partner_required/__manifest__.py
  account_partner_required/i18n/account_partner_required.pot
  account_partner_required/i18n/ar.po
  account_partner_required/i18n/bs.po
  account_partner_required/i18n/cs.po
  account_partner_required/i18n/de.po
  account_partner_required/i18n/en_GB.po
  account_partner_required/i18n/es.po
  account_partner_required/i18n/es_CR.po
  account_partner_required/i18n/es_EC.po
  account_partner_required/i18n/es_MX.po
  account_partner_required/i18n/fr.po
  account_partner_required/i18n/hr.po
  account_partner_required/i18n/hu.po
  account_partner_required/i18n/it.po
  account_partner_required/i18n/ja.po
  account_partner_required/i18n/lt.po
  account_partner_required/i18n/mk.po
  account_partner_required/i18n/mn.po
  account_partner_required/i18n/nb.po
  account_partner_required/i18n/nl.po
  account_partner_required/i18n/nl_BE.po
  account_partner_required/i18n/nl_NL.po
  account_partner_required/i18n/pt.po
  account_partner_required/i18n/pt_BR.po
  account_partner_required/i18n/ro.po
  account_partner_required/i18n/ru.po
  account_partner_required/i18n/sl.po
  account_partner_required/i18n/sv.po
  account_partner_required/i18n/tr.po
  account_partner_required/i18n/tr_TR.po
  account_partner_required/i18n/zh_CN.po
  account_partner_required/i18n/zh_TW.po
  account_partner_required/models/__init__.py
  account_partner_required/models/account.py
  account_partner_required/readme/CONFIGURE.rst
  account_partner_required/readme/CONTRIBUTORS.rst
  account_partner_required/readme/DESCRIPTION.rst
  account_partner_required/readme/USAGE.rst
  account_partner_required/static/description/icon.png
  account_partner_required/static/description/index.html
  account_partner_required/tests/__init__.py
  account_partner_required/tests/test_account_partner_required.py
  account_partner_required/views/account.xml
  setup/account_partner_required/odoo/addons/account_partner_required
  setup/account_partner_required/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1586 [IMP] account_menu: Show Account move lines on Partner
  account_menu/__manifest__.py
  account_menu/views/view_account_move_line.xml
Labels: bot is merging ⏳
