Repository OCA/account-financial-tools, pull requests merged in 2024-11, with the labels that each got.

#1957 [16.0] [ADD] account_chart_update_multilang - new module
  account_chart_update/tests/__init__.py
  account_chart_update/tests/common.py
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
  account_chart_update_multilang/README.rst
  account_chart_update_multilang/__init__.py
  account_chart_update_multilang/__manifest__.py
  account_chart_update_multilang/readme/CONFIGURE.md
  account_chart_update_multilang/readme/CONTRIBUTORS.md
  account_chart_update_multilang/readme/DESCRIPTION.md
  account_chart_update_multilang/readme/USAGE.md
  account_chart_update_multilang/static/description/icon.png
  account_chart_update_multilang/static/description/index.html
  account_chart_update_multilang/tests/__init__.py
  account_chart_update_multilang/tests/test_account_chart_update_multilang.py
  account_chart_update_multilang/wizards/__init__.py
  account_chart_update_multilang/wizards/wizard_chart_update.py
  account_chart_update_multilang/wizards/wizard_chart_update_views.xml
  setup/account_chart_update_multilang/odoo/addons/account_chart_update_multilang
  setup/account_chart_update_multilang/setup.py
Labels: needs review, approved, bot is merging ⏳

#1958 [13.0][BKP][ADD]account_move_post_date_user
  account_move_post_date_user/README.rst
  account_move_post_date_user/__init__.py
  account_move_post_date_user/__manifest__.py
  account_move_post_date_user/i18n/account_move_post_date_user.pot
  account_move_post_date_user/i18n/it.po
  account_move_post_date_user/models/__init__.py
  account_move_post_date_user/models/account_move.py
  account_move_post_date_user/readme/CONTRIBUTORS.rst
  account_move_post_date_user/readme/DESCRIPTION.rst
  account_move_post_date_user/static/description/icon.png
  account_move_post_date_user/static/description/index.html
  account_move_post_date_user/tests/__init__.py
  account_move_post_date_user/tests/test_account_move_post_date_user.py
  account_move_post_date_user/views/account_move.xml
  setup/account_move_post_date_user/odoo/addons/account_move_post_date_user
  setup/account_move_post_date_user/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1968 [FIX] base_vat_optional_vies: don't block mass checks
  base_vat_optional_vies/README.rst
  base_vat_optional_vies/__manifest__.py
  base_vat_optional_vies/models/res_config_settings.py
  base_vat_optional_vies/models/res_partner.py
  base_vat_optional_vies/readme/CONTRIBUTORS.rst
  base_vat_optional_vies/readme/DESCRIPTION.rst
  base_vat_optional_vies/static/description/index.html
  base_vat_optional_vies/tests/__init__.py
  base_vat_optional_vies/tests/tes_config_settings.py
  base_vat_optional_vies/tests/test_config_settings.py
  base_vat_optional_vies/tests/test_res_partner.py
Labels: approved, bot is merging ⏳

#1732 [16.0][MIG] account_lock_to_date
  account_lock_to_date/README.rst
  account_lock_to_date/__init__.py
  account_lock_to_date/__manifest__.py
  account_lock_to_date/i18n/account_lock_to_date.pot
  account_lock_to_date/i18n/es.po
  account_lock_to_date/i18n/fr.po
  account_lock_to_date/models/__init__.py
  account_lock_to_date/models/account_move.py
  account_lock_to_date/models/res_company.py
  account_lock_to_date/readme/CONTRIBUTORS.rst
  account_lock_to_date/readme/DESCRIPTION.rst
  account_lock_to_date/readme/USAGE.rst
  account_lock_to_date/security/ir.model.access.csv
  account_lock_to_date/static/description/icon.png
  account_lock_to_date/static/description/index.html
  account_lock_to_date/tests/__init__.py
  account_lock_to_date/tests/test_account_lock_to_date_update.py
  account_lock_to_date/wizards/__init__.py
  account_lock_to_date/wizards/account_update_lock_to_date.py
  account_lock_to_date/wizards/account_update_lock_to_date.xml
  setup/account_lock_to_date/odoo/addons/account_lock_to_date
  setup/account_lock_to_date/setup.py
Labels: approved, bot is merging ⏳

#1932 [13.0][BKP][ADD] account_journal_restrict_mode
  .copier-answers.yml
  .eslintrc.yml
  .github/workflows/pre-commit.yml
  .github/workflows/stale.yml
  .github/workflows/test.yml
  .gitignore
  .oca_hooks.cfg
  .pre-commit-config.yaml
  account_journal_restrict_mode/README.rst
  account_journal_restrict_mode/__init__.py
  account_journal_restrict_mode/__manifest__.py
  account_journal_restrict_mode/hooks.py
  account_journal_restrict_mode/i18n/account_journal_restrict_mode.pot
  account_journal_restrict_mode/i18n/es.po
  account_journal_restrict_mode/i18n/it.po
  account_journal_restrict_mode/models/__init__.py
  account_journal_restrict_mode/models/account_journal.py
  account_journal_restrict_mode/readme/CONTRIBUTORS.rst
  account_journal_restrict_mode/readme/DESCRIPTION.rst
  account_journal_restrict_mode/readme/ROADMAP.rst
  account_journal_restrict_mode/static/description/icon.png
  account_journal_restrict_mode/static/description/index.html
  account_journal_restrict_mode/tests/__init__.py
  account_journal_restrict_mode/tests/test_account_journal_restrict_mode.py
  setup/account_journal_restrict_mode/odoo/addons/account_journal_restrict_mode
  setup/account_journal_restrict_mode/setup.py
Labels: approved, bot is merging ⏳

#1976 [16.0][FIX] account_chart_update_multilang: error when English language is not active.
  account_chart_update_multilang/tests/test_account_chart_update_multilang.py
  account_chart_update_multilang/wizards/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#1970 [FIX] account_usability. apply same implied_ids settings as in EE (account_accountant module).
  account_usability/security/res_groups.xml
Labels: bot is merging ⏳

#1981 [18.0][MIG] account_usability: Migration to 18.0
  account_usability/README.rst
  account_usability/__init__.py
  account_usability/__manifest__.py
  account_usability/data/ir_module_category.xml
  account_usability/demo/res_groups.xml
  account_usability/i18n/account_usability.pot
  account_usability/i18n/es.po
  account_usability/i18n/fr.po
  account_usability/i18n/fr_FR.po
  account_usability/i18n/hr.po
  account_usability/i18n/it.po
  account_usability/i18n/nl.po
  account_usability/i18n/pt.po
  account_usability/i18n/pt_BR.po
  account_usability/i18n/tr.po
  account_usability/models/__init__.py
  account_usability/models/account_group.py
  account_usability/models/account_tag.py
  account_usability/models/account_tax_group.py
  account_usability/models/res_config_settings.py
  account_usability/pyproject.toml
  account_usability/readme/CONTRIBUTORS.md
  account_usability/readme/DESCRIPTION.md
  account_usability/readme/DEVELOP.md
  account_usability/readme/ROADMAP.md
  account_usability/security/res_groups.xml
  account_usability/static/description/icon.png
  account_usability/static/description/index.html
  account_usability/views/menu.xml
  account_usability/views/res_config_settings_views.xml
  account_usability/views/view_account_bank_statement.xml
  account_usability/views/view_account_group.xml
  account_usability/views/view_account_move_line.xml
  account_usability/views/view_account_tag.xml
  checklog-odoo.cfg
Labels: bot is merging ⏳
