Repository OCA/account-financial-tools, pull requests merged in 2024-10, with the labels that each got.

#1929 [17.0][MIG] account_move_line_sale_info
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/i18n/es.po
  account_move_line_sale_info/i18n/es_AR.po
  account_move_line_sale_info/i18n/it.po
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/pyproject.toml
  account_move_line_sale_info/readme/CONTRIBUTORS.md
  account_move_line_sale_info/readme/DESCRIPTION.md
  account_move_line_sale_info/readme/USAGE.md
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/static/description/index.html
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
Labels: approved, bot is merging ⏳

#1945 [16.0][BKP][IMP] account_journal_restrict_mode: make field readonly to not allow editing in the view
  account_journal_restrict_mode/models/account_journal.py
Labels: bot is merging ⏳

#1869 [16.0][MIG] account_bank_statement_chatter: Migration to 16.0
  account_bank_statement_chatter/README.rst
  account_bank_statement_chatter/__init__.py
  account_bank_statement_chatter/__manifest__.py
  account_bank_statement_chatter/i18n/account_bank_statement_chatter.pot
  account_bank_statement_chatter/i18n/es.po
  account_bank_statement_chatter/models/__init__.py
  account_bank_statement_chatter/models/account_bank_statement.py
  account_bank_statement_chatter/readme/CONTRIBUTORS.rst
  account_bank_statement_chatter/readme/DESCRIPTION.rst
  account_bank_statement_chatter/readme/USAGE.rst
  account_bank_statement_chatter/static/description/icon.png
  account_bank_statement_chatter/static/description/index.html
  account_bank_statement_chatter/views/account_bank_statement_views.xml
  setup/account_bank_statement_chatter/odoo/addons/account_bank_statement_chatter
  setup/account_bank_statement_chatter/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#1930 [17.0][FIX] account_move_template: Fixed tax and payment term errors while generating journal entries from template
  account_move_template/models/account_move_template.py
  account_move_template/tests/test_account_move_template_options.py
  account_move_template/wizard/account_move_template_run.py
Labels: approved, bot is merging ⏳

#1950 [FIX] account_loan: Set name on line in order to make it compatible with assets
  account_loan/wizard/account_loan_post.py
Labels: bot is merging ⏳

#1952 [16.0][FIX] account_loan: Set name on line in order to make it compatible with assets
  account_loan/wizards/account_loan_post.py
Labels: bot is merging ⏳

#1951 [15.0][FIX] account_loan: Set name on line in order to make it compatible with assets
  account_loan/wizard/account_loan_post.py
Labels: bot is merging ⏳

#1953 [17.0][MIG] purchase_unreconciled
  purchase_unreconciled/README.rst
  purchase_unreconciled/__init__.py
  purchase_unreconciled/__manifest__.py
  purchase_unreconciled/models/__init__.py
  purchase_unreconciled/models/account_move_line.py
  purchase_unreconciled/models/company.py
  purchase_unreconciled/models/purchase_order.py
  purchase_unreconciled/models/res_config_settings.py
  purchase_unreconciled/pyproject.toml
  purchase_unreconciled/readme/CONTRIBUTORS.md
  purchase_unreconciled/readme/DESCRIPTION.md
  purchase_unreconciled/readme/USAGE.md
  purchase_unreconciled/security/ir.model.access.csv
  purchase_unreconciled/static/description/index.html
  purchase_unreconciled/tests/__init__.py
  purchase_unreconciled/tests/test_purchase_unreconciled.py
  purchase_unreconciled/views/purchase_order_view.xml
  purchase_unreconciled/views/res_config_settings_view.xml
  purchase_unreconciled/wizards/__init__.py
  purchase_unreconciled/wizards/purchase_unreconciled_exceeded.py
  purchase_unreconciled/wizards/purchase_unreconciled_exceeded_view.xml
Labels: approved, bot is merging ⏳

#1959 [16.0][FIX] account_chart_update: fix _update_accounts when creating account
  account_chart_update/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳
