Repository OCA/account-financial-tools, pull requests merged in 2024-09, with the labels that each got.

#1662 [14.0] account_check_deposit: backport improvements from v16
  account_check_deposit/models/account_check_deposit.py
Labels: bot is merging ⏳, stale

#1895 [14.0][FIX] - incompatibility with account_invoice_constraint_chronology
  account_move_name_sequence/models/account_move.py
Labels: approved, ready to merge, bot is merging ⏳

#1940 [FIX] [16.0] account_asset_management: Analytic Account Migration Script
  account_asset_management/README.rst
  account_asset_management/migrations/16.0.1.0.0/pre-migration.py
  account_asset_management/models/account_asset.py
  account_asset_management/readme/CONTRIBUTORS.rst
  account_asset_management/static/description/index.html
Labels: approved, bot is merging ⏳

#1939 [16.0][IMP] account_asset_number: Add Barcode type Configuration
  account_asset_number/models/account_asset_profile.py
  account_asset_number/report/account_asset_number_report.xml
  account_asset_number/views/account_asset_profile.xml
Labels: approved, bot is merging ⏳

#1938 [17.0][ADD] account_asset_force_account: New module account_asset_force_account
  account_asset_force_account/README.rst
  account_asset_force_account/__init__.py
  account_asset_force_account/__manifest__.py
  account_asset_force_account/i18n/ca_ES.po
  account_asset_force_account/i18n/es.po
  account_asset_force_account/models/__init__.py
  account_asset_force_account/models/account_asset.py
  account_asset_force_account/models/account_asset_line.py
  account_asset_force_account/models/account_move_line.py
  account_asset_force_account/pyproject.toml
  account_asset_force_account/readme/CONTRIBUTORS.md
  account_asset_force_account/readme/DESCRIPTION.md
  account_asset_force_account/readme/USAGE.md
  account_asset_force_account/static/description/icon.png
  account_asset_force_account/static/description/icon.svg
  account_asset_force_account/static/description/index.html
  account_asset_force_account/tests/__init__.py
  account_asset_force_account/tests/test_account_asset_management_force_account.py
  account_asset_force_account/views/account_asset.xml
Labels: approved, ready to merge, bot is merging ⏳
