Repository OCA/account-financial-tools, pull requests merged in 2025-07, with the labels that each got.

#1994 [17.0][MIG] account_chart_update_l10n_eu_oss
  account_chart_update_l10n_eu_oss/README.rst
  account_chart_update_l10n_eu_oss/__init__.py
  account_chart_update_l10n_eu_oss/__manifest__.py
  account_chart_update_l10n_eu_oss/i18n/account_chart_update_l10n_eu_oss.pot
  account_chart_update_l10n_eu_oss/pyproject.toml
  account_chart_update_l10n_eu_oss/readme/CONTRIBUTORS.md
  account_chart_update_l10n_eu_oss/readme/DESCRIPTION.md
  account_chart_update_l10n_eu_oss/static/description/icon.png
  account_chart_update_l10n_eu_oss/static/description/index.html
  account_chart_update_l10n_eu_oss/wizard/__init__.py
  account_chart_update_l10n_eu_oss/wizard/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#2114 [18.0][ADD] Add module account_dashboard_banner
  account_dashboard_banner/README.rst
  account_dashboard_banner/__init__.py
  account_dashboard_banner/__manifest__.py
  account_dashboard_banner/i18n/fr.po
  account_dashboard_banner/models/__init__.py
  account_dashboard_banner/models/account_dashboard_banner_cell.py
  account_dashboard_banner/post_install.py
  account_dashboard_banner/pyproject.toml
  account_dashboard_banner/readme/CONFIGURE.md
  account_dashboard_banner/readme/CONTRIBUTORS.md
  account_dashboard_banner/readme/DESCRIPTION.md
  account_dashboard_banner/readme/USAGE.md
  account_dashboard_banner/security/ir.model.access.csv
  account_dashboard_banner/static/description/account_dashboard_banner.png
  account_dashboard_banner/static/description/banner_cell_config.png
  account_dashboard_banner/static/description/cell_form_with_warning.png
  account_dashboard_banner/static/description/index.html
  account_dashboard_banner/static/src/views/account_dashboard_kanban_banner.esm.js
  account_dashboard_banner/static/src/views/account_dashboard_kanban_banner.xml
  account_dashboard_banner/tests/__init__.py
  account_dashboard_banner/tests/test_banner.py
  account_dashboard_banner/views/account_dashboard_banner_cell.xml
  account_dashboard_banner/views/account_journal_dashboard.xml
Labels: bot is merging ⏳

#2120 [16.0][FIX] account_move_template: Payment Term Error
  account_move_template/wizard/account_move_template_run.py
Labels: approved, bot is merging ⏳

#2096 [18.0][MIG] product_category_tax: Migration to 18.0
  product_category_tax/README.rst
  product_category_tax/__init__.py
  product_category_tax/__manifest__.py
  product_category_tax/i18n/es.po
  product_category_tax/i18n/product_category_tax.pot
  product_category_tax/models/__init__.py
  product_category_tax/models/product_category.py
  product_category_tax/models/product_product.py
  product_category_tax/models/product_template.py
  product_category_tax/pyproject.toml
  product_category_tax/readme/CONFIGURATION.rst
  product_category_tax/readme/CONTRIBUTORS.md
  product_category_tax/readme/DESCRIPTION.md
  product_category_tax/readme/USAGE.md
  product_category_tax/static/description/icon.png
  product_category_tax/static/description/index.html
  product_category_tax/tests/__init__.py
  product_category_tax/tests/test_product_category_tax.py
  product_category_tax/views/product_category.xml
  product_category_tax/views/product_template.xml
Labels: approved, ready to merge, bot is merging ⏳

#2020 [17.0][MIG] account_lock_to_date: Migration to 17.0
  account_lock_to_date/README.rst
  account_lock_to_date/__init__.py
  account_lock_to_date/__manifest__.py
  account_lock_to_date/i18n/account_lock_to_date.pot
  account_lock_to_date/i18n/es.po
  account_lock_to_date/i18n/fr.po
  account_lock_to_date/i18n/it.po
  account_lock_to_date/models/__init__.py
  account_lock_to_date/models/account_move.py
  account_lock_to_date/models/res_company.py
  account_lock_to_date/pyproject.toml
  account_lock_to_date/readme/CONTRIBUTORS.md
  account_lock_to_date/readme/DESCRIPTION.md
  account_lock_to_date/readme/USAGE.md
  account_lock_to_date/security/ir.model.access.csv
  account_lock_to_date/static/description/icon.png
  account_lock_to_date/static/description/index.html
  account_lock_to_date/tests/__init__.py
  account_lock_to_date/tests/test_account_lock_to_date_update.py
  account_lock_to_date/wizards/__init__.py
  account_lock_to_date/wizards/account_update_lock_to_date.py
  account_lock_to_date/wizards/account_update_lock_to_date.xml
Labels: bot is merging ⏳
