Repository OCA/account-financial-tools, pull requests merged in 2025-01, with the labels that each got.

#1998 [17.0][FIX] account_asset_management: fix asset report
  account_asset_management/report/account_asset_report_xls.py
Labels: bot is merging ⏳

#1977 [18.0][MIG] account_fiscal_year: Migration to 18.0
  account_fiscal_year/README.rst
  account_fiscal_year/__init__.py
  account_fiscal_year/__manifest__.py
  account_fiscal_year/i18n/account_fiscal_year.pot
  account_fiscal_year/i18n/es.po
  account_fiscal_year/i18n/fr.po
  account_fiscal_year/i18n/fr_FR.po
  account_fiscal_year/i18n/it.po
  account_fiscal_year/i18n/nl.po
  account_fiscal_year/models/__init__.py
  account_fiscal_year/models/account_fiscal_year.py
  account_fiscal_year/models/res_company.py
  account_fiscal_year/pyproject.toml
  account_fiscal_year/readme/CONTRIBUTORS.md
  account_fiscal_year/readme/DESCRIPTION.md
  account_fiscal_year/readme/ROADMAP.md
  account_fiscal_year/security/account_fiscal_year_rule.xml
  account_fiscal_year/security/ir.model.access.csv
  account_fiscal_year/static/description/account_fiscal_year_form.png
  account_fiscal_year/static/description/icon.png
  account_fiscal_year/static/description/index.html
  account_fiscal_year/static/description/res_company_list.png
  account_fiscal_year/tests/__init__.py
  account_fiscal_year/tests/test_account_fiscal_year.py
  account_fiscal_year/views/account_fiscal_year_views.xml
  account_fiscal_year/views/res_company_views.xml
Labels: approved, ready to merge, bot is merging ⏳

#2002 [16.0][FIX] account_chart_update: Translatable fields without transla…
  account_chart_update_multilang/tests/test_account_chart_update_multilang.py
  account_chart_update_multilang/wizards/wizard_chart_update.py
Labels: approved, bot is merging ⏳

#2014 [15.0][FIX]account_spread_cost_revenue: Total amount different currency
  account_spread_cost_revenue/README.rst
  account_spread_cost_revenue/models/account_spread.py
  account_spread_cost_revenue/readme/CONTRIBUTORS.rst
  account_spread_cost_revenue/static/description/index.html
  account_spread_cost_revenue/tests/test_account_invoice_spread.py
Labels: approved, bot is merging ⏳

#2016 [MIG] account_move_name_sequence: Migration to 18.0
  .bandit
  .eslintrc.json
  .flake8
  .flake8-optional
  .isort.cfg
  .oca_hooks-autofix.cfg
  .oca_hooks.cfg
  .pre-commit-config-autofix.yaml
  .pre-commit-config-optional.yaml
  .prettierrc.yml
  .pylintrc-optional
  account_move_name_sequence/README.rst
  account_move_name_sequence/__init__.py
  account_move_name_sequence/__manifest__.py
  account_move_name_sequence/demo/account_journal_demo.xml
  account_move_name_sequence/demo/ir_sequence_demo.xml
  account_move_name_sequence/hooks.py
  account_move_name_sequence/i18n/account_move_name_sequence.pot
  account_move_name_sequence/i18n/ar.po
  account_move_name_sequence/i18n/es.po
  account_move_name_sequence/i18n/fr.po
  account_move_name_sequence/i18n/hr.po
  account_move_name_sequence/i18n/it.po
  account_move_name_sequence/i18n/sl.po
  account_move_name_sequence/models/__init__.py
  account_move_name_sequence/models/account_journal.py
  account_move_name_sequence/models/account_move.py
  account_move_name_sequence/models/ir_sequence.py
  account_move_name_sequence/pyproject.toml
  account_move_name_sequence/readme/CONFIGURE.md
  account_move_name_sequence/readme/CONTRIBUTORS.md
  account_move_name_sequence/readme/DESCRIPTION.md
  account_move_name_sequence/security/ir.model.access.csv
  account_move_name_sequence/static/description/icon.png
  account_move_name_sequence/static/description/index.html
  account_move_name_sequence/tests/__init__.py
  account_move_name_sequence/tests/test_account_incoming_supplier_invoice.py
  account_move_name_sequence/tests/test_account_move_name_seq.py
  account_move_name_sequence/tests/test_sequence_concurrency.py
  account_move_name_sequence/views/account_journal_views.xml
  account_move_name_sequence/views/account_move_views.xml
  doc8.ini
  pyproject.toml
Labels: approved, bot is merging ⏳

#2019 [17.0][FIX] account_loan: Add freeze_time to tests to avoid errors on some specific dates
  account_loan/tests/test_loan.py
Labels: approved, bot is merging ⏳

#2001 [18.0][MIG] account_cash_deposit
  account_cash_deposit/README.rst
  account_cash_deposit/__init__.py
  account_cash_deposit/__manifest__.py
  account_cash_deposit/data/cash_unit_cad.xml
  account_cash_deposit/data/cash_unit_chf.xml
  account_cash_deposit/data/cash_unit_eur.xml
  account_cash_deposit/data/cash_unit_usd.xml
  account_cash_deposit/data/sequence.xml
  account_cash_deposit/i18n/account_cash_deposit.pot
  account_cash_deposit/i18n/es.po
  account_cash_deposit/i18n/fr.po
  account_cash_deposit/i18n/hr.po
  account_cash_deposit/i18n/it.po
  account_cash_deposit/models/__init__.py
  account_cash_deposit/models/account_cash_deposit.py
  account_cash_deposit/models/cash_unit.py
  account_cash_deposit/models/res_currency.py
  account_cash_deposit/pyproject.toml
  account_cash_deposit/readme/CONFIGURE.md
  account_cash_deposit/readme/CONTRIBUTORS.md
  account_cash_deposit/readme/DESCRIPTION.md
  account_cash_deposit/readme/USAGE.md
  account_cash_deposit/report/report.xml
  account_cash_deposit/report/report_cashdeposit.xml
  account_cash_deposit/security/ir.model.access.csv
  account_cash_deposit/security/security.xml
  account_cash_deposit/static/description/cash_deposit_form.png
  account_cash_deposit/static/description/currency_form_view.png
  account_cash_deposit/static/description/icon.png
  account_cash_deposit/static/description/index.html
  account_cash_deposit/tests/__init__.py
  account_cash_deposit/tests/test_cash_deposit.py
  account_cash_deposit/views/account_cash_deposit.xml
  account_cash_deposit/views/cash_unit.xml
  account_cash_deposit/views/res_currency.xml
  account_cash_deposit/wizards/__init__.py
  account_cash_deposit/wizards/account_cash_order_reception.py
  account_cash_deposit/wizards/account_cash_order_reception_view.xml
Labels: bot is merging ⏳
