Repository OCA/account-financial-tools, pull requests merged in 2025-03, with the labels that each got.

#2043 [FIX] account_asset_force_account: Fixed asset_account_id computation
  account_asset_force_account/models/account_asset.py
Labels: bot is merging ⏳

#2047 [17.0][ENH] account_asset_management: default salvage value on profile
  account_asset_management/models/account_asset.py
  account_asset_management/models/account_asset_profile.py
  account_asset_management/tests/test_account_asset_management.py
  account_asset_management/views/account_asset_profile.xml
Labels: approved, bot is merging ⏳

#2044 [16.0][FIX] account_move_template: Post-install test + fallback to load CoA
  account_move_template/tests/test_account_move_template_options.py
Labels: bot is merging ⏳

#1942 [14.0][IMP] account_lock_to_date: bypass functionality via context
  account_lock_to_date/models/account_move.py
  account_lock_to_date/tests/test_account_lock_to_date_update.py
Labels: approved, bot is merging ⏳

#2046 [16.0][FIX] account_cash_deposit: Post-install test + fallback to load CoA
  account_cash_deposit/README.rst
  account_cash_deposit/readme/CONFIGURE.rst
  account_cash_deposit/readme/USAGE.rst
  account_cash_deposit/static/description/index.html
  account_cash_deposit/tests/test_cash_deposit.py
Labels: approved, bot is merging ⏳

#2008 [18.0][IMP] account_journal_restrict_mode: do not force hash on bank and cash journals
  account_journal_restrict_mode/README.rst
  account_journal_restrict_mode/hooks.py
  account_journal_restrict_mode/models/account_journal.py
  account_journal_restrict_mode/readme/DESCRIPTION.md
  account_journal_restrict_mode/readme/ROADMAP.md
  account_journal_restrict_mode/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#1943 [14.0][IMP] account_check_deposit: users in invoicing group allowed to make check deposit
  account_check_deposit/security/ir.model.access.csv
  account_check_deposit/views/account_check_deposit_view.xml
Labels: bot is merging ⏳

#2052 [18.0][FIX] account_asset_management: Stop using Form in business modules
  account_asset_management/models/account_move.py
Labels: bot is merging ⏳

#1720 [16.0][MIG] account_move_line_landed_cost_info: Migration to 16.0
  account_move_line_landed_cost_info/README.rst
  account_move_line_landed_cost_info/__init__.py
  account_move_line_landed_cost_info/__manifest__.py
  account_move_line_landed_cost_info/hooks.py
  account_move_line_landed_cost_info/i18n/account_move_line_landed_cost_info.pot
  account_move_line_landed_cost_info/models/__init__.py
  account_move_line_landed_cost_info/models/account_move.py
  account_move_line_landed_cost_info/models/stock_valuation_adjustment_lines.py
  account_move_line_landed_cost_info/readme/CONTRIBUTORS.rst
  account_move_line_landed_cost_info/readme/DESCRIPTION.rst
  account_move_line_landed_cost_info/readme/USAGE.rst
  account_move_line_landed_cost_info/static/description/icon.png
  account_move_line_landed_cost_info/static/description/index.html
  account_move_line_landed_cost_info/tests/__init__.py
  account_move_line_landed_cost_info/tests/test_account_move_line_landed_cost_info.py
  account_move_line_landed_cost_info/views/account_move_view.xml
  setup/account_move_line_landed_cost_info/odoo/addons/account_move_line_landed_cost_info
  setup/account_move_line_landed_cost_info/setup.py
Labels: bot is merging ⏳

#2033 [18.0][MIG] account_move_line_sale_info: Migration to 18.0
  account_move_line_sale_info/README.rst
  account_move_line_sale_info/__init__.py
  account_move_line_sale_info/__manifest__.py
  account_move_line_sale_info/hooks.py
  account_move_line_sale_info/i18n/account_move_line_sale_info.pot
  account_move_line_sale_info/i18n/es.po
  account_move_line_sale_info/i18n/es_AR.po
  account_move_line_sale_info/i18n/it.po
  account_move_line_sale_info/models/__init__.py
  account_move_line_sale_info/models/account_move.py
  account_move_line_sale_info/models/sale_order_line.py
  account_move_line_sale_info/models/stock_move.py
  account_move_line_sale_info/pyproject.toml
  account_move_line_sale_info/readme/CONTRIBUTORS.md
  account_move_line_sale_info/readme/DESCRIPTION.md
  account_move_line_sale_info/readme/USAGE.md
  account_move_line_sale_info/security/account_security.xml
  account_move_line_sale_info/static/description/icon.png
  account_move_line_sale_info/static/description/index.html
  account_move_line_sale_info/tests/__init__.py
  account_move_line_sale_info/tests/test_account_move_line_sale_info.py
  account_move_line_sale_info/views/account_move_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2057 [18.0][MIG] account_move_fiscal_year
  account_move_fiscal_year/README.rst
  account_move_fiscal_year/__init__.py
  account_move_fiscal_year/__manifest__.py
  account_move_fiscal_year/i18n/account_move_fiscal_year.pot
  account_move_fiscal_year/i18n/am.po
  account_move_fiscal_year/i18n/ar.po
  account_move_fiscal_year/i18n/ca.po
  account_move_fiscal_year/i18n/de.po
  account_move_fiscal_year/i18n/es.po
  account_move_fiscal_year/i18n/es_CO.po
  account_move_fiscal_year/i18n/es_EC.po
  account_move_fiscal_year/i18n/fr.po
  account_move_fiscal_year/i18n/fr_FR.po
  account_move_fiscal_year/i18n/gl.po
  account_move_fiscal_year/i18n/hr.po
  account_move_fiscal_year/i18n/hr_HR.po
  account_move_fiscal_year/i18n/it.po
  account_move_fiscal_year/i18n/nl.po
  account_move_fiscal_year/i18n/pt.po
  account_move_fiscal_year/i18n/pt_BR.po
  account_move_fiscal_year/i18n/pt_PT.po
  account_move_fiscal_year/i18n/sl.po
  account_move_fiscal_year/i18n/tr_TR.po
  account_move_fiscal_year/models/__init__.py
  account_move_fiscal_year/models/account_move.py
  account_move_fiscal_year/models/account_move_line.py
  account_move_fiscal_year/models/res_company.py
  account_move_fiscal_year/pyproject.toml
  account_move_fiscal_year/readme/CONTRIBUTORS.md
  account_move_fiscal_year/readme/DESCRIPTION.md
  account_move_fiscal_year/readme/INSTALL.md
  account_move_fiscal_year/readme/USAGE.md
  account_move_fiscal_year/static/description/icon.png
  account_move_fiscal_year/static/description/index.html
  account_move_fiscal_year/tests/__init__.py
  account_move_fiscal_year/tests/test_account_move_fiscal_year.py
  account_move_fiscal_year/views/account_move.xml
  account_move_fiscal_year/views/account_move_line.xml
Labels: approved, ready to merge, bot is merging ⏳
