Repository OCA/account-financial-tools, pull requests merged in 2025-09, with the labels that each got.

#2127 [18.0][MIG] account_fiscal_year_auto_create: Migration to 18.0
  account_fiscal_year_auto_create/README.rst
  account_fiscal_year_auto_create/__init__.py
  account_fiscal_year_auto_create/__manifest__.py
  account_fiscal_year_auto_create/data/ir_cron.xml
  account_fiscal_year_auto_create/i18n/account_fiscal_year_auto_create.pot
  account_fiscal_year_auto_create/i18n/es.po
  account_fiscal_year_auto_create/i18n/fr.po
  account_fiscal_year_auto_create/i18n/fr_FR.po
  account_fiscal_year_auto_create/i18n/hr.po
  account_fiscal_year_auto_create/i18n/it.po
  account_fiscal_year_auto_create/models/__init__.py
  account_fiscal_year_auto_create/models/account_fiscal_year.py
  account_fiscal_year_auto_create/pyproject.toml
  account_fiscal_year_auto_create/readme/CONTRIBUTORS.md
  account_fiscal_year_auto_create/readme/DESCRIPTION.md
  account_fiscal_year_auto_create/static/description/icon.png
  account_fiscal_year_auto_create/static/description/index.html
  account_fiscal_year_auto_create/tests/__init__.py
  account_fiscal_year_auto_create/tests/test_module.py
Labels: approved, ready to merge, bot is merging ⏳

#2090 [18.0][MIG] account_move_print: Migration to 18.0
  account_move_print/README.rst
  account_move_print/__init__.py
  account_move_print/__manifest__.py
  account_move_print/i18n/account_move_print.pot
  account_move_print/i18n/es.po
  account_move_print/i18n/hr.po
  account_move_print/i18n/it.po
  account_move_print/i18n/tr.po
  account_move_print/pyproject.toml
  account_move_print/readme/CONTRIBUTORS.md
  account_move_print/readme/DESCRIPTION.md
  account_move_print/readme/USAGE.md
  account_move_print/report/journal_report.xml
  account_move_print/static/description/icon.png
  account_move_print/static/description/index.html
Labels: approved, ready to merge, bot is merging ⏳

#2060 [15.0][MIG] account_move_line_repair_info: Backport from v16
  account_move_line_repair_info/README.rst
  account_move_line_repair_info/__init__.py
  account_move_line_repair_info/__manifest__.py
  account_move_line_repair_info/hooks.py
  account_move_line_repair_info/i18n/account_move_line_repair_info.pot
  account_move_line_repair_info/i18n/it.po
  account_move_line_repair_info/models/__init__.py
  account_move_line_repair_info/models/account_move.py
  account_move_line_repair_info/models/repair_order.py
  account_move_line_repair_info/models/stock_valuation_layer.py
  account_move_line_repair_info/readme/CONTRIBUTORS.rst
  account_move_line_repair_info/readme/DESCRIPTION.rst
  account_move_line_repair_info/readme/USAGE.rst
  account_move_line_repair_info/security/account_security.xml
  account_move_line_repair_info/static/description/icon.png
  account_move_line_repair_info/static/description/index.html
  account_move_line_repair_info/tests/__init__.py
  account_move_line_repair_info/tests/test_account_move_line_repair_info.py
  account_move_line_repair_info/views/account_move_view.xml
  setup/account_move_line_repair_info/odoo/addons/account_move_line_repair_info
  setup/account_move_line_repair_info/setup.py
Labels: approved, bot is merging ⏳

#2024 [17.0][MIG] account_asset_management_stock_lot: Migration to 17.0
  account_asset_management_stock_lot/README.rst
  account_asset_management_stock_lot/__init__.py
  account_asset_management_stock_lot/__manifest__.py
  account_asset_management_stock_lot/i18n/account_asset_management_stock_lot.pot
  account_asset_management_stock_lot/models/__init__.py
  account_asset_management_stock_lot/models/account_asset.py
  account_asset_management_stock_lot/models/stock_lot.py
  account_asset_management_stock_lot/pyproject.toml
  account_asset_management_stock_lot/readme/CONTRIBUTORS.md
  account_asset_management_stock_lot/readme/DESCRIPTION.md
  account_asset_management_stock_lot/static/description/icon.png
  account_asset_management_stock_lot/static/description/index.html
  account_asset_management_stock_lot/views/account_asset.xml
Labels: approved, bot is merging ⏳

#2105 [18.0][IMP] - account_asset_management : use a method to get assets to compute for better inheritance
  account_asset_management/wizard/account_asset_compute.py
Labels: approved, bot is merging ⏳

#2152 [18.0][FIX] account_chart_update: Create the accounting accounts with the appropriate code
  account_chart_update/tests/test_account_chart_update.py
  account_chart_update/wizard/wizard_chart_update.py
Labels: bot is merging ⏳

#2115 [18.0][ADD] account_dashboard_banner_mis_builder: use MIS Builder in Dashboard Banner
  account_dashboard_banner_mis_builder/README.rst
  account_dashboard_banner_mis_builder/__init__.py
  account_dashboard_banner_mis_builder/__manifest__.py
  account_dashboard_banner_mis_builder/i18n/fr.po
  account_dashboard_banner_mis_builder/models/__init__.py
  account_dashboard_banner_mis_builder/models/account_dashboard_banner_cell.py
  account_dashboard_banner_mis_builder/pyproject.toml
  account_dashboard_banner_mis_builder/readme/CONFIGURE.md
  account_dashboard_banner_mis_builder/readme/CONTRIBUTORS.md
  account_dashboard_banner_mis_builder/readme/DESCRIPTION.md
  account_dashboard_banner_mis_builder/static/description/index.html
  account_dashboard_banner_mis_builder/views/account_dashboard_banner_cell.xml
Labels: bot is merging ⏳
