Repository OCA/account-financial-tools, pull requests merged in 2025-04, with the labels that each got.

#2059 [18.0][MIG] account_maturity_date_default: Migration to version 18.0
  account_maturity_date_default/README.rst
  account_maturity_date_default/__init__.py
  account_maturity_date_default/__manifest__.py
  account_maturity_date_default/i18n/account_maturity_date_default.pot
  account_maturity_date_default/i18n/es.po
  account_maturity_date_default/models/__init__.py
  account_maturity_date_default/models/account_move.py
  account_maturity_date_default/models/account_move_line.py
  account_maturity_date_default/pyproject.toml
  account_maturity_date_default/readme/CONTRIBUTORS.md
  account_maturity_date_default/readme/DESCRIPTION.md
  account_maturity_date_default/static/description/icon.png
  account_maturity_date_default/static/description/index.html
  account_maturity_date_default/tests/__init__.py
  account_maturity_date_default/tests/test_account_move.py
Labels: approved, bot is merging ⏳

#2058 [14.0][IMP] account_loan: pending_principal_amount total
  account_loan/views/account_loan_view.xml
Labels: approved, ready to merge, bot is merging ⏳

#2018 [16.0][FIX] account_move_line_purchase_info: do not consider stock entry lines on revaluations
  account_move_line_purchase_info/README.rst
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/migrations/16.0.2.0.0/post-migration.py
  account_move_line_purchase_info/migrations/16.0.2.0.0/pre-migration.py
  account_move_line_purchase_info/models/account_move.py
  account_move_line_purchase_info/models/purchase_order.py
  account_move_line_purchase_info/models/purchase_order_line.py
  account_move_line_purchase_info/models/stock_move.py
  account_move_line_purchase_info/readme/DESCRIPTION.rst
  account_move_line_purchase_info/static/description/index.html
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
Labels: approved, ready to merge, bot is merging ⏳

#2065 [17.0][FW][FIX] account_move_line_purchase_info: do not consider stock entry lines on revaluations
  account_move_line_purchase_info/README.rst
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/migrations/17.0.2.0.0/post-migration.py
  account_move_line_purchase_info/migrations/17.0.2.0.0/pre-migration.py
  account_move_line_purchase_info/models/account_move.py
  account_move_line_purchase_info/models/purchase_order.py
  account_move_line_purchase_info/models/purchase_order_line.py
  account_move_line_purchase_info/models/stock_move.py
  account_move_line_purchase_info/readme/DESCRIPTION.md
  account_move_line_purchase_info/static/description/index.html
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
  purchase_unreconciled/__manifest__.py
  purchase_unreconciled/models/purchase_order.py
Labels: approved, bot is merging ⏳

#2066 [18.0][FW][FIX] account_move_line_purchase_info: do not consider stock entry lines on revaluations
  account_move_line_purchase_info/README.rst
  account_move_line_purchase_info/__manifest__.py
  account_move_line_purchase_info/migrations/18.0.2.0.0/post-migration.py
  account_move_line_purchase_info/migrations/18.0.2.0.0/pre-migration.py
  account_move_line_purchase_info/models/account_move.py
  account_move_line_purchase_info/models/purchase_order.py
  account_move_line_purchase_info/models/purchase_order_line.py
  account_move_line_purchase_info/models/stock_move.py
  account_move_line_purchase_info/readme/DESCRIPTION.md
  account_move_line_purchase_info/static/description/index.html
  account_move_line_purchase_info/tests/test_account_move_line_purchase_info.py
Labels: approved, bot is merging ⏳

#2034 [18.0][MIG] purchase_unreconciled: Migration to 18.0
  .copier-answers.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  eslint.config.cjs
  purchase_unreconciled/README.rst
  purchase_unreconciled/__init__.py
  purchase_unreconciled/__manifest__.py
  purchase_unreconciled/i18n/it.po
  purchase_unreconciled/i18n/purchase_unreconciled.pot
  purchase_unreconciled/models/__init__.py
  purchase_unreconciled/models/account_move_line.py
  purchase_unreconciled/models/company.py
  purchase_unreconciled/models/purchase_order.py
  purchase_unreconciled/models/res_config_settings.py
  purchase_unreconciled/pyproject.toml
  purchase_unreconciled/readme/CONTRIBUTORS.md
  purchase_unreconciled/readme/DESCRIPTION.md
  purchase_unreconciled/readme/USAGE.md
  purchase_unreconciled/security/ir.model.access.csv
  purchase_unreconciled/static/description/icon.png
  purchase_unreconciled/static/description/index.html
  purchase_unreconciled/tests/__init__.py
  purchase_unreconciled/tests/test_purchase_unreconciled.py
  purchase_unreconciled/views/purchase_order_view.xml
  purchase_unreconciled/views/res_config_settings_view.xml
  purchase_unreconciled/wizards/__init__.py
  purchase_unreconciled/wizards/purchase_unreconciled_exceeded.py
  purchase_unreconciled/wizards/purchase_unreconciled_exceeded_view.xml
Labels: approved, bot is merging ⏳

#2054 [17.0][IMP] account_loan: Edit table in draft
  account_loan/README.rst
  account_loan/models/account_loan.py
  account_loan/models/account_loan_line.py
  account_loan/readme/CONTRIBUTORS.md
  account_loan/static/description/index.html
  account_loan/views/account_loan_lines_view.xml
  account_loan/views/account_loan_view.xml
  account_loan/wizards/account_loan_post.py
Labels: approved, bot is merging ⏳

#2074 [17.0][FIX] account_loan: Always set the correct date to avoid incorrect values
  account_loan/models/account_loan.py
  account_loan/tests/test_loan.py
Labels: approved, bot is merging ⏳

#2077 [17.0][FIX] account_loan: Define the correct date of the lines if payment_on_first_period is not checked.
  account_loan/models/account_loan.py
  account_loan/tests/test_loan.py
Labels: bot is merging ⏳
